COPY "whats_new" FROM stdin;
120	2002-06-12 17:11:23-05	Business Administrators are people who can log into the AO Industries web site and the AOSH in order to maintain an account.  These administrators may now be added, modified, and removed using the new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.admin.AdministratorIndex)'>Administrator Control Panel</A>.
122	2002-07-12 13:35:53-05	Dedicated server customers may now <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.ServerCP)'>Control Server Processes</A> that were previously only accessible to AO Industries' personnel.
160	2004-01-08 00:00:00-06	The <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.ControlIndex)'>Control Panels</A> will now stay consistently responsive.  Previously, we were running our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.backup.AOServBackupIndex)'>Backup System Database</A> and our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.performance.PostgreSQL)'>AOServ System Database</A> on the same physical hardware.  We have modified our code to access multiple PostgreSQL databases on multiple dedicated servers from our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.master.AOServMasterIndex)'>AOServ Master Server</A>.  The control panels will no longer be slowed down while the backup system performs its long queries and updates.\r\n
123	2002-07-12 13:37:59-05	The new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.password.GlobalPasswordSetter)'>Global Password Reset Tool</A> makes setting all of the passwords for one username quick and easy.
125	2002-07-17 00:00:00-05	The <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.email.EmailIndex)'>Email Control Panel</A> now allows an email address to be used multiple times.  As an example, this allows user@domain.com to be delivered to an inbox and forwarded to another email address.
126	2002-08-13 23:51:03-05	Email autoresponders may now be easily configured using our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.email.Inboxes)'>Email Inbox Control Panel</A>.  Manual editing of the <code>.procmailrc</code> files is no longer necessary.
127	2002-08-13 23:55:15-05	We have developed and installed web-based email for all email hosted on any of our servers.  The simplest URL is <A class='@LINK_CLASS' href='http://aoindustries.com/webmail'>http://aoindustries.com/webmail</A>
159	2003-11-16 16:36:13.803834-06	The AO Industries web site and control panels now have a pluggable look and feel.  We will soon release our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.ControlIndex)'>Control Panel</A> code in a reusable form.  Building on the new pluggable look and feel, the control panels may be branded and customized to match any web site and purpose.\r\n
129	2002-09-02 03:03:06-05	Many new features have been added to our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.webmail.WebMail)'>Web Mail</A>, including the ability to manage folders and send attachments.
163	2004-04-11 18:26:17.914395-05	We now support the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.daemon.operatingsystems.Mandrake)'>Mandrake 9.2</A> distribution of the Linux operating system.  We are phasing out the use of the older <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.daemon.operatingsystems.RedHat)'>RedHat 7.2</A> distribution of Linux.  All new servers have Mandrake 9.2 installed by default.  We have currently upgraded our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.services.virtual.VirtualIndex)'>Virtual Hosting</A> servers; all other servers will be upgraded in several weeks.\r\n
164	2004-04-03 00:00:00-06	We have optimized our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.reliability.Firewalls)'>firewall scripts</A> to provide greater networking throughput while keeping network latency lower and more consistent.  These new scripts reduced the number of firewall rules from 7700 to 900 in our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.datacenters.kc.KansasCityDataCenterIndex)'>Kansas City location</A> and will have proportional results in other locations.\r\n
165	2004-04-09 00:00:00-05	Sun's Java SDK version 1.4.2_04 is now available.  This is the default JVM for newly added websites.  To upgrade an existing Java virtual machine, modify your profile script to include this line:<BR>\r\n<BR>\r\n<CODE>. /usr/aoserv/etc/j2sdk1.4.2_04.sh</CODE><BR>\r\n<BR>\r\nFor more details, see the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.FAQ?category=jvms&page=profile)'>JVM Profile Script FAQ</A>.\r\n
152	2003-07-19 12:44:13.773645-05	Sun's Java SDK version 1.4.2 is now available on all servers.  To upgrade an existing Java virtual machine, modify your profile script to include this line:<BR>\r\n<BR>\r\n<CODE>. /usr/aoserv/etc/j2sdk1.4.2.sh</CODE><BR>\r\n<BR>\r\nFor more details, see the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.FAQ?category=jvms&page=profile)'>JVM Profile Script FAQ</A>.\r\n\r\n
153	2003-07-19 17:32:32.32328-05	Added support for PostgreSQL 7.3.3.  Existing installs of PostgreSQL 7.3 have been upgraded.  Support for PostgreSQL 7.3 has been removed.
154	2003-07-20 11:41:03.179136-05	PHP 4.3.2 is now installed.  Any existing site that was running version 4.3.0 has been upgraded.  Support for PHP 4.3.0 has been removed.  Documentation for PHP 4.3.2 is available in our <A class='@LINK_CLASS' href='../docs/'>Full Package Documentation</A> area.\r\n
155	2003-08-20 15:24:00.245728-05	Added PEAR support to our PHP 4.3.2 installations.
80	2001-02-08 05:33:26-06	As the first step in developing our new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.ControlIndex)'>Control Panel</A>, you may now update your <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.business.Profiles)'>Business Profile</A>.
169	2004-09-29 14:25:08.965496-05	We now accept Discover cards for both one-time payments and automatic payments. To provide the card numbers, please call us at (866) 270-6195 or use our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.company.Contact)'>Contact Us Form</A>, making sure to select the "Encrypt Message" option.
158	2003-11-05 21:57:22.039324-06	To avoid conflicts while in failover mode, sendmail no longer listens on localhost.  This means that your SMTP server for your applications will have to be one of the IP addresses on the machine, or a hostname that resolves to an IP address on the machine.  In our default setup, mail.<i>yourdomain.com</i> should be used as the SMTP server for your applications.\r\n
156	2003-11-05 21:53:38.191529-06	The new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.IPAddressCP)'>IP Address Control Panel</A> allows users with a private IP address or a managed server to configure which services are listening, monitored, and opened through firewalls.\r\n
33	2000-09-17 00:00:00-05	Password strength enforced during sign up and password changes.  You may also <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.client.AOServClientIndex)'>Test the Strength of Passwords</A>
39	2000-10-06 00:00:00-05	Shared HTTPS available for all accounts as <code>https://secure.aoindustries.com/mysite/...</code> - please <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.ticket.CreateTicket)'>submit a ticket</A> to have the HTTPS mappings enabled enabled.
50	2000-10-20 00:00:00-05	<A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.FAQ)'>Frequently Asked Questions (FAQs)</A> created
92	2001-05-17 04:01:04-05	In order to promote communication between our clients, we now support several <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.community.ListServers)'>E-Mail Lists</A>.  The lists cover a variety of subjects from Apache to Xerces.
161	2004-01-12 00:21:30.304998-06	We have added an output caching layer to our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.framework.AOWebFrameworkIndex)'>AOWeb Framework</A>.  This caching is automatically performed for pages derived from <A class='@LINK_CLASS' href='../docs/aoweb-framework/com/aoindustries/website/framework/AutoListPage.html'>AutoListPage</A> and <A class='@LINK_CLASS' href='../docs/aoweb-framework/com/aoindustries/website/framework/HTMLInputStreamPage.html'>HTMLInputStreamPage</A>.<BR>\r\n<BR>\r\nWhen benchmarking our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.HomePage)'>Home Page</A>, the throughput went from 75 requests/second to 840 request/second, a 1000% improvement.  The Apache and Tomcat combination on our web server is now capable of producing 40 MB/sec of dynamic content on a single CPU.<BR>\r\n<BR>\r\nAny user of the AOWeb Framework classes will see these same performance boosts in their websites.\r\n
96	2001-05-24 14:36:41-05	Email inbox passwords may now be reset by clicking the <code>Edit</code> option in <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.email.Inboxes)'>The Email Inbox Control Panel</A>.
98	2001-06-01 19:26:22-05	The JDBC access to InterBase is now working properly.  InterBase support for <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.database.Javatator)'>Javatator</A> has been restored.
99	2001-06-14 08:40:23-05	Our new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.ticket.TicketIndex)'>Customer Service Ticket Database</A> lets our customers submit new service requests and check the progress of existing requests.
109	2001-11-08 01:50:11-06	The developmental <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.AOServIndex)'>AO Serv Documentation</A> is now available.
110	2001-11-10 17:20:55-06	The old <code>cgi-bin/restart</code> Java VM restart mechanism has been replaced by new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.client.aosh.AOSHCommands?command=start_jvm)'>start_jvm</A> and <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.client.aosh.AOSHCommands?command=stop_jvm)'>stop_jvm</A> AOSH commands.  For convienence, we have also installed a <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.httpd.JVMControl)'>Java Virtual Machine Control Panel</A>.
111	2001-11-11 17:53:17-06	The <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.Documentation)'>AO Serv Docs</A> are available for download in both <code>.zip</code> and <code>.tgz</code> formats.
112	2001-11-11 17:54:03-06	New <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.EditDNS)'>DNS Control Panel</A> provides complete control over the name servers.
113	2002-01-18 00:00:00-06	Moved the AO Serv Master server to a dedicated box to greatly improve the performance of the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.AOServIndex)'>AO Serv System</A>
115	2002-01-23 02:04:49-06	The <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.password.PasswordIndex)'>Password Control Panel</A> has been expanded to include web site, AO Serv, shell, email, FTP, MySQL, and PostgreSQL accounts.
116	2002-01-26 13:50:21-06	We have released the first version of our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.httpd.HttpdIndex)'>Web Site Control Panel</A>, allowing our users to add new web sites and Java virtual machines to our servers.
117	2002-04-07 00:10:39-06	Our new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.database.DatabaseIndex)'>Database Control Panel</A> gives our clients complete control over the MySQL and PostgreSQL RDBMS.  The control panels include the ability to add and remove both users and databases.  In addition, database contents may be dumped with one easy click.
118	2002-06-10 14:04:52-05	<A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.email.SmtpStats)'>SMTP Server Statistics</A> are now available in the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.email.EmailIndex)'>Email Control Panel</A>.
119	2002-06-11 17:04:17-05	We now fully support CVS pservers through our new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.EditCvs)'>CVS Control Panel</A>.
137	2002-11-26 14:03:31-06	We recently developed a new port monitoring system that uses thread pools to get around some limitations of Java IO.  Our previous port monitoring system used a single thread to monitor ports, but some IO processes could not be interrupted with a call to <code>Thread.interrupt()</code>.  Our new system allocates threads as needed, concurrently monitors ports, and internally monitors itself to ensure consistent results.  Overall, we will now catch problems more quickly and accurately, which will allow us to take care of the issues before a client calls and reports the outage.\r\n
46	2000-10-17 00:00:00-05	Weekly and monthly Log File Analysis installed on every site under <code>http://www.mysite.com/analog/</code>
138	2002-12-29 17:38:08.156011-06	Every virtual server now concurrently supports PostgreSQL 7.1.3, PostgresSQL 7.2.3, and PostgreSQL 7.3.  New users may be added in the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.database.PostgresUserCP)'>PostgreSQL User Control Panel</A>.  Once the database administrator user is added, databases may be added using the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.database.PostgresDatabaseCP)'>PostgreSQL Database Control Panel</A>.<BR>\r\n<BR>\r\nThe version of PostgreSQL JDBC driver may be selected by making two changes.  First, edit the <CODE>profile</CODE> script for the Java Virtual Machine, found in <CODE>/www/<i>site_name</i>/bin/profile</CODE> for single-site JVMs or <CODE>/wwwgroup/<i>jvm_name</i>/bin/profile</CODE> for multi-site JVMs.  Second, replace the <CODE>postgresql.jar</CODE> symbolic links in <CODE>lib/</CODE>, <CODE>common/lib/</CODE>, and <CODE>server/lib/</CODE>, depending on the version of Tomcat.<BR>\r\n<BR>\r\nThe version of shared libraries used for PHP may be selected by editing the <CODE>php</CODE> script found in <CODE>/www/<i>site_name</i>/webapps/ROOT/cgi-bin/php</CODE>.<BR>\r\n<BR>\r\nManaged servers may also support these newer versions of PostgreSQL on request.\r\n
141	2003-03-04 01:53:29.086067-06	To reduce the amount of unsolicited emails traveling through our SMTP servers, we added the following real time blacklists:\r\n<PRE>\r\nlist.dsbl.org\r\nblackholes.mail-abuse.org\r\ndialups.mail-abuse.org\r\nrelays.mail-abuse.org\r\nrelays.ordb.org\r\nsbl.spamhaus.org\r\n</PRE>\r\n
162	2004-01-12 20:16:52.246134-06	Sun's Java SDK version 1.4.2_03 is now available. To upgrade an existing Java virtual machine, modify your profile script to include this line:<BR>\r\n<BR>\r\n<CODE>. /usr/aoserv/etc/j2sdk1.4.2_03.sh</CODE><BR>\r\n<BR>\r\nFor more details, see the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.FAQ?category=jvms&page=profile)'>JVM Profile Script FAQ</A>.
143	2003-04-04 13:56:52.501482-06	We recently added two new failover servers to our Kansas City data center.  Each machine is a single Intel P4 2.0A with 1536 MB of RAM on a 4x120 GB IBM ATA/100 RAID5.  These machines are powerful enough to adequately assume the load of any other machine in the event of a hardware failure.<BR>\r\n<BR>\r\nEvery server in our Kansas City data center, which currently includes all of our virtual, managed, and colocated accounts, is mirrored to these machines at least once per day.  Managed and colocated customers may request more frequent mirroring, at the cost of increasing their system load.\r\n
140	2003-02-10 00:00:00-06	For email clients using AO Industries servers as their SMTP server, we now only support authenticated SMTP.  If you get a message saying "Error 5.7.1, Relaying Denied" when trying to send emails, please configure your mail client to login to our SMTP servers using the same username and password as your incoming POP3 or IMAP server.
142	2003-03-04 02:00:48.715097-06	Starting on or near March 16th, 2003, we will no longer support localhost (127.0.0.1) as a SMTP server.  Please use the canonical hostname of the server hosting the application instead, such as <CODE>www7.kc.aoindustries.com</CODE>.  Your help is appreciated as we increase the versatility of our failover system and work toward supporting Virtual Dedicated Server (VDS) packages.
144	2003-04-04 18:26:13.120461-06	Two new Java Virtual Machines (JVMs) have been installed.  For those wanting alternate SSL support, we have installed Cryptix libraries into the JDK located in <CODE>/usr/j2sdk1.4.1_02_cryptix</CODE>.  The profile script can be found at <CODE>/usr/aoserv/etc/j2sdk1.4.1_02_cryptix.sh</CODE>.<BR>\r\n<BR>\r\nAnd for those who like to live on the bleeding-edge, we have installed the beta 1.4.2 JVM in <CODE>/usr/j2sdk1.4.2_beta</CODE>.  The profile script is <CODE>/usr/aoserv/etc/j2sdk1.4.2_beta</CODE>.\r\n
145	2003-04-11 03:56:55.103583-05	Many PERL modules for XML processing have been installed.  Anybody interested in developing XML applications in PERL should consult our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.daemon.SoftwarePackages)'>Software Package List</A> to see what is currently available.
146	2003-05-07 14:15:00.808271-05	Improved existing <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.business.Profiles)'>Business Profile Control Panel</A>.  Added new control panels to <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.business.Disable)'>disable</A> or <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.business.Cancel)'>cancel</A> businesses (accounts).
147	2003-06-28 01:42:21.79807-05	The <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.accounting.AccountHistory)'>Account History</A> has been improved for resellers.  You may now search for transactions by both the account the charges are applied to and the account the charges originate from.\r\n
148	2003-06-28 01:48:00.792648-05	For resellers, we now provide the option of billing your sub-accounts directly.  Those who administrate multiple accounts with AO Industries may find this very helpful.  Determine which account best represents the group of accounts.  If there is no clear winner, we may add a free account for this purpose.  Next, we can change your existing accounts to become sub-accounts of this administrative account.  At this point, logging into the control panel as a member of the administrative account will allow you to control all accounts.  However, when users of a sub-account log into the control panel, they can only see and manipulate their account as before.\r\n
149	2003-07-07 19:17:39.612828-05	Our new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.backup.BackupIndex)'>Backup Control Panel</A> puts our backup system at your fingertips.  You may configure the backup system, explore the files that have been backed-up, and retrieve previous versions of files through your browser.  If you have accidentally deleted a file or want a previous version, you will find most likely find what you need here.\r\n
150	2003-07-17 14:17:28.191885-05	<A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.backup.report.ReportIndex)'>Daily Reports</A> of backup system use are available.  We will soon be charging for disk space beyond the package limits.  Disk space will be the sum of files, databases, and backups.  Please check these reports to see how much space your are currently using.<BR>\r\n<BR>\r\nBefore we charge for disk space, we will provide a control panel to configure the backup system in a very granular manner.  We will also provide tools to easily know how much disk space you are using.  Once these tools are in place, there will be a one-month transition period before charges begin to be applied.\r\n
151	2003-07-18 18:26:26.763051-05	We have recently made significant improvements to our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.webmail.WebMail)'>WebMail Interface</A>.  In addition to streamlined navigation and cleaner layouts, users may now configure many aspects of their account through the new "Settings" button.\r\n
90	2001-05-17 00:48:48-05	Our wildcard certificate from Thawte has arrived for our users on www2.kc.aoindustries.com.  This machine hosts some Level 2 and Level 3 accounts.  We will purchase wildcard certificates for our other servers when client demand warrants the cost.  Please contact us to request the shared HTTPS, so that we may accurately determine the demand for each machine.
103	2001-07-24 16:37:24-05	Upgraded SSH on all servers to OpenSSH.  New host keys have been made for all servers.  You may need to remove the old host keys upon first access.
81	2001-02-16 18:28:23-06	Installed Cocoon 1.8.2 and Xalan 1.2.D02
83	2001-03-30 05:44:25-06	Level 2 and Level 3 clients who want to move to one of our new machines, please contact <a class='@LINK_CLASS' href='mailto:support@aoindustries.com'>support@aoindustries.com</a> asking to be moved.
84	2001-04-17 09:50:12-05	Upon request, Tomcat 3.2.2b3 is now available
85	2001-04-23 00:00:00-05	fftw libraries and headers installed
86	2001-04-25 00:00:00-05	XFree86 upgraded and libpng headers installed
87	2001-04-25 21:08:05-05	Past log file parsing for February and March has been completed.  Parsing will occur on a daily basis, as normal.
88	2001-05-08 21:33:41-05	The upgrade of www1.kc.aoindustries.com to a dual PIII-933 went smoothly.  This machine primarily hosts Level 1 accounts, but some higher levels still reside on it.  Both Tomcat restarts and JSP or XML compiling will be noticeably faster.
93	2001-05-17 04:02:27-05	PostgreSQL upgraded to version 7.0.3 on all servers.  We will give version 7.1 a little more time to settle before upgrading again.
74	2001-01-03 15:17:45-06	The yearly log file analysis has completed.  The results are available in <code>http://www.mysite.com/analog/</code>
34	2000-09-28 00:00:00-05	Jakarta-Cocoon upgraded to version 1.8
91	2001-05-17 01:21:54-05	We have completely re-implemented Majordomo.  These changes have four significant effects.  One, Majordomo is easier for us to install and maintain, leading to faster installation of a Majordomo instance or list.  Two, the installation is isolated between users and more secure.  Three, because of the isolation, we now place more control in the hands of the users.  And four, Majordomo completely works like it is supposed to.  Some of you have been waiting for Majordomo improvements or installs.  We will be upgrading all current users of Majordomo, and adding the new lists soon.  A future development effort will address sequence numbers, digest support, and Majorcool.
94	2001-05-23 23:19:21-05	Apache and Tomcat configurations updated to support mod_jk and the newer AJP13 protocol.  No sites have been automatically changed, but we can upgrade upon request.  Please note that AJP13 is still much slower than AJP12.  Using AJP12, our standard "Hello" servlet processes 544 requests per second.  Using the newer AJP13 protocol, that rate drops to a lowly 38 requests per second.
95	2001-05-23 23:35:10-05	Upgraded the MySQL JDBC drivers to mm.mysql version 2.0.4
104	2001-08-27 01:29:52-05	Upgraded PostgreSQL servers from version 7.0.3 to version 7.1.3.
105	2001-09-25 01:06:35-05	To test the reliability of our clustering options in a real-world environment, the <A class='@LINK_CLASS' href='http://www.aoindustries.com/'>http://www.aoindustries.com/</A> website is now clustered.
106	2001-10-03 21:11:51-05	The new AOServ System is up and running.  We are still working on the GUI client, but the command interpreter is functional.  Try "<code>aosh -i</code>" from a SSH or Telnet connection.  When prompted for a username and password, use the same username and password as for the <A class='@LINK_CLASS' href="http://aoindustries.com/">http://aoindustries.com/</A> web site.  Try "<code>help help</code>" to see all the available commands.
108	2001-10-16 14:47:18-05	The <A class='@LINK_CLASS' href="../docs/aocode-public/">AO Code Public</A> and <A class='@LINK_CLASS' href="../docs/aoserv-client/">AO Serv Client</A> Java API documents are now available.  The JAR files may be downloaded from the <code>/usr/aoserv/lib/</code> directory on any server.
77	2001-01-29 19:32:15-06	Installed the <A class='@LINK_CLASS' href='../docs/php-4.3.0/'>PHP 4 documentation</A>
114	2002-01-19 00:00:00-06	We installed a new firewall and moved the hosts on the <code>209.15.126.0/24</code> subnet to the new <code>209.15.201.0/24</code> subnet.  We will maintain compatibility with the old IP addresses until the end of January.
82	2001-03-30 05:42:41-06	The <a class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.email.EmailIndex)'>Email Control Panel</a> is ready for use.
121	2002-06-28 04:38:47-05	Updated the website with a new look and feel, as well as new content throughout the site.
124	2002-07-09 00:00:00-05	We have performed significant hardware upgrades to virtual servers, including faster CPUs, more RAM, and new hard drives using RAID 5 and RAID 1.  Several new virtual servers exist, so new accounts will be set up on empty, fast hardware.
128	2002-09-02 03:01:35-05	Tomcat 4 is now supported for every Java-enabled account level, from Developer to Premium.  The Developer accounts still use a shared JVM and the sites are isolated from one another using a custom security policy.  To upgrade an existing site, copy your content to a home directory, drop the site in the control panel, add the site back selecting the newer version, and reinstall your content.
130	2002-09-10 10:26:48-05	The new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.linux.LinuxAccountCP)'>Linux Account Control Panel</A> allows you to add, edit, and remove email, ftp, and shell accounts.
132	2002-10-04 00:27:40-05	We have updated our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.daemon.SoftwarePackages)'>Software Package List</A> to include all the software we support.  We also added many more packages to the <A class='@LINK_CLASS' href='../docs/'>Documentation Archive</A>.
133	2002-10-04 00:30:48-05	We now support multiple versions of PHP.  We have done away with the stock RedHat PHP because RedHat has been slow to support the latest versions.  Also, our build of PHP includes support for many options not included in the RedHat shipped builds.  To change the version of PHP, modify your <code>/www/<i>site_name</i>/webapps/ROOT/cgi-bin/php</code> script to call the correct PHP executable.  The available versions of the PHP executable are found in <code>/usr/php-<i>version</i>/bin/php</code>.\r\n
131	2002-10-15 16:06:18-05	We now support WebDAV (mod_dav) for all account levels and can enable it manually upon request.  If the demand for WebDAV proves large enough, we will add a control panel option for it.\r\n\r\n
134	2002-10-18 15:20:27-05	Every server rebooted for kernel upgrade.
135	2002-11-06 05:14:38-06	Comprehensive <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.monitor.MRTG)'>MRTG Graphs</A> are available for every server.
136	2002-11-20 15:30:04-06	We now support Tomcat 4.0.6 and Tomcat 4.1.12.
6	2000-08-19 00:00:00-05	Installed Jakarta-RegExp
7	2000-08-19 00:00:00-05	Installed Jakarta-Oro
8	2000-08-19 00:00:00-05	Installed Jakarta-Ant
9	2000-08-19 00:00:00-05	Installed Xang
10	2000-08-19 00:00:00-05	Installed SOAP
11	2000-08-19 00:00:00-05	Installed Java Activation classes
12	2000-08-19 00:00:00-05	Installed Xalan Java
13	2000-08-19 00:00:00-05	Installed Xerces Java
14	2000-08-22 00:00:00-05	Price model improved to provide one free month for one year advanced payment
15	2000-08-25 00:00:00-05	Over 1200 fonts installed in <code>/usr/X11R6/lib/X11/fonts/TrueType</code> for use in Java server side image processing
16	2000-09-01 00:00:00-05	Installed GNU RegExp
17	2000-09-04 00:00:00-05	Installed KavaChart
18	2000-09-07 00:00:00-05	Installed Jetspeed
19	2000-09-07 00:00:00-05	Installed Castor
20	2000-09-07 00:00:00-05	Installed FreeMarker
21	2000-09-07 00:00:00-05	Installed OpenXML
22	2000-09-07 00:00:00-05	Installed XMLRPC-Java
23	2000-09-07 00:00:00-05	Installed Web Macro
24	2000-09-07 00:00:00-05	Installed Apache-Turbine
25	2000-09-07 00:00:00-05	Installed Apache-Jyve
26	2000-09-07 00:00:00-05	Installed Village libraries
27	2000-09-07 00:00:00-05	Installed Java POP 3 API's
28	2000-09-07 00:00:00-05	HotSpot Java JIT supported in SDK 1.3
29	2000-09-07 00:00:00-05	Installed J2SE 1.3 and JDK 1.1.8, Level 2 and above can choose their Java VM to use, Level 1 uses J2SE 1.3
30	2000-09-08 00:00:00-05	FastCGI installed
31	2000-09-08 00:00:00-05	PHPMyAdmin is now a standard part of every site using MySQL
32	2000-09-14 00:00:00-05	Majordomo email lists now supported
35	2000-09-30 00:00:00-05	PostgreSQL installed as another database option
36	2000-09-30 00:00:00-05	Systems upgraded to RedHat 7.0
37	2000-09-30 00:00:00-05	Shared anonymous FTP directory moved to <code>/var/ftp/pub/</code>
38	2000-09-30 00:00:00-05	<code>cvs</code> installed
73	2001-01-02 00:00:00-06	Upgraded Xerces from version 1.1.3 to version 1.2.0 so Cocoon 1.8 works as expected.
40	2000-10-09 00:00:00-05	Unix talk installed for improved communication between shell accounts
41	2000-10-10 00:00:00-05	<code>gnupg</code> installed for free public key encryption (PKI)
42	2000-10-11 00:00:00-05	<code>mcrypt</code> installed for additional encryption capabilities
43	2000-10-12 00:00:00-05	Daily off-site, encrypted, incremental backup enabled
44	2000-10-15 00:00:00-05	C libraries updated so PostgreSQL properly parses float numbers
45	2000-10-16 00:00:00-05	Pine installed for reading email from a shell account
47	2000-10-19 00:00:00-05	This what's new page
48	2000-10-20 00:00:00-05	Added the capability to map multiple host/domain names into your existing web space.
49	2000-10-20 00:00:00-05	Receive 1 Free Month for Referrals
51	2000-10-21 20:02:48-05	Log files are now processed on a daily basis
52	2000-10-24 19:18:07-05	Upgraded the imap packages because we have received reports of slow IMAP server response.
53	2000-10-25 17:22:44-05	JDBC 2.0.1 API installed so the MM.MySQL JDBC driver may use JDBC 2.0 features
54	2000-10-26 10:10:39-05	Upgraded to the latest version of JDK 1.3
55	2000-10-26 10:45:35-05	Enabled Borland's javacomp JIT compiler to provide over twice the throughput of Sun's HotSpot JIT
56	2000-11-01 17:02:18-06	The Ozone ODBMS is installed, testing is still under way
57	2000-11-11 08:21:12-06	Trial version of Tomcat 3.2b6 installed due to bug in Tomcat 3.1 not supporting encodeURL(String) properly.
58	2000-11-12 14:19:02-06	FTP transfer logs are parsed daily and placed in http://mysite.com/analog/
59	2000-11-15 01:24:29-06	Installed FOP version 0.13.0 for compatibility with Cocoon 1.8
60	2000-11-17 12:18:12-06	At the request of our clients, the aspell package was installed
61	2000-11-21 19:52:01-06	With the help of user feedback, our XSP processing now works properly
62	2000-11-30 07:17:09-06	Added the <A class='@LINK_CLASS' href='https://secure.aoindustries.com/servlet/com.javaphilia.javatator.Main'>Javatator Database Tool</A> for clients to easily administer both MySQL and PostgreSQL.
1	2000-08-13 00:00:00-05	All machines rebooted once for kernel upgrade
2	2000-08-19 00:00:00-05	Installed Jakarta-Watchdog
3	2000-08-19 00:00:00-05	Installed Jakarta-Taglibs
4	2000-08-19 00:00:00-05	Installed Jakarta-Struts
5	2000-08-19 00:00:00-05	Installed Jakarta-Slide
63	2000-12-13 18:09:57-06	SSH is now enabled for our international clients.
64	2000-12-16 21:12:05-06	Jakarta ORO 2.0.1 installed
75	2001-01-25 10:32:56-06	Added the PoolMan classes for global use.
76	2001-01-29 19:28:43-06	Upgraded PHP to version 4.0.4pl1.
67	2000-12-16 21:25:10-06	Jakarta Regexp 1.2 installed
78	2001-02-05 11:21:19-06	Our new, customized kernel allows our users' private HTTP servers to directly handle requests on port 80.
79	2001-02-05 15:53:21-06	Jetspeed 1.3a1 installed
69	2000-12-16 22:03:08-06	Jakarta Servlet API 3.2 installed
65	2000-12-16 22:03:47-06	Jakarta Tomcat 3.2.1 installed
70	2000-12-16 23:21:20-06	Added <A class='@LINK_CLASS' href='../docs/'>Full Documentation</A> for the software packages we support
71	2000-12-17 13:15:49-06	We now support the InterBase database.
72	2000-12-29 05:21:04-06	Although we do not yet officially support it, one of our clients is now using Cocoon 2 on our systems.
97	2001-05-24 16:43:56-05	Installed the servlets.com COS package version 21May2001
100	2001-06-18 23:27:50-05	In preparation for support EJB using JBoss, we have installed Jakarta Tomcat 3.2.2.
101	2001-06-19 10:54:26-05	We are pleased to announce that we now support EJB using JBoss for our Level 2 and above clients.
89	2001-05-17 00:38:27-05	A significant upgrade to our version of the Apache web server, along with a new configuration and process model, allow us to now offer both mod_jk support and wildcard HTTPS certificates for every site.  All old sites have been retrofitted with a HTTPS server.  All new sites come standard with HTTPS support.  As an example, users of www1.kc access the HTTPS server using <code>https://<I>sitename</I>.c1.aoindustries.com/</code>, where <code><i>sitename</i></code> is the same as your directory under <code>/www</code>.  Users on other machines replace the <code>c1</code> with the number of your server.
102	2001-06-19 18:33:52-05	JDK 1.3.1 is available for increased JVM reliability.
166	2004-09-18 01:08:28.420387-05	Installed the latest security patches to PHP 4.0.6.  Installed PHP 4.3.8.  Installed PHP 5.0.1.  PHP version 5.0.1 is now the default version of PHP for new websites.  For security reasons, all users of PHP 4.2.3 or PHP 4.3.3 are strongly encouraged to <A href="@URL(com.aoindustries.website.clientarea.FAQ?category=php&page=version)" class="@LINK_CLASS">Upgrade to PHP version 4.3.8 or 5.0.1.
168	2004-09-23 01:47:11.398668-05	In order to reduce the number of viruses being received by our customers, incoming emails are filtered by attachment extensions.  By default, the most common virus-carrying extensions are not allowed.  We will soon expand our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.email.Inboxes)'>Email Inbox Control Panel</A> and <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.webmail.WebMail)'>WebMail Interface</A> to support the configuration of these new filters.\r\n
170	2004-11-29 00:30:18.108642-06	The URLs for the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.HomePage)'>AO Industries Web Site</A> have been simplified through the use of servlet mappings.
157	2003-11-05 21:55:24.676578-06	We now accept American Express cards for both one-time payments and automatic payments.  To provide the card numbers, please call us at (866) 270-6195 or use our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.company.Contact)'>Contact Us Form</A>, making sure to select the "Encrypt Message" option.\r\n
167	2004-07-25 00:00:00-05	We have completed the upgrades to <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.daemon.operatingsystems.Mandrake)'>Mandrake 9.2</A>.  All servers now run this newer version of Linux and have the latest security updates installed.
171	2004-11-29 00:33:58.910373-06	The <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.HomePage)'>AO Industries Web Site</A> now uses form-based authentication instead of browser authentication.  This allow you to logout of the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.ControlIndex)'>Control Panels</A> and other tools without closing your browser.\r\n
173	2004-12-09 01:20:16.684298-06	We now offer <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.services.dedicated.DedicatedIndex)'>Dedicated Servers</A> starting $100/month.
172	2004-11-29 00:38:07.110479-06	Our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.reseller.ResellerIndex)'>Resellers</A> may now <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.admin.SwitchUsers)'>Switch Users</A> to their sub-accounts in order to see things from the sub-accounts point of view, including all data filters and security checks.
174	2004-12-10 23:09:15.330565-06	Fixed a bug in our ProFTP configuration where some FTP accounts were not properly restricted to their home directories.
177	2005-04-03 14:25:12.693993-05	Upgraded our MySQL installation to MySQL-Max to support InnoDB and transactions.
175	2005-02-22 14:54:08.526453-06	We have now implemented <A class='@LINK_CLASS' href='http://spamassassin.apache.org/index.html'>SpamAssassin</A> on all of our servers.  We have also modified our IMAP server to automatically train the Bayesian filters for SpamAssassin based on email use.  Please see our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.FAQ?category=email&page=antispam)'>Anti-Spam FAQ</A> for more details.\r\n
176	2005-02-22 15:35:22.406872-06	Our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.webmail.WebMail)'>WebMail</A> interface now supports nested IMAP folders and is more tightly integrated with our new SpamAssassin installation.\r\n
179	2005-06-01 14:47:30.899039-05	We have completed our new <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.reseller.PackageBuilder)'>Reseller Package Builder</A>.  This new tool allows our resellers to define custom packages.  Once approved by AO Industries, the package definitions may be used for new accounts.\r\n
178	2005-05-19 08:08:55.825718-05	As part of our operating system upgrades, we are now running SpamAssassin 3.  SpamAssassin 3 will help us keep up with the latest efforts of bulk mailers.<BR>\r\n<BR>\r\nWe have also greatly improved the performance of the IMAP server when training the SpamAssassin Bayesian filters.  Previously the IMAP server would directly call <code>sa-learn</code>, the SpamAssassin Bayesian filter training tool, and only complete its task when the <code>sa-learn</code> process completed.  Now the IMAP server places a copy of the relevant messsages into a temporary directory, and another processes trains SpamAssassin in the background.  As far as a user can distinguish, our modified IMAP server is now as fast as an unmodified server.<BR>\r\n<BR>\r\nWhen an email inbox has its SpamAssassin integration mode set to "POP3", any emails considered to be junk by SpamAssassin will now have "*****SPAM*****" prepended to the subject lines.<BR>\r\n<BR>\r\nThe <code>required_score</code> may now be set on a per-inbox basis in either our <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.email.Inboxes)'>Email Inbox Control Panel</A> or <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.webmail.WebMail)'>WebMail Interface</A>.  Our default value of 3.0 is fairly aggressive.  Individuals who want less chance of valid emails being flagged as junk may raise this value to 5.0 or 10.0.\r\n
180	2005-06-01 15:51:15.455741-05	We have added indexing within the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.performance.Caches)'>AOServ Client Distributed Caches</A> to improve the performance of many API calls.\r\n
181	2005-06-01 15:54:53.469451-05	We have reduced the number of cache invalidation signals being sent from the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.master.AOServMasterIndex)'>AOServ Master</A> to the <A class='@LINK_CLASS' href='@URL(com.aoindustries.website.aoserv.components.client.AOServClientIndex)'>AOServ Clients</A>.  Previously, certain API calls would result in all connected clients being notified of the update.  This would result in all servers verifying their configurations concurrently, causing a short-term, high load on the master server.\r\n
183	2005-12-13 23:00:26.193823-06	We have improved our firewall rules in three significant ways:\r\n<OL>\r\n    <LI>All services must be registered with AO Industries and opened on our firewall prior to clients being able to connect.  Previously, any service on ports above 1024 were allowed unless blocked.  We have switched to a block-unless-allowed policy for all ports.</LI>\r\n    <LI>All servers now route their packets through our firewalls, even when on the same network.  Previously all servers on the same physical network had unfiltered access to other servers on the same physical network, where each physical network is comprised of servers of the same type (virtual, dedicated, managed, colocation, ...).  Now, each server is isolated from one another by the firewalls just like they are isolated from other networks.  This has somewhat reduced the efficiency of inter-server communication, but we believe the loss of efficiency is well worth the added security.</LI>\r\n    <LI>We have restricted all outbound UDP traffic from all of our networks.  If you need to provide of access any UDP service please <a class='@LINK_CLASS' href='@URL(com.aoindustries.website.company.Contact)'>contact us</a> with the specific list of IP addresses and ports you will need to allow access to or from.</LI>\r\n</OL>\r\n
182	2005-12-04 12:01:00-06	We are happy to announce the installation and support of AWStats, Java 5, and\r\nTomcat 5.5.<br>\r\n<br>\r\nAWStats:\r\n<ul>\r\n    Many of you have noticed that we turned off Analog reporting a couple of\r\n    months ago on some servers due to Analog causing high load averages.  We\r\n    have now integrated AWStats into our Control Panels.  We have parsed all\r\n    log files back about one year.  You may see your reports in our HTTP\r\n    Servers Control Panel, or at this URL:<br>\r\n<br>\r\n    <a class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.httpd.AWStats)'>@URL(com.aoindustries.website.clientarea.control.httpd.AWStats)</A>\r\n</ul>\r\nJava 5:\r\n<ul>\r\n    Java 5 may be used for any existing site by udpating your profile script to\r\n    include /usr/aoserv/etc/jdk1.5.0.sh  See this FAQ for more details on how\r\n    to change Java versions:<br>\r\n<br>\r\n    <a class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.FAQ?category=jvms&page=profile)'>@URL(com.aoindustries.website.clientarea.FAQ?category=jvms&page=profile)</A>\r\n</ul>\r\nTomcat 5.5:\r\n<ul>\r\n    New sites may now be created running Tomcat 5.5.  We cannot upgrade existing\r\n    sites automatically.  So in the case of an upgrade please create a new\r\n    installation (<a class='@LINK_CLASS' href='@URL(com.aoindustries.website.clientarea.control.httpd.HttpdSiteCP)'>Web Sites Control Panel</a>), install your content, test, and\r\n    then switch the DNS settings to the new IP address.\r\n</ul>
\.
SELECT setval ('"whats_new_pkey_seq"', 183, true);
