#!/bin/bash
DIR=`dirname "$0"`
DB_NAME="$1"
if [ "$DB_NAME" = "" ]
then
	echo "usage: $0 {aoweb|aoindustries|aoserv_backup}" 2>&1
	exit 1
fi
grep -h -i "create table" ${DIR}/${DB_NAME}/*.sql | cut -c14- | cut -d\  -f1 | while read TABLE_NAME
do
	echo "drop table ${TABLE_NAME} cascade;"
done
grep -h -i "create sequence" ${DIR}/${DB_NAME}/*.sql | cut -c17- | cut -d\  -f1 | while read SEQUENCE_NAME
do
	echo "drop sequence ${SEQUENCE_NAME};"
done
