#!/bin/bash
DIR=`dirname "$0"`
DB_NAME="$1"
if [ "$DB_NAME" = "" ]
then
	echo "usage: $0 {aoweb|aoindustries/public}" 2>&1
	exit 1
fi

for FILE in "${DIR}/${DB_NAME}"/*-create.sql
do
	echo "\\echo ${FILE}"
	cat "${FILE}"
done
