#!/bin/bash
DIR="${BASH_SOURCE%/*}"
echo "BEGIN;"
# 5
cat "${DIR}/aoindustries/schema/ForeignKey-data5-pre.sql"
	# 4
	cat "${DIR}/aoindustries/schema/Column-data4-pre.sql"
	cat "${DIR}/aoindustries/aosh/Command-data4-pre.sql"
		# 3
		cat "${DIR}/aoindustries/schema/Table-data3-pre.sql"
			# 2
			cat "${DIR}/aoindustries/schema/Type-data2-pre.sql"
			cat "${DIR}/aoindustries/schema/Schema-data2-pre.sql"
				# 1
				cat "${DIR}/aoindustries/schema/AOServProtocol-data1-pre.sql"
				cat "${DIR}/aoindustries/schema/AOServProtocol-data1.sql"
				cat "${DIR}/aoindustries/schema/AOServProtocol-data1-post.sql"
			# 2
			cat "${DIR}/aoindustries/schema/Schema-data2.sql"
			cat "${DIR}/aoindustries/schema/Schema-data2-post.sql"
			cat "${DIR}/aoindustries/schema/Type-data2.sql"
			cat "${DIR}/aoindustries/schema/Type-data2-post.sql"
		# 3
		cat "${DIR}/aoindustries/schema/Table-data3.sql"
		cat "${DIR}/aoindustries/schema/Table-data3-post.sql"
	# 4
	cat "${DIR}/aoindustries/aosh/Command-data4.sql"
	cat "${DIR}/aoindustries/aosh/Command-data4-post.sql"
	for SQL in "${DIR}/aoindustries"/*/*-schema.Column.sql
	do
	  echo "\echo $SQL"
	  cat "$SQL"
	done
	cat "${DIR}/aoindustries/schema/Column-data4.sql"
	cat "${DIR}/aoindustries/schema/Column-data4-post.sql"
# 5
cat "${DIR}/aoindustries/schema/ForeignKey-data5.sql"
cat "${DIR}/aoindustries/schema/ForeignKey-data5-post.sql"
echo "COMMIT;"
