#!/bin/bash
#
# Converts data from AOServ 1.0 database to AOServ 2.0
#
DIR=`dirname "$0"`
(
  # Clear database
  "${DIR}/generate_sql-drop" "aoindustries"
) | /ao/bin/ssh aoadmin@192.168.1.129 "psql -p 5433 aoindustries" 2>&1 | grep -i error | grep -v " does not exist$"
read -p "Please confirm public schema is empty (\d) then press <Enter>: "
(
  # Create database objects
  "${DIR}/generate_sql-create" "aoindustries"

  # Convert data
cat <<EOF
  insert into ao_server_daemon_hosts select * from aoserv1.ao_server_daemon_hosts;
  select setval('ao_server_daemon_hosts_pkey_seq', (select coalesce(max(pkey)+1, 1) from ao_server_daemon_hosts), false);
  insert into ao_server_resources select
    lsg.pkey + 4000000,
    case
      when lg.type in ('user') then 'shell_group'
      when lg.type in ('system') then 'system_group'
      else 'Unknown group type: ' || lg.type
    end,
    pk.accounting,
    lsg.ao_server
  from
    aoserv1.linux_server_groups lsg
    inner join aoserv1.linux_groups lg on lsg.name=lg.name
    inner join aoserv1.packages pk on lg.package=pk.name
  ;
  insert into ao_server_resources select
    lsa.pkey + 5000000,
    case
      when la.type in ('application', 'user') then 'shell_account'
      when la.type in ('email') then 'email_inbox'
      when la.type in ('ftponly') then 'ftponly_account'
      when la.type in ('system') then 'system_account'
      else 'Unknown account type: ' || la.type
    end,
    pk.accounting,
    lsa.ao_server
  from
    aoserv1.linux_server_accounts lsa
    inner join aoserv1.linux_accounts la on lsa.username=la.username
    inner join aoserv1.usernames un on la.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into ao_server_resources select
    cr.pkey + 6000000,
    'cvs_repository',
    pk.accounting,
    lsa.ao_server
  from
    aoserv1.cvs_repositories cr
    inner join aoserv1.linux_server_accounts lsa on cr.linux_server_account=lsa.pkey
    inner join aoserv1.linux_accounts la on lsa.username=la.username
    inner join aoserv1.usernames un on la.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into ao_server_resources select
    pfs.net_bind + 7000000,
    'private_ftp_server',
    pk.accounting,
    lsa.ao_server
  from
    aoserv1.private_ftp_servers pfs
    inner join aoserv1.linux_server_accounts lsa on pfs.linux_server_account=lsa.pkey
    inner join aoserv1.usernames un on lsa.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into ao_server_resources select
    ms.pkey + 8000000,
    'mysql_server',
    pk.accounting,
    ms.ao_server
  from
    aoserv1.mysql_servers ms
    inner join aoserv1.packages pk on ms.package=pk.name
  ;
  insert into ao_server_resources select
    md.pkey + 9000000,
    'mysql_database',
    pk.accounting,
    ms.ao_server
  from
    aoserv1.mysql_databases md
    inner join aoserv1.packages pk on md.package=pk.name
    inner join aoserv1.mysql_servers ms on md.mysql_server=ms.pkey
  ;
  insert into ao_server_resources select
    msu.pkey + 10000000,
    'mysql_user',
    pk.accounting,
    ms.ao_server
  from
    aoserv1.mysql_server_users msu
    inner join aoserv1.usernames un on msu.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
    inner join aoserv1.mysql_servers ms on msu.mysql_server=ms.pkey
  ;
  insert into ao_server_resources select
    ps.pkey + 11000000,
    'postgresql_server',
    pk.accounting,
    ps.ao_server
  from
    aoserv1.postgres_servers ps
    inner join aoserv1.net_binds nb on ps.net_bind=nb.pkey
    inner join aoserv1.packages pk on nb.package=pk.name
  ;
  insert into ao_server_resources select
    pd.pkey + 12000000,
    'postgresql_database',
    pk.accounting,
    ps.ao_server
  from
    aoserv1.postgres_databases pd
    inner join aoserv1.postgres_server_users psu on pd.datdba=psu.pkey
    inner join aoserv1.usernames un on psu.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
    inner join aoserv1.postgres_servers ps on pd.postgres_server=ps.pkey
  ;
  insert into ao_server_resources select
    psu.pkey + 13000000,
    'postgresql_user',
    pk.accounting,
    ps.ao_server
  from
    aoserv1.postgres_server_users psu
    inner join aoserv1.usernames un on psu.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
    inner join aoserv1.postgres_servers ps on psu.postgres_server=ps.pkey
  ;
  insert into ao_server_resources select
    hs.pkey + 14000000,
    'httpd_server',
    pk.accounting,
    hs.ao_server
  from
    aoserv1.httpd_servers hs
    inner join aoserv1.packages pk on hs.package=pk.pkey
  ;
  insert into ao_server_resources select
    hs.pkey + 15000000,
    'httpd_jboss_site',
    pk.accounting,
    hs.ao_server
  from
    aoserv1.httpd_jboss_sites hjs
    inner join aoserv1.httpd_sites hs on hjs.tomcat_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
  ;
  insert into ao_server_resources select
    hs.pkey + 15000000,
    'httpd_static_site',
    pk.accounting,
    hs.ao_server
  from
    aoserv1.httpd_static_sites hss
    inner join aoserv1.httpd_sites hs on hss.httpd_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
  ;
  insert into ao_server_resources select
    hs.pkey + 15000000,
    'httpd_tomcat_std_site',
    pk.accounting,
    hs.ao_server
  from
    aoserv1.httpd_tomcat_std_sites htss
    inner join aoserv1.httpd_sites hs on htss.tomcat_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
  ;
  insert into ao_server_resources select
    hs.pkey + 15000000,
    'httpd_tomcat_shared_site',
    pk.accounting,
    hs.ao_server
  from
    aoserv1.httpd_tomcat_shared_sites htss
    inner join aoserv1.httpd_sites hs on htss.tomcat_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
  ;

  select setval('resources_pkey_seq', 19000001, false);
  insert into resources select
    nextval('resources_pkey_seq'),
    'server_farm',
    pk.accounting,
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.server_farms sf
    inner join aoserv1.packages pk on sf.owner=pk.pkey
  order by
    sf.name
  ;

  select setval('resources_pkey_seq', 19000001, false);
  insert into server_farms select
    nextval('resources_pkey_seq'),
    'server_farm',
    sf.name,
    sf.description,
    sf.use_restricted_smtp_port
  from
    aoserv1.server_farms sf
  order by
    sf.name
  ;

  insert into resources select
    se.pkey,
    'backup_server',
    pk.accounting,

    now(),
    'orion',
    null,
    now()
  from
    aoserv1.servers se
    inner join aoserv1.packages pk on se.package=pk.pkey
  where
    se.pkey not in (select server from aoserv1.physical_servers) and se.pkey not in (select server from aoserv1.virtual_servers)
  ;
  insert into resources select
    ps.server,
    'physical_server',
    pk.accounting,
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.physical_servers ps
    inner join aoserv1.servers se on ps.server=se.pkey
    inner join aoserv1.packages pk on se.package=pk.pkey
  ;
  insert into resources select
    vs.server,
    'virtual_server',
    pk.accounting,
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.virtual_servers vs
    inner join aoserv1.servers se on vs.server=se.pkey
    inner join aoserv1.packages pk on se.package=pk.pkey
  ;

  insert into servers select
    se.pkey,
    case
        when (select count(*) from aoserv1.physical_servers ps where se.pkey=ps.server)>0 then 'physical_server'
        when (select count(*) from aoserv1.virtual_servers vs where se.pkey=vs.server)>0 then 'virtual_server'
        else 'backup_server'
    end,
    pk.accounting,
    (select sf.resource from server_farms sf where sf.name=se.farm),
    se.description,
    se.operating_system_version,
    se.name,
    se.monitoring_enabled
  from
    aoserv1.servers se
    inner join aoserv1.packages pk on se.package=pk.pkey
  ;

  insert into ao_servers select * from aoserv1.ao_servers;
EOF
  cat "${DIR}/aoindustries/aoserv_permissions-data1.sql"
  cat "${DIR}/aoindustries/aoserv_role_permissions-data1.sql"
  cat "${DIR}/aoindustries/aoserv_roles-data1.sql"
  cat "${DIR}/aoindustries/architectures-data1.sql"
cat <<EOF
  insert into backup_servers select
    se.pkey,
    'backup_server'
  from
    aoserv1.servers se
  where
    se.pkey not in (select server from aoserv1.physical_servers) and se.pkey not in (select server from aoserv1.virtual_servers)
  ;
  insert into backup_partitions select pkey, ao_server, path, quota_enabled from aoserv1.backup_partitions;
  select setval('backup_partitions_pkey_seq', (select coalesce(max(pkey)+1, 1) from backup_partitions), false);
EOF
  cat "${DIR}/aoindustries/backup_retentions-data1.sql"
  echo "insert into bank_accounts select * from aoserv1.bank_accounts;"
  cat "${DIR}/aoindustries/bank_transaction_types-data1.sql"
cat <<EOF
  insert into bank_transactions select * from aoserv1.bank_transactions;
  select setval('bank_transactions_transid_seq', (select coalesce(max(transid)+1, 1) from bank_transactions), false);
  insert into banks select * from aoserv1.banks;
  insert into brands select
    br.accounting,
    br.nameserver1,
    br.nameserver2,
    br.nameserver3,
    br.nameserver4,
    br.smtp_linux_server_account + 5000000,
    br.smtp_host,
    br.smtp_password,
    br.imap_linux_server_account + 5000000,
    br.imap_host,
    br.imap_password,
    br.support_email_address,
    br.support_email_display,
    br.signup_email_address,
    br.signup_email_display,
    br.ticket_encryption_from,
    br.ticket_encryption_recipient,
    br.signup_encryption_from,
    br.signup_encryption_recipient,
    br.support_toll_free,
    br.support_day_phone,
    br.support_emergency_phone1,
    br.support_emergency_phone2,
    br.support_fax,
    br.support_mailing_address1,
    br.support_mailing_address2,
    br.support_mailing_address3,
    br.support_mailing_address4,
    br.english_enabled,
    br.japanese_enabled,
    br.aoweb_struts_http_url_base,
    br.aoweb_struts_https_url_base,
    br.aoweb_struts_google_verify_content,
    br.aoweb_struts_noindex,
    br.aoweb_struts_google_analytics_new_tracking_code,
    br.aoweb_struts_signup_admin_address,
    br.aoweb_struts_vnc_bind,
    br.aoweb_struts_keystore_type,
    br.aoweb_struts_keystore_password
  from aoserv1.brands br;
  select setval('business_administrator_roles_pkey_seq', 1, false);
  insert into business_administrator_roles select
    nextval('business_administrator_roles_pkey_seq'),
    username,
    case
      -- Read-Only
      when username in (
        'root'
      ) then 1
      -- Master User
      when username in (
        'aoserv',
        'assassyn',
        'biscuit',
        'bugnugger',
        'chris24',
        'jasondavies',
        'kaori',
        'oldaodeacon',
        'orion'
      ) then 2
      -- AOServ Daemon
      when username in (
        'ao1_kc_svr',
        'aq_svr',
        'backup42_ineedmybackup_com',
        'backup73_svr',
        'centos5_svr',
        'dais_svr',
        'db2_fc_softwaremiracles_com_svr',
        'dlserver_svr',
        'guggenheim_svr',
        'gw1_fc_svr',
        'gw1_mob_svr',
        'gw2_fc_svr',
        'keepandshare_svr',
        'masterdb_keepandshare_svr',
        'master_svr',
        'mob_kc_svr',
        'ns1_svr',
        'ns2_svr',
        'ns3_svr',
        'ns4_svr',
        'pertinence_svr',
        'slavedb1_svr',
        'suspendo_svr',
        'swimconn_svr',
        'w1_fc_insightsys_svr',
        'www1_fc_enduraquest_svr',
        'www1_fc_lnxhosting_ca_svr',
        'www1_fc_nmw_svr',
        'www1_fc_oe_svr',
        'www1_fc_softwaremiracles',
        'www1_foliolizer_svr',
        'www1_kc_svr',
        'www1_leagle_svr',
        'www1_limlom_svr',
        'www1_pca_svr',
        'www2_fc_nmw_svr',
        'www2_fc_softwaremiracles',
        'www2_kc_svr',
        'www3_kc_svr',
        'www4_kc_svr',
        'www5_kc_svr',
        'www6_kc_svr',
        'www7_kc_svr',
        'www8_kc_svr',
        'www9_fc_svr',
        'xen1_mob_svr',
        'xen2_mob_svr',
        'xen907_1_svr',
        'xen907_2_svr',
        'xen907_3_svr',
        'xen907_4_svr',
        'xen907_5_svr',
        'xen914_1_svr',
        'xen914_2_svr',
        'xen914_4_svr',
        'xen914_5_svr',
        'xen917_1_svr',
        'xen917_2_svr',
        'xen917_3_svr',
        'xen917_4_svr',
        'xen917_5_svr',
        'xen_917_6_svr'
      ) then 3
      -- AOWeb Struts
      when username in (
        'aointernet_web_app',
        'aoweb_app',
        'cloudhosting_web_app',
        'cloudservers_web_app',
        'cmsguys_web_app',
        'commerceguys_web_app',
        'drupalguys_web_app',
        'forumguys_web_app',
        'glassfishhosting_web_app',
        'grailshosting_web_app',
        'groupwareguys_web_app',
        'hostingguys',
        'hostingguys_web_app',
        'j2eehosting_web_app',
        'javaee5hosting_web_app',
        'javaguys_web_app',
        'jbosshosting_web_app',
        'joomlaguys_web_app',
        'jspguys_web_app',
        'mamboguys_web_app',
        'mediawikiguys_web_app',
        'mysqlguys_web_app',
        'nmwcontrolpanel_web_app',
        'oscommerceguys_web_app',
        'pharmacyhosting_web_app',
        'phpbbguys_web_app',
        'phpgroupwarehosting_web_app',
        'phpguys_web_app',
        'postgishosting_web_app',
        'postgresqlhost_web_app',
        'pythonguys_web_app',
        'railshost_web_app',
        'rubyguys_web_app',
        'smfguys_web_app',
        'tikiwikihosting_web_app',
        'tomcatguys_web_app',
        'virtuemarthosting_web_app',
        'wikiguys_web_app',
        'xenguys_web_app',
        'xoopshosting_web_app'
      ) then 4
      -- AWStats Proxy
      when username in (
        'build_awstats',
        'edrugstore_awstats',
        'edrugtest_awstats',
        'leagleaw'
      ) then 6
      -- Business Administrator
      else 5
    end
  from aoserv1.business_administrators;
  insert into business_administrators select
    ba.username,
    pk.accounting,
    ba.password,
    ba.name,
    ba.title,
    ba.birthday,
    ba.is_preferred,
    ba.private,
    ba.created,
    ba.work_phone,
    ba.home_phone,
    ba.cell_phone,
    ba.fax,
    ba.email,
    ba.address1,
    ba.address2,
    ba.city,
    ba.state,
    ba.country,
    ba.zip,
    ba.disable_log,
    ba.can_switch_users,
    ba.support_code
  from
    aoserv1.business_administrators ba
    inner join aoserv1.usernames un on ba.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into business_profiles select * from aoserv1.business_profiles;
  select setval('business_profiles_pkey_seq', (select coalesce(max(pkey)+1, 1) from business_profiles), false);
  insert into business_servers select pkey, accounting, server, is_default, can_vnc_console from aoserv1.business_servers;
  select setval('business_servers_pkey_seq', (select coalesce(max(pkey)+1, 1) from business_servers), false);
  insert into businesses select
    bu.accounting,
    bu.contract_version,
    bu.created,
    bu.canceled,
    bu.cancel_reason,
    bu.parent,
    bu.can_add_backup_server,
    bu.can_add_businesses,
    bu.can_see_prices,
    bu.disable_log,
    bu.do_not_disable_reason,
    bu.auto_enable,
    bu.bill_parent,
    pk.package_definition,
    case when bu.accounting='AOINDUSTRIES' then null else pk.created_by end,
    pk.email_in_burst,
    pk.email_in_rate,
    pk.email_out_burst,
    pk.email_out_rate,
    pk.email_relay_burst,
    pk.email_relay_rate
  from
    aoserv1.businesses bu
    inner join aoserv1.packages pk on bu.accounting=pk.accounting
  ;
  insert into country_codes select * from aoserv1.country_codes;
  insert into credit_card_processors select * from aoserv1.credit_card_processors;
  insert into credit_card_transactions select * from aoserv1.credit_card_transactions;
  select setval('credit_card_transactions_pkey_seq', (select coalesce(max(pkey)+1, 1) from credit_card_transactions), false);
  insert into credit_cards select * from aoserv1.credit_cards;
  select setval('credit_cards_pkey_seq', (select coalesce(max(pkey)+1, 1) from credit_cards), false);
EOF
  cat "${DIR}/aoindustries/currencies-data1.sql"
cat <<EOF
  insert into disable_log select * from aoserv1.disable_log;
  select setval('disable_log_pkey_seq', (select coalesce(max(pkey)+1, 1) from disable_log), false);
  insert into distro_files select * from aoserv1.distro_files;
  select setval('distro_files_pkey_seq', (select coalesce(max(pkey)+1, 1) from distro_files), false);
EOF
  cat "${DIR}/aoindustries/distro_file_types-data1.sql"
cat <<EOF
  select setval('resources_pkey_seq', 17000001, false);
  insert into dns_zones select
    nextval('resources_pkey_seq'),
    'dns_zone',
    pk.accounting,
    dz.zone,
    dz.file,
    dz.hostmaster,
    dz.serial,
    dz.ttl
  from
    aoserv1.dns_zones dz
    inner join aoserv1.packages pk on dz.package=pk.name
  order by
    dz.zone
  ;
  update dns_zones set zone=substring(zone from 1 for length(zone)-1) where zone like '%.';
  update dns_zones set hostmaster=substring(hostmaster from 1 for length(hostmaster)-1) where hostmaster like '%.';
  insert into dns_tlds select domain from aoserv1.dns_tlds;
EOF
  cat "${DIR}/aoindustries/dns_types-data1.sql"
cat <<EOF
  insert into email_addresses select pkey, address, domain+3000000 from aoserv1.email_addresses;
  select setval('email_addresses_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_addresses), false);
  insert into email_attachment_blocks select
    eab.pkey,
    eab.linux_server_account + 5000000,
    eab.extension
  from
    aoserv1.email_attachment_blocks eab
    inner join aoserv1.linux_server_accounts lsa on eab.linux_server_account=lsa.pkey
    inner join aoserv1.linux_accounts la on lsa.username=la.username
  where
    la.type in ('application', 'user', 'email')
  ;
  select setval('email_attachment_blocks_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_attachment_blocks), false);
  insert into email_attachment_types select extension, is_default_block from aoserv1.email_attachment_types;
  insert into email_domains select
    ed.pkey+3000000,
    ed.domain,
    ed.ao_server,
    pk.accounting
  from
    aoserv1.email_domains ed
    inner join aoserv1.packages pk on ed.package=pk.name
  ;
  select setval('email_domains_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_domains), false);
  insert into email_forwarding select * from aoserv1.email_forwarding;
  select setval('email_forwarding_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_forwarding), false);
  insert into email_inbox_addresses select
    laa.pkey,
    laa.email_address,
    laa.linux_server_account + 5000000
  from
    aoserv1.linux_acc_addresses laa
  ;
  select setval('email_inbox_addresses_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_inbox_addresses), false);
  insert into email_inboxes select
    lsa.pkey + 5000000,
    case
      when la.type in ('application', 'user') then 'shell_account'
      when la.type in ('email') then 'email_inbox'
      else 'Unknown account type: ' || la.type
    end,
    lsa.autoresponder_from,
    lsa.autoresponder_subject,
    lsa.autoresponder_path,
    lsa.is_autoresponder_enabled,
    lsa.use_inbox,
    lsa.trash_email_retention,
    lsa.junk_email_retention,
    lsa.sa_integration_mode,
    lsa.sa_required_score,
    lsa.sa_discard_score
  from
    aoserv1.linux_server_accounts lsa
    inner join aoserv1.linux_accounts la on lsa.username=la.username
  where
    la.type in ('application', 'user', 'email')
  ;
  insert into email_list_addresses select * from aoserv1.email_list_addresses;
  select setval('email_list_addresses_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_list_addresses), false);
  insert into email_lists select pkey, path, linux_server_account + 5000000, linux_server_group + 4000000, disable_log from aoserv1.email_lists;
  select setval('email_lists_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_lists), false);
  insert into email_pipe_addresses select * from aoserv1.email_pipe_addresses;
  select setval('email_pipe_addresses_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_pipe_addresses), false);
  insert into email_pipes select * from aoserv1.email_pipes;
  select setval('email_pipes_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_pipes), false);
EOF
  cat "${DIR}/aoindustries/email_sa_integration_modes-data1.sql"
  cat "${DIR}/aoindustries/email_smtp_relay_types-data1.sql"
cat <<EOF
  insert into email_smtp_relays select * from aoserv1.email_smtp_relays;
  select setval('email_smtp_relays_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_smtp_relays), false);
  insert into email_smtp_smart_host_domains select * from aoserv1.email_smtp_smart_host_domains;
  select setval('email_smtp_smart_host_domains_pkey_seq', (select coalesce(max(pkey)+1, 1) from email_smtp_smart_host_domains), false);
  insert into email_smtp_smart_hosts select * from aoserv1.email_smtp_smart_hosts;
  insert into encryption_keys select * from aoserv1.encryption_keys;
  select setval('encryption_keys_pkey_seq', (select coalesce(max(pkey)+1, 1) from encryption_keys), false);
  insert into expense_categories select * from aoserv1.expense_categories;
  insert into failover_file_log select
    pkey,
    replication,
    start_time,
    case when end_time<start_time then start_time else end_time end,
    scanned,
    updated,
    bytes,
    is_successful
  from
    aoserv1.failover_file_log
  ;
  select setval('failover_file_log_pkey_seq', (select coalesce(max(pkey)+1, 1) from failover_file_log), false);
  insert into failover_file_replications select * from aoserv1.failover_file_replications;
  select setval('failover_file_replications_pkey_seq', (select coalesce(max(pkey)+1, 1) from failover_file_replications), false);
  insert into failover_file_schedule select * from aoserv1.failover_file_schedule;
  select setval('failover_file_schedule_pkey_seq', (select coalesce(max(pkey)+1, 1) from failover_file_schedule), false);
  insert into failover_mysql_replications select
    pkey,
    ao_server,
    replication,
    mysql_server + 8000000,
    monitoring_seconds_behind_low,
    monitoring_seconds_behind_medium,
    monitoring_seconds_behind_high,
    monitoring_seconds_behind_critical
  from
    aoserv1.failover_mysql_replications
  ;
  select setval('failover_mysql_replications_pkey_seq', (select coalesce(max(pkey)+1, 1) from failover_mysql_replications), false);
  insert into file_backup_settings select * from aoserv1.file_backup_settings;
  select setval('file_backup_settings_pkey_seq', (select coalesce(max(pkey)+1, 1) from file_backup_settings), false);
  insert into ftp_guest_users select
    lsa.pkey + 5000000,
    'ftponly_account'
  from
    aoserv1.ftp_guest_users fgu
    inner join aoserv1.linux_server_accounts lsa on fgu.username=lsa.username
  ;
  insert into group_names select distinct
    lsg.name,
    pk.accounting,
    null::integer
  from
    aoserv1.linux_server_groups lsg
    inner join aoserv1.linux_groups lg on lsg.name=lg.name
    inner join aoserv1.packages pk on lg.package=pk.name
  ;
  insert into httpd_binds select net_bind, httpd_server + 14000000 from aoserv1.httpd_binds;
  insert into httpd_jboss_sites select
    tomcat_site + 15000000,
    version,
    jnp_bind,
    webserver_bind,
    rmi_bind,
    hypersonic_bind,
    jmx_bind
  from
    aoserv1.httpd_jboss_sites
  ;
  insert into httpd_jboss_versions select * from aoserv1.httpd_jboss_versions;
  insert into httpd_jk_codes select * from aoserv1.httpd_jk_codes;
  insert into httpd_jk_protocols select * from aoserv1.httpd_jk_protocols;
  insert into httpd_shared_tomcats select
    pkey,
    name,
    ao_server,
    version,
    linux_server_account + 5000000,
    linux_server_group + 4000000,
    disable_log,
    tomcat4_worker,
    tomcat4_shutdown_port,
    tomcat4_shutdown_key,
    is_manual
  from
    aoserv1.httpd_shared_tomcats
  ;
  select setval('httpd_shared_tomcats_pkey_seq', (select coalesce(max(pkey)+1, 1) from httpd_shared_tomcats), false);
  insert into httpd_site_authenticated_locations select
    pkey,
    httpd_site + 15000000,
    path,
    is_regular_expression,
    auth_name,
    auth_group_file,
    auth_user_file,
    require
  from
    aoserv1.httpd_site_authenticated_locations
  ;
  select setval('httpd_site_authenticated_locations_pkey_seq', (select coalesce(max(pkey)+1, 1) from httpd_site_authenticated_locations), false);
  insert into httpd_site_binds select
    pkey,
    httpd_site + 15000000,
    httpd_bind,
    access_log,
    error_log,
    ssl_cert_file,
    ssl_cert_key_file,
    disable_log,
    predisable_config,
    is_manual,
    redirect_to_primary_hostname
  from
    aoserv1.httpd_site_binds
  ;
  select setval('httpd_site_binds_pkey_seq', (select coalesce(max(pkey)+1, 1) from httpd_site_binds), false);
  insert into httpd_site_urls select * from aoserv1.httpd_site_urls;
  select setval('httpd_site_urls_pkey_seq', (select coalesce(max(pkey)+1, 1) from httpd_site_urls), false);
  insert into httpd_static_sites select httpd_site + 15000000 from aoserv1.httpd_static_sites;
  insert into httpd_tomcat_contexts select
    pkey,
    tomcat_site + 15000000,
    class_name,
    cookies,
    cross_context,
    doc_base,
    override,
    path,
    privileged,
    reloadable,
    use_naming,
    wrapper_class,
    debug,
    work_dir
  from
    aoserv1.httpd_tomcat_contexts
  ;
  select setval('httpd_tomcat_contexts_pkey_seq', (select coalesce(max(pkey)+1, 1) from httpd_tomcat_contexts), false);
  insert into httpd_tomcat_data_sources select * from aoserv1.httpd_tomcat_data_sources;
  select setval('httpd_tomcat_data_sources_pkey_seq', (select coalesce(max(pkey)+1, 1) from httpd_tomcat_data_sources), false);
  insert into httpd_tomcat_parameters select * from aoserv1.httpd_tomcat_parameters;
  select setval('httpd_tomcat_parameters_pkey_seq', (select coalesce(max(pkey)+1, 1) from httpd_tomcat_parameters), false);
  insert into httpd_tomcat_shared_sites select
    tomcat_site + 15000000,
    httpd_shared_tomcat
  from
    aoserv1.httpd_tomcat_shared_sites
  ;
  insert into httpd_tomcat_sites select
    httpd_site + 15000000,
    version,
    use_apache
  from
    aoserv1.httpd_tomcat_sites
  ;
  insert into httpd_tomcat_std_sites select
    tomcat_site + 15000000,
    tomcat4_shutdown_port,
    tomcat4_shutdown_key
  from
    aoserv1.httpd_tomcat_std_sites
  ;
  insert into httpd_tomcat_versions select * from aoserv1.httpd_tomcat_versions;
  insert into httpd_workers select
    pkey,
    code,
    net_bind,
    tomcat_site + 15000000
  from
    aoserv1.httpd_workers
  ;
  select setval('httpd_workers_pkey_seq', (select coalesce(max(pkey)+1, 1) from httpd_workers), false);
  insert into ip_addresses select
    ia.pkey+2000000,
    'ip_address',
    case when
      ia.net_device is null
    then
      (select server from aoserv1.ao_servers where hostname='master.aoindustries.com')
    else
      (select nd.server from aoserv1.net_devices nd where nd.pkey=ia.net_device)
    end,
    ia.ip_address,
    ia.net_device,
    ia.is_alias,
    ia.hostname,
    ia.available,
    ia.is_overflow,
    ia.is_dhcp,
    ia.ping_monitor_enabled,
    ia.external_ip_address,
    case
      when ia.netmask='255.0.0.0' then 8::smallint
      when ia.netmask='255.255.255.0' then 24::smallint
      when ia.netmask='255.255.255.128' then 25::smallint
      when ia.netmask='255.255.255.192' then 26::smallint
      when ia.netmask='255.255.255.248' then 29::smallint
      else ('Unknown netmask: ' || ia.netmask)::smallint
    end
  from
    aoserv1.ip_addresses ia
    inner join aoserv1.packages pk on ia.package=pk.name
  where
    ia.ip_address!='0.0.0.0'
  ;
  insert into dns_records select
    dr.pkey+1000000,
    'dns_record',
    pk.accounting,
    (select dz2.resource from dns_zones dz2 where dr.zone=dz2.zone),
    dr.domain,
    dr.type,
    dr.mx_priority,
    case when dr.type='A' then dr.destination else null end,
    case
      when dr.type in ('CNAME', 'MX', 'NS', 'PTR')
      then
        case when dr.destination like '%.'
          then substring(dr.destination from 1 for length(dr.destination)-1)
          else dr.destination||'.'||substring(dz.zone from 1 for length(dz.zone)-1)
        end
      else null
    end,
    case when dr.type in ('TXT', 'SPF') then dr.destination else null end,
    dr.dhcp_address,
    dr.ttl
  from
    aoserv1.dns_records dr
    inner join aoserv1.dns_zones dz on dr.zone=dz.zone
    inner join aoserv1.packages pk on dz.package=pk.name
  ;
EOF
  cat "${DIR}/aoindustries/languages-data1.sql"
cat <<EOF
  select setval('linux_account_groups_pkey_seq', 1, false);
  insert into linux_account_groups select
    nextval('linux_account_groups_pkey_seq'),
    lsa.pkey + 5000000,
    case
      when la.type in ('application', 'user') then 'shell_account'
      when la.type in ('email') then 'email_inbox'
      when la.type in ('ftponly') then 'ftponly_account'
      when la.type in ('system') then 'system_account'
      else 'Unknown account type: ' || la.type
    end,
    lsa.ao_server,
    lsg.pkey + 4000000,
    case
      when lg.type in ('user') then 'shell_group'
      when lg.type in ('system') then 'system_group'
      else 'Unknown group type: ' || lg.type
    end,
    lg.name,
    lga.is_primary
  from
    aoserv1.linux_group_accounts lga
    inner join aoserv1.linux_accounts la on lga.username=la.username
    inner join aoserv1.linux_server_accounts lsa on la.username=lsa.username
    inner join aoserv1.linux_groups lg on lga.group_name=lg.name
    inner join aoserv1.linux_server_groups lsg on lg.name=lsg.name
  where
    lsa.ao_server=lsg.ao_server
  ;
  insert into cvs_repositories select
    cr.pkey + 6000000,
    'cvs_repository',
    lsa.ao_server,
    cr.path,
    lag.pkey,
    lag.linux_account_type,
    cr.mode
  from
    aoserv1.cvs_repositories cr
    inner join aoserv1.linux_server_accounts lsa on cr.linux_server_account=lsa.pkey
    left outer join linux_account_groups lag on
      cr.linux_server_account + 5000000 = lag.linux_account
      and cr.linux_server_group + 4000000 = lag.linux_group
      and lsa.ao_server = lag.ao_server
  ;
  insert into httpd_servers select
    hs.pkey + 14000000,
    'httpd_server',
    hs.ao_server,
    hs.number,
    hs.max_binds,
    lag.pkey,
    hs.mod_php_version,
    hs.use_suexec,
    hs.is_shared,
    hs.use_mod_perl,
    hs.timeout
  from
    aoserv1.httpd_servers hs
    inner join aoserv1.packages pk on hs.package=pk.pkey
    left outer join linux_account_groups lag on
      hs.linux_server_account + 5000000 = lag.linux_account
      and hs.linux_server_group + 4000000 = lag.linux_group
      and hs.ao_server = lag.ao_server
  ;
  insert into httpd_sites select
    hs.pkey + 15000000,
    'httpd_jboss_site',
    pk.accounting,
    hs.ao_server,
    hs.site_name,
    hs.list_first,
    lag.pkey,
    lag.linux_account_type,
    hs.server_admin,
    hs.is_manual,
    hs.awstats_skip_files
  from
    aoserv1.httpd_jboss_sites hjs
    inner join aoserv1.httpd_sites hs on hjs.tomcat_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
    left outer join aoserv1.linux_server_accounts lsa on hs.linux_account=lsa.username and hs.ao_server=lsa.ao_server
    left outer join aoserv1.linux_server_groups lsg on hs.linux_group=lsg.name and hs.ao_server=lsg.ao_server
    left outer join linux_account_groups lag on
      lsa.pkey + 5000000 = lag.linux_account
      and lsg.pkey + 4000000 = lag.linux_group
      and hs.ao_server = lag.ao_server
  ;
  insert into httpd_sites select
    hs.pkey + 15000000,
    'httpd_static_site',
    pk.accounting,
    hs.ao_server,
    hs.site_name,
    hs.list_first,
    lag.pkey,
    lag.linux_account_type,
    hs.server_admin,
    hs.is_manual,
    hs.awstats_skip_files
  from
    aoserv1.httpd_static_sites hss
    inner join aoserv1.httpd_sites hs on hss.httpd_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
    left outer join aoserv1.linux_server_accounts lsa on hs.linux_account=lsa.username and hs.ao_server=lsa.ao_server
    left outer join aoserv1.linux_server_groups lsg on hs.linux_group=lsg.name and hs.ao_server=lsg.ao_server
    left outer join linux_account_groups lag on
      lsa.pkey + 5000000 = lag.linux_account
      and lsg.pkey + 4000000 = lag.linux_group
      and hs.ao_server = lag.ao_server
  ;
  insert into httpd_sites select
    hs.pkey + 15000000,
    'httpd_tomcat_std_site',
    pk.accounting,
    hs.ao_server,
    hs.site_name,
    hs.list_first,
    lag.pkey,
    lag.linux_account_type,
    hs.server_admin,
    hs.is_manual,
    hs.awstats_skip_files
  from
    aoserv1.httpd_tomcat_std_sites htss
    inner join aoserv1.httpd_sites hs on htss.tomcat_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
    left outer join aoserv1.linux_server_accounts lsa on hs.linux_account=lsa.username and hs.ao_server=lsa.ao_server
    left outer join aoserv1.linux_server_groups lsg on hs.linux_group=lsg.name and hs.ao_server=lsg.ao_server
    left outer join linux_account_groups lag on
      lsa.pkey + 5000000 = lag.linux_account
      and lsg.pkey + 4000000 = lag.linux_group
      and hs.ao_server = lag.ao_server
  ;
  insert into httpd_sites select
    hs.pkey + 15000000,
    'httpd_tomcat_shared_site',
    pk.accounting,
    hs.ao_server,
    hs.site_name,
    hs.list_first,
    lag.pkey,
    lag.linux_account_type,
    hs.server_admin,
    hs.is_manual,
    hs.awstats_skip_files
  from
    aoserv1.httpd_tomcat_shared_sites htss
    inner join aoserv1.httpd_sites hs on htss.tomcat_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
    left outer join aoserv1.linux_server_accounts lsa on hs.linux_account=lsa.username and hs.ao_server=lsa.ao_server
    left outer join aoserv1.linux_server_groups lsg on hs.linux_group=lsg.name and hs.ao_server=lsg.ao_server
    left outer join linux_account_groups lag on
      lsa.pkey + 5000000 = lag.linux_account
      and lsg.pkey + 4000000 = lag.linux_group
      and hs.ao_server = lag.ao_server
  ;
EOF
  cat "${DIR}/aoindustries/linux_account_types-data1.sql"
cat <<EOF
  insert into linux_accounts select
    lsa.pkey + 5000000,
    case
      when la.type in ('application', 'user') then 'shell_account'
      when la.type in ('email') then 'email_inbox'
      when la.type in ('ftponly') then 'ftponly_account'
      when la.type in ('system') then 'system_account'
      else 'Unknown account type: ' || la.type
    end,
    pk.accounting,
    lsa.ao_server,
    lsa.username,
    lsa.uid,
    lsa.home,
    la.name,
    case when la.office_location is null or length(la.office_location)=0 then null else la.office_location end,
    case when la.office_phone is null or length(la.office_phone)=0 then null else la.office_phone end,
    case when la.home_phone is null or length(la.home_phone)=0 then null else la.home_phone end,
    la.shell,
    lsa.predisable_password
  from
    aoserv1.linux_server_accounts lsa
    inner join aoserv1.linux_accounts la on lsa.username=la.username
    inner join aoserv1.usernames un on la.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
EOF
  cat "${DIR}/aoindustries/linux_group_types-data1.sql"
cat <<EOF
  insert into linux_groups select
    lsg.pkey + 4000000,
    case
      when lg.type in ('user') then 'shell_group'
      when lg.type in ('system') then 'system_group'
      else 'Unknown group type: ' || lg.type
    end,
    pk.accounting,
    lsg.ao_server,
    lsg.name,
    lsg.gid
  from
    aoserv1.linux_server_groups lsg
    inner join aoserv1.linux_groups lg on lsg.name=lg.name
    inner join aoserv1.packages pk on lg.package=pk.name
  ;
  insert into majordomo_lists select
    email_list,
    majordomo_server + 3000000,
    name,
    listname_pipe_add,
    listname_list_add,
    owner_listname_add,
    listname_owner_add,
    listname_approval_add,
    listname_request_pipe_add
  from
    aoserv1.majordomo_lists
  ;
  insert into majordomo_servers select
    domain + 3000000,
    linux_server_account + 5000000,
    linux_server_group + 4000000,
    version,
    majordomo_pipe_address,
    owner_majordomo_add,
    majordomo_owner_add
  from
    aoserv1.majordomo_servers
  ;
  insert into majordomo_versions select * from aoserv1.majordomo_versions;
  insert into master_hosts select * from aoserv1.master_hosts;
  select setval('master_hosts_pkey_seq', (select coalesce(max(pkey)+1, 1) from master_hosts), false);
  insert into master_servers select * from aoserv1.master_servers;
  select setval('master_servers_pkey_seq', (select coalesce(max(pkey)+1, 1) from master_servers), false);
  insert into master_users select * from aoserv1.master_users;
  insert into monthly_charges select * from aoserv1.monthly_charges;
  select setval('monthly_charges_pkey_seq', (select coalesce(max(pkey)+1, 1) from monthly_charges), false);
  insert into mysql_databases select
    md.pkey + 9000000,
    'mysql_database',
    ms.ao_server,
    md.name,
    md.mysql_server + 8000000
  from
    aoserv1.mysql_databases md
    inner join aoserv1.packages pk on md.package=pk.name
    inner join aoserv1.mysql_servers ms on md.mysql_server=ms.pkey
  ;
  insert into mysql_db_users select
    mdu.pkey,
    msu.mysql_server + 8000000,
    mdu.mysql_database + 9000000,
    mdu.mysql_server_user + 10000000,
    mdu.select_priv,
    mdu.insert_priv,
    mdu.update_priv,
    mdu.delete_priv,
    mdu.create_priv,
    mdu.drop_priv,
    mdu.grant_priv,
    mdu.references_priv,
    mdu.index_priv,
    mdu.alter_priv,
    mdu.create_tmp_table_priv,
    mdu.lock_tables_priv,
    mdu.create_view_priv,
    mdu.show_view_priv,
    mdu.create_routine_priv,
    mdu.alter_routine_priv,
    mdu.execute_priv,
    mdu.event_priv,
    mdu.trigger_priv
  from
    aoserv1.mysql_db_users mdu
    inner join aoserv1.mysql_server_users msu on mdu.mysql_server_user=msu.pkey
  ;
  select setval('mysql_db_users_pkey_seq', (select coalesce(max(pkey)+1, 1) from mysql_db_users), false);
  insert into mysql_servers select
    ms.pkey + 8000000,
    'mysql_server',
    pk.accounting,
    ms.ao_server,
    ms.name,
    ms.version,
    ms.max_connections,
    ms.net_bind
  from
    aoserv1.mysql_servers ms
    inner join aoserv1.packages pk on ms.package=pk.name
  ;
  insert into mysql_users select
    msu.pkey + 10000000,
    'mysql_user',
    pk.accounting,
    ms.ao_server,
    msu.username,
    msu.mysql_server + 8000000,
    msu.host,
    mu.select_priv,
    mu.insert_priv,
    mu.update_priv,
    mu.delete_priv,
    mu.create_priv,
    mu.drop_priv,
    mu.reload_priv,
    mu.shutdown_priv,
    mu.process_priv,
    mu.file_priv,
    mu.grant_priv,
    mu.references_priv,
    mu.index_priv,
    mu.alter_priv,
    mu.show_db_priv,
    mu.super_priv,
    mu.create_tmp_table_priv,
    mu.lock_tables_priv,
    mu.execute_priv,
    mu.repl_slave_priv,
    mu.repl_client_priv,
    mu.create_view_priv,
    mu.show_view_priv,
    mu.create_routine_priv,
    mu.alter_routine_priv,
    mu.create_user_priv,
    mu.event_priv,
    mu.trigger_priv,
    msu.predisable_password,
    msu.max_questions,
    msu.max_updates,
    msu.max_connections,
    msu.max_user_connections
  from
    aoserv1.mysql_server_users msu
    inner join aoserv1.mysql_users mu on msu.username=mu.username
    inner join aoserv1.usernames un on mu.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
    inner join aoserv1.mysql_servers ms on msu.mysql_server=ms.pkey
  ;
  insert into net_binds select
    nb.pkey,
    pk.accounting,
    nb.server,
    bs.pkey,
    case when ia.ip_address='0.0.0.0' then null else 2000000+nb.ip_address end,
    nb.port,
    nb.net_protocol,
    nb.app_protocol,
    nb.open_firewall,
    nb.monitoring_enabled,
    nb.monitoring_parameters
  from
    aoserv1.net_binds nb
    inner join aoserv1.ip_addresses ia on nb.ip_address=ia.pkey
    inner join aoserv1.packages pk on nb.package=pk.name
    inner join aoserv1.business_servers bs on pk.accounting=bs.accounting and nb.server=bs.server
  ;
  select setval('net_binds_pkey_seq', (select coalesce(max(pkey)+1, 1) from net_binds), false);
  insert into net_device_ids select * from aoserv1.net_device_ids;
  insert into net_devices select pkey, server, device_id, description, gateway, network, broadcast, mac_address, max_bit_rate, monitoring_bit_rate_low, monitoring_bit_rate_medium, monitoring_bit_rate_high, monitoring_bit_rate_critical from aoserv1.net_devices;
  select setval('net_devices_pkey_seq', (select coalesce(max(pkey)+1, 1) from net_devices), false);
  insert into net_protocols select * from aoserv1.net_protocols;
  insert into net_tcp_redirects select * from aoserv1.net_tcp_redirects;
  insert into notice_log select * from aoserv1.notice_log;
  select setval('notice_log_pkey_seq', (select coalesce(max(pkey)+1, 1) from notice_log), false);
EOF
  cat "${DIR}/aoindustries/notice_types-data1.sql"
  cat "${DIR}/aoindustries/operating_system_versions-data1.sql"
  cat "${DIR}/aoindustries/operating_systems-data1.sql"
cat <<EOF
  insert into package_categories select * from aoserv1.package_categories;
  select setval('package_definition_businesses_pkey_seq', 1, false);
  insert into package_definition_businesses select
    nextval('package_definition_businesses_pkey_seq'),
    pkey,
    accounting,
    display,
    description,
    active,
    approved
  from
    aoserv1.package_definitions
  ;
  insert into package_definition_limits select
    pkey,
    package_definition,
    case
      when resource='httpd' then 'httpd_server'
      when resource='ip' then 'ip_address'
      when resource='user' then 'shell_account'
      when resource='email' then 'email_inbox'
      else resource
    end,
    soft_limit,
    hard_limit,
    additional_rate,
    additional_transaction_type
  from
    aoserv1.package_definition_limits
  where
    resource!='site'
  ;
  select setval('package_definition_limits_pkey_seq', (select coalesce(max(pkey)+1, 1) from package_definition_limits), false);
  insert into package_definitions select
    pkey,
    category,
    case when accounting='AOINDUSTRIES' then name else accounting||'_'||name end,
    version,
    'USD',
    setup_fee,
    setup_fee_transaction_type,
    monthly_rate,
    monthly_rate_transaction_type,
    approved
  from aoserv1.package_definitions;
  select setval('package_definitions_pkey_seq', (select coalesce(max(pkey)+1, 1) from package_definitions), false);
EOF
  cat "${DIR}/aoindustries/payment_types-data1.sql"
cat <<EOF
  insert into postgres_databases select
    pd.pkey + 12000000,
    'postgresql_database',
    pk.accounting,
    ps.ao_server,
    pd.name,
    pd.postgres_server + 11000000,
    pd.datdba + 13000000,
    pd.encoding,
    pd.is_template,
    pd.allow_conn,
    pd.enable_postgis
  from
    aoserv1.postgres_databases pd
    inner join aoserv1.postgres_server_users psu on pd.datdba=psu.pkey
    inner join aoserv1.usernames un on psu.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
    inner join aoserv1.postgres_servers ps on pd.postgres_server=ps.pkey
  ;
EOF
  cat "${DIR}/aoindustries/postgres_encodings-data1.sql"
cat <<EOF
  insert into postgres_servers select
    ps.pkey + 11000000,
    'postgresql_server',
    pk.accounting,
    ps.ao_server,
    ps.name,
    ps.version,
    ps.max_connections,
    ps.net_bind,
    ps.sort_mem,
    ps.shared_buffers,
    ps.fsync
  from
    aoserv1.postgres_servers ps
    inner join aoserv1.net_binds nb on ps.net_bind=nb.pkey
    inner join aoserv1.packages pk on nb.package=pk.name
  ;
  insert into postgres_users select
    psu.pkey + 13000000,
    'postgresql_user',
    pk.accounting,
    ps.ao_server,
    psu.username,
    psu.postgres_server + 11000000,
    pu.createdb,
    pu.trace,
    pu.super,
    pu.catupd,
    psu.predisable_password
  from
    aoserv1.postgres_server_users psu
    inner join aoserv1.postgres_users pu on psu.username=pu.username
    inner join aoserv1.usernames un on pu.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
    inner join aoserv1.postgres_servers ps on psu.postgres_server=ps.pkey
  ;
  insert into postgres_versions select * from aoserv1.postgres_versions;
  insert into private_ftp_servers select
    pfs.net_bind + 7000000,
    'private_ftp_server',
    pk.accounting,
    lsa.ao_server,
    pfs.net_bind,
    pfs.logfile,
    pfs.hostname,
    pfs.email,
    lag.pkey,
    lag.linux_account_type,
    pfs.allow_anonymous
  from
    aoserv1.private_ftp_servers pfs
    inner join aoserv1.linux_server_accounts lsa on pfs.linux_server_account=lsa.pkey
    inner join aoserv1.usernames un on lsa.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
    left outer join linux_account_groups lag on lsa.pkey + 5000000 = lag.linux_account and lsa.ao_server=lag.ao_server and lag.is_primary
  ;
  insert into processor_types select * from aoserv1.processor_types;
  insert into protocols select * from aoserv1.protocols;
  insert into resellers select * from aoserv1.resellers;
EOF
  cat "${DIR}/aoindustries/resource_types-data1.sql"
cat <<EOF
  select setval('resources_pkey_seq', 17000001, false);
  insert into resources select
    nextval('resources_pkey_seq'),
    'dns_zone',
    pk.accounting,
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.dns_zones dz
    inner join aoserv1.packages pk on dz.package=pk.name
  order by
    dz.zone
  ;
  insert into resources select
    dr.pkey+1000000,
    'dns_record',
    pk.accounting,
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.dns_records dr
    inner join aoserv1.dns_zones dz on dr.zone=dz.zone
    inner join aoserv1.packages pk on dz.package=pk.name
  ;
  insert into resources select
    ia.pkey+2000000,
    'ip_address',
    pk.accounting,
    ia.created,
    'orion',
    null,
    ia.created
  from
    aoserv1.ip_addresses ia
    inner join aoserv1.packages pk on ia.package=pk.name
  where
    ia.ip_address!='0.0.0.0'
  ;
  insert into resources select
    lsg.pkey + 4000000,
    case
      when lg.type in ('user') then 'shell_group'
      when lg.type in ('system') then 'system_group'
      else 'Unknown group type: ' || lg.type
    end,
    pk.accounting,
    lsg.created,
    'orion',
    null,
    lsg.created
  from
    aoserv1.linux_server_groups lsg
    inner join aoserv1.linux_groups lg on lsg.name=lg.name
    inner join aoserv1.packages pk on lg.package=pk.name
  ;
  insert into resources select
    lsa.pkey + 5000000,
    case
      when la.type in ('application', 'user') then 'shell_account'
      when la.type in ('email') then 'email_inbox'
      when la.type in ('ftponly') then 'ftponly_account'
      when la.type in ('system') then 'system_account'
      else 'Unknown account type: ' || la.type
    end,
    pk.accounting,
    lsa.created,
    'orion',
    lsa.disable_log,
    lsa.created
  from
    aoserv1.linux_server_accounts lsa
    inner join aoserv1.linux_accounts la on lsa.username=la.username
    inner join aoserv1.usernames un on la.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into resources select
    cr.pkey + 6000000,
    'cvs_repository',
    pk.accounting,
    cr.created,
    'orion',
    cr.disable_log,
    cr.created
  from
    aoserv1.cvs_repositories cr
    inner join aoserv1.linux_server_accounts lsa on cr.linux_server_account=lsa.pkey
    inner join aoserv1.linux_accounts la on lsa.username=la.username
    inner join aoserv1.usernames un on la.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into resources select
    pfs.net_bind + 7000000,
    'private_ftp_server',
    pk.accounting,
    pfs.created,
    'orion',
    lsa.disable_log,
    pfs.created
  from
    aoserv1.private_ftp_servers pfs
    inner join aoserv1.linux_server_accounts lsa on pfs.linux_server_account=lsa.pkey
    inner join aoserv1.usernames un on lsa.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into resources select
    ms.pkey + 8000000,
    'mysql_server',
    pk.accounting,
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.mysql_servers ms
    inner join aoserv1.packages pk on ms.package=pk.name
  ;
  insert into resources select
    md.pkey + 9000000,
    'mysql_database',
    pk.accounting,
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.mysql_databases md
    inner join aoserv1.packages pk on md.package=pk.name
  ;
  insert into resources select
    msu.pkey + 10000000,
    'mysql_user',
    pk.accounting,
    now(),
    'orion',
    msu.disable_log,
    now()
  from
    aoserv1.mysql_server_users msu
    inner join aoserv1.usernames un on msu.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into resources select
    ps.pkey + 11000000,
    'postgresql_server',
    pk.accounting,
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.postgres_servers ps
    inner join aoserv1.net_binds nb on ps.net_bind=nb.pkey
    inner join aoserv1.packages pk on nb.package=pk.name
  ;
  insert into resources select
    pd.pkey + 12000000,
    'postgresql_database',
    pk.accounting,
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.postgres_databases pd
    inner join aoserv1.postgres_server_users psu on pd.datdba=psu.pkey
    inner join aoserv1.usernames un on psu.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into resources select
    psu.pkey + 13000000,
    'postgresql_user',
    pk.accounting,
    now(),
    'orion',
    psu.disable_log,
    now()
  from
    aoserv1.postgres_server_users psu
    inner join aoserv1.usernames un on psu.username=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into resources select
    hs.pkey + 14000000,
    'httpd_server',
    pk.accounting,
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.httpd_servers hs
    inner join aoserv1.packages pk on hs.package=pk.pkey
  ;
  insert into resources select
    hs.pkey + 15000000,
    'httpd_jboss_site',
    pk.accounting,
    now(),
    'orion',
    hs.disable_log,
    now()
  from
    aoserv1.httpd_jboss_sites hjs
    inner join aoserv1.httpd_sites hs on hjs.tomcat_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
  ;
  insert into resources select
    hs.pkey + 15000000,
    'httpd_static_site',
    pk.accounting,
    now(),
    'orion',
    hs.disable_log,
    now()
  from
    aoserv1.httpd_static_sites hss
    inner join aoserv1.httpd_sites hs on hss.httpd_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
  ;
  insert into resources select
    hs.pkey + 15000000,
    'httpd_tomcat_std_site',
    pk.accounting,
    now(),
    'orion',
    hs.disable_log,
    now()
  from
    aoserv1.httpd_tomcat_std_sites htss
    inner join aoserv1.httpd_sites hs on htss.tomcat_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
  ;
  insert into resources select
    hs.pkey + 15000000,
    'httpd_tomcat_shared_site',
    pk.accounting,
    now(),
    'orion',
    hs.disable_log,
    now()
  from
    aoserv1.httpd_tomcat_shared_sites htss
    inner join aoserv1.httpd_sites hs on htss.tomcat_site=hs.pkey
    inner join aoserv1.packages pk on hs.package=pk.name
  ;

  insert into resources select
    pkey + 18000000,
    'rack',
    'AOINDUSTRIES',
    now(),
    'orion',
    null,
    now()
  from
    aoserv1.racks
  ;
  insert into racks select
    r.pkey + 18000000,
    'rack',
    sf.resource,
    r.name,
    r.max_power,
    r.total_rack_units
  from
    aoserv1.racks r
    inner join server_farms sf on r.farm=sf.name
  ;

  insert into server_resources select
    ia.pkey+2000000,
    'ip_address',
    pk.accounting,
    case when
      ia.net_device is null
    then
      (select server from aoserv1.ao_servers where hostname='master.aoindustries.com')
    else
      (select nd.server from aoserv1.net_devices nd where nd.pkey=ia.net_device)
    end
  from
    aoserv1.ip_addresses ia
    inner join aoserv1.packages pk on ia.package=pk.name
  where
    ia.ip_address!='0.0.0.0'
  ;
  insert into physical_servers select
    ps.server,
    'physical_server',
    se.farm,
    ps.rack + 18000000,
    r.farm,
    ps.rack_units,
    ps.ram,
    ps.processor_type,
    ps.processor_speed,
    ps.processor_cores,
    ps.max_power,
    ps.supports_hvm
  from
    aoserv1.physical_servers ps
    inner join servers se on ps.server=se.resource
    inner join racks r on (ps.rack + 18000000) = r.resource
  ;
EOF
  cat "${DIR}/aoindustries/shells-data1.sql"
cat <<EOF
  insert into signup_request_options select * from aoserv1.signup_request_options;
  select setval('signup_request_options_pkey_seq', (select coalesce(max(pkey)+1, 1) from signup_request_options), false);
  insert into signup_requests select * from aoserv1.signup_requests;
  select setval('signup_requests_pkey_seq', 1154, false);
  insert into spam_email_messages select * from aoserv1.spam_email_messages;
  select setval('spam_email_messages_pkey_seq', (select coalesce(max(pkey)+1, 1) from spam_email_messages), false);
  insert into system_email_aliases select * from aoserv1.system_email_aliases;
  select setval('system_email_aliases_pkey_seq', (select coalesce(max(pkey)+1, 1) from system_email_aliases), false);
  insert into technologies select * from aoserv1.technologies;
  select setval('technologies_pkey_seq', (select coalesce(max(pkey)+1, 1) from technologies), false);
  insert into technology_classes select name from aoserv1.technology_classes;
  insert into technology_names select name from aoserv1.technology_names;
  insert into technology_versions select * from aoserv1.technology_versions;
  select setval('technology_versions_pkey_seq', (select coalesce(max(pkey)+1, 1) from technology_versions), false);
EOF
  cat "${DIR}/aoindustries/ticket_action_types-data1.sql"
cat <<EOF
  insert into ticket_actions select * from aoserv1.ticket_actions;
  select setval('ticket_actions_pkey_seq', (select coalesce(max(pkey)+1, 1) from ticket_actions), false);
  insert into ticket_assignments select
    ta.pkey,
    ta.ticket,
    ta.reseller,
    ta.administrator,
    pk.accounting
  from
    aoserv1.ticket_assignments ta
    inner join aoserv1.usernames un on ta.administrator=un.username
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  select setval('ticket_assignments_pkey_seq', (select coalesce(max(pkey)+1, 1) from ticket_assignments), false);
  insert into ticket_brand_categories select * from aoserv1.ticket_brand_categories;
  insert into ticket_categories select * from aoserv1.ticket_categories;
EOF
  cat "${DIR}/aoindustries/ticket_priorities-data1.sql"
  cat "${DIR}/aoindustries/ticket_statuses-data1.sql"
  cat "${DIR}/aoindustries/ticket_types-data1.sql"
cat <<EOF
  insert into tickets select
    ti.pkey,
    ti.brand,
    ti.reseller,
    re.ticket_auto_escalate,
    ti.accounting,
    ti.language,
    case when ti.created_by is null then 'root' else ti.created_by end,
    ti.category,
    ti.ticket_type,
    ti.from_address,
    ti.summary,
    ti.details,
    ti.raw_email,
    ti.open_date,
    ti.client_priority,
    ti.admin_priority,
    ti.status,
    ti.status_timeout,
    ti.contact_emails,
    ti.contact_phone_numbers,
    ti.internal_notes
  from
    aoserv1.tickets ti
    inner join aoserv1.resellers re on ti.reseller=re.accounting
  ;
  insert into time_zones select * from aoserv1.time_zones;
  insert into transaction_types select * from aoserv1.transaction_types;
  insert into transactions select
    transid,
    time,
    accounting,
    source_accounting,
    username,
    type,
    description,
    quantity,
    'USD',
    rate,
    payment_type,
    payment_info,
    processor,
    credit_card_transaction,
    payment_confirmed
  from
    aoserv1.transactions
  ;
  select setval('transactions_transid_seq', (select coalesce(max(transid)+1, 1) from transactions), false);
  insert into us_states select * from aoserv1.us_states;
  insert into usernames select
    un.username,
    pk.accounting,
    un.disable_log
  from
    aoserv1.usernames un
    inner join aoserv1.packages pk on un.package=pk.name
  ;
  insert into virtual_disks select * from aoserv1.virtual_disks;
  select setval('virtual_disks_pkey_seq', (select coalesce(max(pkey)+1, 1) from virtual_disks), false);
  insert into virtual_servers select
    vs.server,
    'virtual_server',
    vs.primary_ram,
    vs.primary_ram_target,
    vs.secondary_ram,
    vs.secondary_ram_target,
    vs.minimum_processor_type,
    vs.minimum_processor_architecture,
    vs.minimum_processor_speed,
    vs.minimum_processor_speed_target,
    vs.processor_cores,
    vs.processor_cores_target,
    vs.processor_weight,
    vs.processor_weight_target,
    vs.primary_physical_server_locked,
    vs.secondary_physical_server_locked,
    vs.requires_hvm,
    vs.vnc_password
  from
    aoserv1.virtual_servers vs
    inner join aoserv1.servers se on vs.server=se.pkey
    inner join aoserv1.packages pk on se.package=pk.pkey
  ;
  insert into whois_history select * from aoserv1.whois_history;
  select setval('whois_history_pkey_seq', (select coalesce(max(pkey)+1, 1) from whois_history), false);
  -- TODO: pack resources_pkey_seq at the end of this process - ordered by created time?
EOF
  # Complete database objects
  "${DIR}/generate_sql-view" "aoindustries"
  "${DIR}/generate_sql-index" "aoindustries"
  "${DIR}/generate_sql-vacuum" "aoindustries"
  "${DIR}/generate_sql-reference" "aoindustries"
) | /ao/bin/ssh aoadmin@192.168.1.129 "psql -p 5433 aoindustries" 2>&1 | grep -i error
