begin;
insert into ao_server_resources values(1,  'mysql_server',      'AOINDUSTRIES', 2);
insert into ao_server_resources values(2,  'mysql_server',      'AOINDUSTRIES', 2);
insert into ao_server_resources values(3,  'mysql_user',        'AOINDUSTRIES', 2);
insert into ao_server_resources values(4,  'mysql_user',        'AOINDUSTRIES', 2);
insert into ao_server_resources values(5,  'mysql_user',        'NMW',          2);
insert into ao_server_resources values(6,  'mysql_database',    'AOINDUSTRIES', 2);
insert into ao_server_resources values(7,  'mysql_database',    'AOINDUSTRIES', 2);
insert into ao_server_resources values(8,  'mysql_database',    'AOINDUSTRIES', 2);
insert into ao_server_resources values(9,  'mysql_database',    'NMW',          2);
insert into ao_server_resources values(10, 'postgresql_server', 'AOINDUSTRIES', 2);
insert into ao_server_resources values(11, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(12, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(13, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(14, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(15, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(16, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(17, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(18, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(19, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(20, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(21, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(22, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(23, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(24, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(25, 'postgresql_user',   'AOINDUSTRIES', 2);
insert into ao_server_resources values(26, 'postgresql_user',   'AOINDUSTRIES', 2);
commit;
