begin;
insert into architectures values('alpha', 64);
insert into architectures values('amd64', 64);
insert into architectures values('hppa', 64);
insert into architectures values('i286', 16);
insert into architectures values('i386', 32);
insert into architectures values('i486', 32);
insert into architectures values('i586', 32);
insert into architectures values('i686', 32);
insert into architectures values('m68k', 32);
insert into architectures values('mips32', 32);
insert into architectures values('mips64', 64);
insert into architectures values('ppc', 64);
insert into architectures values('sparc', 32);
insert into architectures values('sparc64', 64);
insert into architectures values('x86_64', 64);
commit;
