begin;
insert into dns_types values('A');
insert into dns_types values('AAAA');
insert into dns_types values('CNAME');
insert into dns_types values('MX');
insert into dns_types values('NS');
insert into dns_types values('PTR');
insert into dns_types values('SPF');
insert into dns_types values('TXT');
commit;
