insert into httpd_tomcat_versions values(1941, '/usr/apache/jakarta/tomcat/3.1', false);
insert into httpd_tomcat_versions values(1944, '/usr/apache/jakarta/tomcat/3.2', false);
insert into httpd_tomcat_versions values(2525, '/usr/apache/jakarta/tomcat/4.1', true);
insert into httpd_tomcat_versions values(2583, '/usr/apache/jakarta/tomcat/5.5', true);
insert into httpd_tomcat_versions values(3232, '/usr/apache/jakarta/tomcat/3.1', false);
insert into httpd_tomcat_versions values(3233, '/usr/apache/jakarta/tomcat/3.2', false);
insert into httpd_tomcat_versions values(3234, '/usr/apache/jakarta/tomcat/4.1', true);
insert into httpd_tomcat_versions values(3235, '/usr/apache/jakarta/tomcat/5.5', true);
insert into httpd_tomcat_versions values(3228, '/opt/apache-tomcat-5.5', true);
