COPY "linux_groups" FROM stdin;
news	AOINDUSTRIES	application
root	AOINDUSTRIES	system
bin	AOINDUSTRIES	system
daemon	AOINDUSTRIES	system
sys	AOINDUSTRIES	system
adm	AOINDUSTRIES	system
tty	AOINDUSTRIES	system
disk	AOINDUSTRIES	system
lp	AOINDUSTRIES	system
mem	AOINDUSTRIES	system
kmem	AOINDUSTRIES	system
wheel	AOINDUSTRIES	system
mailonly	AOINDUSTRIES	system
uucp	AOINDUSTRIES	system
man	AOINDUSTRIES	application
floppy	AOINDUSTRIES	system
games	AOINDUSTRIES	application
slocate	AOINDUSTRIES	application
utmp	AOINDUSTRIES	system
pvm	AOINDUSTRIES	application
named	AOINDUSTRIES	application
postgres	AOINDUSTRIES	application
interbase	AOINDUSTRIES	application
nscd	AOINDUSTRIES	application
rpc	AOINDUSTRIES	system
xfs	AOINDUSTRIES	application
dip	AOINDUSTRIES	system
mailnull	AOINDUSTRIES	application
ftp	AOINDUSTRIES	application
httpd	AOINDUSTRIES	application
xvfb	AOINDUSTRIES	application
nobody	AOINDUSTRIES	system
users	AOINDUSTRIES	system
console	AOINDUSTRIES	system
pppusers	AOINDUSTRIES	system
popusers	AOINDUSTRIES	system
slipusers	AOINDUSTRIES	system
mysql	AOINDUSTRIES	application
cdrom	AOINDUSTRIES	system
usb	AOINDUSTRIES	system
sshd	AOINDUSTRIES	application
cdwriter	AOINDUSTRIES	system
audio	AOINDUSTRIES	system
video	AOINDUSTRIES	system
ftponly	AOINDUSTRIES	ftponly
xgrp	AOINDUSTRIES	application
aoadmin	AOINDUSTRIES	user
ntools	AOINDUSTRIES	application
ctools	AOINDUSTRIES	application
nogroup	AOINDUSTRIES	system
lock	AOINDUSTRIES	system
rpm	AOINDUSTRIES	system
ident	AOINDUSTRIES	system
ntp	AOINDUSTRIES	system
ftpmon	AOINDUSTRIES	ftponly
smmsp	AOINDUSTRIES	application
qmail	AOINDUSTRIES	application
nofiles	AOINDUSTRIES	application
mail	AOINDUSTRIES	system
vcsa	AOINDUSTRIES	system
portmon	AOINDUSTRIES	application
replicator	AOINDUSTRIES	application
proftpd_jailed	AOINDUSTRIES	system
tcpdump	AOINDUSTRIES	system
awstats	AOINDUSTRIES	application
\.
