COPY "linux_groups" FROM stdin;
news	AOINDUSTRIES	system
root	AOINDUSTRIES	system
bin	AOINDUSTRIES	system
daemon	AOINDUSTRIES	system
sys	AOINDUSTRIES	system
adm	AOINDUSTRIES	system
tty	AOINDUSTRIES	system
disk	AOINDUSTRIES	system
lp	AOINDUSTRIES	system
mem	AOINDUSTRIES	system
kmem	AOINDUSTRIES	system
wheel	AOINDUSTRIES	system
mailonly	AOINDUSTRIES	system
uucp	AOINDUSTRIES	system
man	AOINDUSTRIES	system
floppy	AOINDUSTRIES	system
games	AOINDUSTRIES	system
slocate	AOINDUSTRIES	system
utmp	AOINDUSTRIES	system
pvm	AOINDUSTRIES	system
named	AOINDUSTRIES	system
postgres	AOINDUSTRIES	system
interbase	AOINDUSTRIES	system
nscd	AOINDUSTRIES	system
rpc	AOINDUSTRIES	system
xfs	AOINDUSTRIES	system
mailnull	AOINDUSTRIES	system
ftp	AOINDUSTRIES	system
apache	AOINDUSTRIES	system
xvfb	AOINDUSTRIES	system
nobody	AOINDUSTRIES	system
users	AOINDUSTRIES	system
console	AOINDUSTRIES	system
pppusers	AOINDUSTRIES	system
popusers	AOINDUSTRIES	system
slipusers	AOINDUSTRIES	system
mysql	AOINDUSTRIES	system
sshd	AOINDUSTRIES	system
ftponly	AOINDUSTRIES	ftponly
aoadmin	AOINDUSTRIES	user
lock	AOINDUSTRIES	system
rpm	AOINDUSTRIES	system
ident	AOINDUSTRIES	system
ntp	AOINDUSTRIES	system
ftpmon	AOINDUSTRIES	ftponly
smmsp	AOINDUSTRIES	system
mail	AOINDUSTRIES	system
vcsa	AOINDUSTRIES	system
portmon	AOINDUSTRIES	system
replicator	AOINDUSTRIES	system
tcpdump	AOINDUSTRIES	system
awstats	AOINDUSTRIES	system
dip	AOINDUSTRIES	system
gopher	AOINDUSTRIES	system
haldaemon	AOINDUSTRIES	system
pcap	AOINDUSTRIES	system
dbus	AOINDUSTRIES	system
screen	AOINDUSTRIES	system
avahi	AOINDUSTRIES	system
saslauth	AOINDUSTRIES	system
distcache	AOINDUSTRIES	system
nfsnobody	AOINDUSTRIES	system
rpcuser	AOINDUSTRIES	system
utempter	AOINDUSTRIES	system
nginx	AOINDUSTRIES	system
memcached	AOINDUSTRIES	system
cdrom	AOINDUSTRIES	system
dialout	AOINDUSTRIES	system
tape	AOINDUSTRIES	system
video	AOINDUSTRIES	system
audio	AOINDUSTRIES	system
avahi-autoipd	AOINDUSTRIES	system
systemd-bus-proxy	AOINDUSTRIES	system
tcpdump	AOINDUSTRIES	system
chrony	AOINDUSTRIES	system
cgred	AOINDUSTRIES	system
aoserv-jilter	AOINDUSTRIES	system
aoserv-xen-migration	AOINDUSTRIES	system
mockbuild	AOINDUSTRIES	user
\.
