COPY linux_group_accounts (pkey, group_name, username, is_primary) FROM stdin;
1	root	root	t
2	avahi	avahi	t
3	bin	bin	t
4	daemon	daemon	t
5	adm	adm	t
6	lp	lp	t
7	root	sync	t
8	root	shutdown	t
9	root	halt	t
10	mail	mail	t
11	mail	cyrus	t
12	saslauth	cyrus	f
13	root	operator	t
14	users	games	t
16	ftp	ftp	t
17	nobody	nobody	t
18	mailnull	mailnull	t
19	rpc	rpc	t
20	dbus	dbus	t
21	xfs	xfs	t
22	mysql	mysql	t
23	ftpmon	ftpmon	t
24	gopher	gopher	t
25	mailonly	emailmon	t
26	news	news	t
27	aoadmin	aoadmin	t
28	named	named	t
29	nscd	nscd	t
30	postgres	postgres	t
31	ident	ident	t
32	pvm	pvm	t
33	bin	root	f
34	bin	daemon	f
35	daemon	root	f
36	daemon	bin	f
37	sys	root	f
38	sys	bin	f
39	sys	adm	f
40	adm	root	f
41	adm	daemon	f
42	disk	root	f
43	lp	daemon	f
44	wheel	root	f
45	interbase	interbase	t
46	apache	apache	t
47	haldaemon	haldaemon	t
48	xvfb	xvfb	t
49	uucp	uucp	t
50	pcap	pcap	t
51	distcache	distcache	t
52	nfsnobody	nfsnobody	t
53	rpcuser	rpcuser	t
54	sshd	sshd	t
55	smmsp	smmsp	t
56	rpm	rpm	t
57	ntp	ntp	t
58	vcsa	vcsa	t
59	awstats	awstats	t
\.
SELECT setval ('"linux_group_accounts_pkey_seq"', 60, true);
