begin;
insert into linux_accounts values(34, 'system_account',  'AOINDUSTRIES', 2, 'root',      0,     '/root',              'root',                              null, null, null, '/bin/bash',        null);
insert into linux_accounts values(35, 'system_account',  'AOINDUSTRIES', 2, 'adm',       3,     '/var/adm',           'adm',                               null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(36, 'system_account',  'AOINDUSTRIES', 2, 'apache',    48,    '/var/www',           'Apache',                            null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(37, 'system_account',  'AOINDUSTRIES', 2, 'avahi',     70,    '/',                  'Avahi daemon',                      null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(38, 'system_account',  'AOINDUSTRIES', 2, 'awstats',   78,    '/var/opt/awstats-6', 'AWStats Background Log Processing', null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(39, 'system_account',  'AOINDUSTRIES', 2, 'bin',       1,     '/bin',               'bin',                               null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(40, 'system_account',  'AOINDUSTRIES', 2, 'cyrus',     76,    '/var/lib/imap',      'Cyrus IMAP Server',                 null, null, null, '/bin/bash',        null);
insert into linux_accounts values(41, 'system_account',  'AOINDUSTRIES', 2, 'daemon',    2,     '/sbin',              'daemon',                            null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(42, 'system_account',  'AOINDUSTRIES', 2, 'dbus',      81,    '/',                  'System message bus',                null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(43, 'system_account',  'AOINDUSTRIES', 2, 'distcache', 94,    '/',                  'Distcache',                         null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(44, 'system_account',  'AOINDUSTRIES', 2, 'ftp',       14,    '/var/ftp',           'FTP User',                          null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(45, 'system_account',  'AOINDUSTRIES', 2, 'games',     12,    '/usr/games',         'games',                             null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(46, 'system_account',  'AOINDUSTRIES', 2, 'gopher',    13,    '/var/gopher',        'gopher',                            null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(47, 'system_account',  'AOINDUSTRIES', 2, 'haldaemon', 68,    '/',                  'HAL daemon',                        null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(48, 'system_account',  'AOINDUSTRIES', 2, 'halt',      7,     '/sbin',              'halt',                              null, null, null, '/sbin/halt',       null);
insert into linux_accounts values(49, 'system_account',  'AOINDUSTRIES', 2, 'interbase', 27,    '/opt/interbase',     'InterBase Server',                  null, null, null, '/bin/bash',        null);
insert into linux_accounts values(50, 'system_account',  'AOINDUSTRIES', 2, 'lp',        4,     '/var/spool/lpd',     'lp',                                null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(51, 'system_account',  'AOINDUSTRIES', 2, 'mail',      8,     '/var/spool/mail',    'mail',                              null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(52, 'system_account',  'AOINDUSTRIES', 2, 'mailnull',  47,    '/var/spool/mqueue',  'mailnull',                          null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(53, 'system_account',  'AOINDUSTRIES', 2, 'mysql',     31,    '/var/lib/mysql',     'MySQL Server',                      null, null, null, '/bin/bash',        null);
insert into linux_accounts values(54, 'system_account',  'AOINDUSTRIES', 2, 'named',     25,    '/var/named',         'Named',                             null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(55, 'system_account',  'AOINDUSTRIES', 2, 'news',      9,     '/etc/news',          'news',                              null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(56, 'system_account',  'AOINDUSTRIES', 2, 'nfsnobody', 65534, '/var/lib/nfs',       'Anonymous NFS User',                null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(57, 'system_account',  'AOINDUSTRIES', 2, 'nobody',    99,    '/',                  'Nobody',                            null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(58, 'system_account',  'AOINDUSTRIES', 2, 'ntp',       38,    '/etc/ntp',           'ntp',                               null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(59, 'system_account',  'AOINDUSTRIES', 2, 'operator',  11,    '/root',              'operator',                          null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(60, 'system_account',  'AOINDUSTRIES', 2, 'pcap',      77,    '/var/arpwatch',      'pcap',                              null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(61, 'system_account',  'AOINDUSTRIES', 2, 'postgres',  26,    '/var/lib/pgsql',     'PostgreSQL Server',                 null, null, null, '/bin/bash',        null);
insert into linux_accounts values(62, 'system_account',  'AOINDUSTRIES', 2, 'rpc',       32,    '/',                  'Portmapper RPC user',               null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(63, 'system_account',  'AOINDUSTRIES', 2, 'rpcuser',   29,    '/var/lib/nfs',       'RPC Service User',                  null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(64, 'system_account',  'AOINDUSTRIES', 2, 'rpm',       37,    '/var/lib/rpm',       'rpm',                               null, null, null, '/bin/bash',        null);
insert into linux_accounts values(65, 'system_account',  'AOINDUSTRIES', 2, 'shutdown',  6,     '/sbin',              'shutdown',                          null, null, null, '/sbin/shutdown',   null);
insert into linux_accounts values(66, 'system_account',  'AOINDUSTRIES', 2, 'smmsp',     51,    '/var/spool/mqueue',  'system user for sendmail',          null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(67, 'system_account',  'AOINDUSTRIES', 2, 'sshd',      74,    '/var/empty/sshd',    'system user for openssh',           null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(68, 'system_account',  'AOINDUSTRIES', 2, 'sync',      5,     '/sbin',              'sync',                              null, null, null, '/bin/sync',        null);
insert into linux_accounts values(69, 'system_account',  'AOINDUSTRIES', 2, 'uucp',      10,    '/var/spool/uucp',    'uucp',                              null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(70, 'system_account',  'AOINDUSTRIES', 2, 'vcsa',      69,    '/dev',               'virtual console memory owner',      null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(71, 'system_account',  'AOINDUSTRIES', 2, 'xfs',       43,    '/etc/X11/fs',        'X Font Server',                     null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(72, 'system_account',  'AOINDUSTRIES', 2, 'xvfb',      73,    '/etc/X11',           'Xvfb Process',                      null, null, null, '/bin/bash',        null);
insert into linux_accounts values(73, 'email_inbox',     'AOINDUSTRIES', 2, 'emailmon',  504,   '/home/e/emailmon',   'Email Monitoring Account',          null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(74, 'email_inbox',     'TEST',         2, 'testimap',  506,   '/home/t/testimap',   'Test Imap',                         null, null, null, '/usr/bin/passwd',  null);
insert into linux_accounts values(75, 'ftponly_account', 'AOINDUSTRIES', 2, 'ftpmon',    505,   '/home/f/ftpmon',     'FTP Monitoring Account',            null, null, null, '/sbin/nologin',    null);
insert into linux_accounts values(76, 'shell_account',   'AOINDUSTRIES', 2, 'aoadmin',   503,   '/home/a/aoadmin',    'AO Industries Admin',               null, null, null, '/bin/bash',        null);
commit;
