COPY "linux_groups" FROM stdin;
news	AOINDUSTRIES	application
root	AOINDUSTRIES	system
bin	AOINDUSTRIES	system
daemon	AOINDUSTRIES	system
sys	AOINDUSTRIES	system
adm	AOINDUSTRIES	system
tty	AOINDUSTRIES	system
disk	AOINDUSTRIES	system
lp	AOINDUSTRIES	system
mem	AOINDUSTRIES	system
kmem	AOINDUSTRIES	system
wheel	AOINDUSTRIES	system
mailonly	AOINDUSTRIES	system
uucp	AOINDUSTRIES	system
man	AOINDUSTRIES	application
floppy	AOINDUSTRIES	system
games	AOINDUSTRIES	application
slocate	AOINDUSTRIES	application
utmp	AOINDUSTRIES	system
pvm	AOINDUSTRIES	application
named	AOINDUSTRIES	application
postgres	AOINDUSTRIES	application
interbase	AOINDUSTRIES	application
nscd	AOINDUSTRIES	application
rpc	AOINDUSTRIES	system
xfs	AOINDUSTRIES	application
mailnull	AOINDUSTRIES	application
ftp	AOINDUSTRIES	application
apache	AOINDUSTRIES	application
xvfb	AOINDUSTRIES	application
nobody	AOINDUSTRIES	system
users	AOINDUSTRIES	system
console	AOINDUSTRIES	system
pppusers	AOINDUSTRIES	system
popusers	AOINDUSTRIES	system
slipusers	AOINDUSTRIES	system
mysql	AOINDUSTRIES	application
sshd	AOINDUSTRIES	application
ftponly	AOINDUSTRIES	ftponly
aoadmin	AOINDUSTRIES	user
lock	AOINDUSTRIES	system
rpm	AOINDUSTRIES	system
ident	AOINDUSTRIES	system
ntp	AOINDUSTRIES	system
ftpmon	AOINDUSTRIES	ftponly
smmsp	AOINDUSTRIES	application
mail	AOINDUSTRIES	system
vcsa	AOINDUSTRIES	system
portmon	AOINDUSTRIES	application
replicator	AOINDUSTRIES	application
tcpdump	AOINDUSTRIES	system
awstats	AOINDUSTRIES	application
dip	AOINDUSTRIES	system
gopher	AOINDUSTRIES	application
haldaemon	AOINDUSTRIES	application
pcap	AOINDUSTRIES	system
dbus	AOINDUSTRIES	system
screen	AOINDUSTRIES	system
avahi	AOINDUSTRIES	system
saslauth	AOINDUSTRIES	system
distcache	AOINDUSTRIES	system
nfsnobody	AOINDUSTRIES	system
rpcuser	AOINDUSTRIES	system
utempter	AOINDUSTRIES	system
\.
