begin;
insert into package_categories values('virtual', 'Virtual Hosting');
insert into package_categories values('aoserv', 'AOServ Software');
insert into package_categories values('backup', 'Backup Service');
insert into package_categories values('sysadmin', 'System Administration');
insert into package_categories values('colocation', 'Colocation');
insert into package_categories values('virtual_dedicated', 'Virtual Dedicated Servers');
insert into package_categories values('virtual_managed', 'Virtual Managed Servers');
insert into package_categories values('dedicated', 'Dedicated Servers');
insert into package_categories values('managed', 'Managed Servers');
insert into package_categories values('reseller', 'Reseller');
commit;
