begin;
insert into package_categories values('aoserv');
insert into package_categories values('application');
insert into package_categories values('backup');
insert into package_categories values('colocation');
insert into package_categories values('dedicated');
insert into package_categories values('managed');
insert into package_categories values('reseller');
insert into package_categories values('sysadmin');
insert into package_categories values('virtual');
insert into package_categories values('virtual_dedicated');
insert into package_categories values('virtual_managed');
commit;
