begin;
insert into payment_types values('check', 'Check', true, false);
insert into payment_types values('money_order', 'Money Order', true, false);
insert into payment_types values('visa', 'Visa', true, true);
insert into payment_types values('mastercard', 'MasterCard', true, true);
insert into payment_types values('discover', 'Discover', true, true);
insert into payment_types values('cash', 'Cash', true, false);
insert into payment_types values('amex', 'American Express', true, true);
insert into payment_types values('paypal', 'PayPal', true, false);
insert into payment_types values('wire', 'Wire Transfer', true, false);
commit;
