begin;
insert into payment_types values('check', true, false);
insert into payment_types values('money_order', true, false);
insert into payment_types values('visa', true, true);
insert into payment_types values('mastercard', true, true);
insert into payment_types values('discover', true, true);
insert into payment_types values('cash', true, false);
insert into payment_types values('amex', true, true);
insert into payment_types values('paypal', true, false);
insert into payment_types values('wire', true, false);
commit;
