begin;
insert into postgres_versions values(14, '7.1');
insert into postgres_versions values(15, '7.2');
insert into postgres_versions values(16, '7.3');
insert into postgres_versions values(17, '8.0');
insert into postgres_versions values(18, '8.1');
insert into postgres_versions values(2586, '8.1');
insert into postgres_versions values(3296, '8.1');
insert into postgres_versions values(3298, '8.3');
commit;
