create table sr_memory (
  server_report integer
    constraint server_rep_memory_pkey primary key,
  mem_total_min integer not null,
  mem_total_avg float4 not null,
  mem_total_max integer not null,
  mem_free_min integer not null,
  mem_free_avg float4 not null,
  mem_free_max integer not null,
  mem_shared_min integer not null,
  mem_shared_avg float4 not null,
  mem_shared_max integer not null,
  buffers_min integer not null,
  buffers_avg float4 not null,
  buffers_max integer not null,
  cached_min integer not null,
  cached_avg float4 not null,
  cached_max integer not null,
  swap_cached_min integer not null,
  swap_cached_avg float4 not null,
  swap_cached_max integer not null,
  active_min integer not null,
  active_avg float4 not null,
  active_max integer not null,
  inact_dirty_min integer not null,
  inact_dirty_avg float4 not null,
  inact_dirty_max integer not null,
  inact_clean_min integer not null,
  inact_clean_avg float4 not null,
  inact_clean_max integer not null,
  inact_target_min integer not null,
  inact_target_avg float4 not null,
  inact_target_max integer not null,
  high_total_min integer not null,
  high_total_avg float4 not null,
  high_total_max integer not null,
  high_free_min integer not null,
  high_free_avg float4 not null,
  high_free_max integer not null,
  low_total_min integer not null,
  low_total_avg float4 not null,
  low_total_max integer not null,
  low_free_min integer not null,
  low_free_avg float4 not null,
  low_free_max integer not null
);
grant all on sr_memory to aoadmin;
grant select, insert, delete on sr_memory to aoserv_app;
