create table sr_net_ip (
  server_report integer
    constraint sr_net_ip_pkey primary key,
  packet_min float4 not null,
  packet_avg float4 not null,
  packet_max float4 not null,
  invalid_headers_min float4 not null,
  invalid_headers_avg float4 not null,
  invalid_headers_max float4 not null,
  forward_min float4 not null,
  forward_avg float4 not null,
  forward_max float4 not null,
  discard_min float4 not null,
  discard_avg float4 not null,
  discard_max float4 not null,
  deliver_min float4 not null,
  deliver_avg float4 not null,
  deliver_max float4 not null,
  request_min float4 not null,
  request_avg float4 not null,
  request_max float4 not null,
  out_drop_min float4 not null,
  out_drop_avg float4 not null,
  out_drop_max float4 not null,
  out_drop_no_route_min float4 not null,
  out_drop_no_route_avg float4 not null,
  out_drop_no_route_max float4 not null,
  out_drop_timeout_min float4 not null,
  out_drop_timeout_avg float4 not null,
  out_drop_timeout_max float4 not null,
  ra_req_min float4 not null,
  ra_req_avg float4 not null,
  ra_req_max float4 not null,
  ra_ok_min float4 not null,
  ra_ok_avg float4 not null,
  ra_ok_max float4 not null,
  ra_fail_min float4 not null,
  ra_fail_avg float4 not null,
  ra_fail_max float4 not null
);
grant all on sr_net_ip to aoadmin;
grant select, insert, delete on sr_net_ip to aoserv_app;
