create table sr_net_icmp (
  server_report integer
    constraint sr_net_icmp_pkey primary key,
  in_message_min float4 not null,
  in_message_avg float4 not null,
  in_message_max float4 not null,
  in_fail_min float4 not null,
  in_fail_avg float4 not null,
  in_fail_max float4 not null,
  in_unreachable_min float4 not null,
  in_unreachable_avg float4 not null,
  in_unreachable_max float4 not null,
  in_timeout_min float4 not null,
  in_timeout_avg float4 not null,
  in_timeout_max float4 not null,
  in_quench_min float4 not null,
  in_quench_avg float4 not null,
  in_quench_max float4 not null,
  in_redirect_min float4 not null,
  in_redirect_avg float4 not null,
  in_redirect_max float4 not null,
  in_echo_request_min float4 not null,
  in_echo_request_avg float4 not null,
  in_echo_request_max float4 not null,
  in_echo_reply_min float4 not null,
  in_echo_reply_avg float4 not null,
  in_echo_reply_max float4 not null,
  out_message_min float4 not null,
  out_message_avg float4 not null,
  out_message_max float4 not null,
  out_fail_min float4 not null,
  out_fail_avg float4 not null,
  out_fail_max float4 not null,
  out_unreachable_min float4 not null,
  out_unreachable_avg float4 not null,
  out_unreachable_max float4 not null,
  out_timeout_min float4 not null,
  out_timeout_avg float4 not null,
  out_timeout_max float4 not null,
  out_redirect_min float4 not null,
  out_redirect_avg float4 not null,
  out_redirect_max float4 not null,
  out_echo_reply_min float4 not null,
  out_echo_reply_avg float4 not null,
  out_echo_reply_max float4 not null
);
grant all on sr_net_icmp to aoadmin;
grant select, insert, delete on sr_net_icmp to aoserv_app;
