create sequence sr_net_devices_pkey_seq cycle;
grant all on sr_net_devices_pkey_seq to aoadmin;
grant select, update on sr_net_devices_pkey_seq to aoserv_app;

create table sr_net_devices (
  pkey integer
    default nextval('sr_net_devices_pkey_seq')
    constraint sr_net_devices_pkey primary key,
  server_report integer not null,
  device_id text not null,
  rx_bytes_min float4 not null,
  rx_bytes_avg float4 not null,
  rx_bytes_max float4 not null,
  rx_packets_min float4 not null,
  rx_packets_avg float4 not null,
  rx_packets_max float4 not null,
  rx_errors_min float4 not null,
  rx_errors_avg float4 not null,
  rx_errors_max float4 not null,
  rx_drop_min float4 not null,
  rx_drop_avg float4 not null,
  rx_drop_max float4 not null,
  rx_fifo_min float4 not null,
  rx_fifo_avg float4 not null,
  rx_fifo_max float4 not null,
  rx_frame_min float4 not null,
  rx_frame_avg float4 not null,
  rx_frame_max float4 not null,
  rx_compress_min float4 not null,
  rx_compress_avg float4 not null,
  rx_compress_max float4 not null,
  rx_multicast_min float4 not null,
  rx_multicast_avg float4 not null,
  rx_multicast_max float4 not null,
  tx_bytes_min float4 not null,
  tx_bytes_avg float4 not null,
  tx_bytes_max float4 not null,
  tx_packets_min float4 not null,
  tx_packets_avg float4 not null,
  tx_packets_max float4 not null,
  tx_errors_min float4 not null,
  tx_errors_avg float4 not null,
  tx_errors_max float4 not null,
  tx_drop_min float4 not null,
  tx_drop_avg float4 not null,
  tx_drop_max float4 not null,
  tx_fifo_min float4 not null,
  tx_fifo_avg float4 not null,
  tx_fifo_max float4 not null,
  tx_colls_min float4 not null,
  tx_colls_avg float4 not null,
  tx_colls_max float4 not null,
  tx_carrier_min float4 not null,
  tx_carrier_avg float4 not null,
  tx_carrier_max float4 not null,
  tx_compressed_min float4 not null,
  tx_compressed_avg float4 not null,
  tx_compressed_max float4 not null,
  listen_min integer not null,
  listen_avg float4 not null,
  listen_max integer not null,
  unique(server_report, device_id)
);
grant all on sr_net_devices to aoadmin;
grant select, insert, delete on sr_net_devices to aoserv_app;
