create table sr_net_tcp (
  server_report integer
    constraint sr_net_tcp_pkey primary key,
  active_connect_min float4 not null,
  active_connect_avg float4 not null,
  active_connect_max float4 not null,
  passive_connect_min float4 not null,
  passive_connect_avg float4 not null,
  passive_connect_max float4 not null,
  fail_connect_min float4 not null,
  fail_connect_avg float4 not null,
  fail_connect_max float4 not null,
  in_reset_min float4 not null,
  in_reset_avg float4 not null,
  in_reset_max float4 not null,
  connect_min float4 not null,
  connect_avg float4 not null,
  connect_max float4 not null,
  segment_receive_min float4 not null,
  segment_receive_avg float4 not null,
  segment_receive_max float4 not null,
  segment_send_min float4 not null,
  segment_send_avg float4 not null,
  segment_send_max float4 not null,
  segment_resend_min float4 not null,
  segment_resend_avg float4 not null,
  segment_resend_max float4 not null,
  bad_segment_receive_min float4 not null,
  bad_segment_receive_avg float4 not null,
  bad_segment_receive_max float4 not null,
  out_reset_min float4 not null,
  out_reset_avg float4 not null,
  out_reset_max float4 not null
);
grant all on sr_net_tcp to aoadmin;
grant select, insert, delete on sr_net_tcp to aoserv_app;
