COPY "technology_names" FROM stdin;
analog	\N	\N	\N	\N	\N
anonftp	\N	\N	\N	\N	\N
Socket	\N	\N	\N	\N	\N
Spreadsheet-WriteExcel	\N	\N	\N	\N	\N
daemontools	\N	\N	\N	\N	\N
dot-forward	\N	\N	\N	\N	\N
fastforward	\N	\N	\N	\N	\N
qmail	\N	\N	\N	\N	\N
apache	\N	\N	\N	\N	\N
apache-devel	\N	\N	\N	\N	\N
Apache-JSSI	\N	\N	\N	\N	\N
Apache-Jyve	\N	\N	\N	\N	\N
Apache-Turbine	\N	\N	\N	\N	\N
ash	\N	\N	\N	\N	\N
aspell	\N	\N	\N	\N	\N
autoconf	\N	\N	\N	\N	\N
automake	\N	\N	\N	\N	\N
basesystem	\N	\N	\N	\N	\N
bash	\N	\N	\N	\N	\N
bc	\N	\N	\N	\N	\N
bdflush	\N	\N	\N	\N	\N
bind	\N	\N	\N	\N	\N
bind-utils	\N	\N	\N	\N	\N
binutils	\N	\N	\N	\N	\N
byacc	\N	\N	\N	\N	\N
bzip2	\N	\N	\N	\N	\N
caching-nameserver	\N	\N	\N	\N	\N
chkconfig	\N	\N	\N	\N	\N
chkfontpath	\N	\N	\N	\N	\N
compat-libstdc++	\N	\N	\N	\N	\N
console-tools	\N	\N	\N	\N	\N
ucspi-tcp	\N	\N	\N	\N	\N
cos	\N	\N	\N	\N	\N
cpio	\N	\N	\N	\N	\N
cpp	\N	\N	\N	\N	\N
cracklib	\N	\N	\N	\N	\N
cracklib-dicts	\N	\N	\N	\N	\N
crontabs	\N	\N	\N	\N	\N
Crypt-CBC	\N	\N	\N	\N	\N
Crypt-DES	\N	\N	\N	\N	\N
cvs	\N	\N	\N	\N	\N
cyrus-sasl	\N	\N	\N	\N	\N
Data-ShowTable	\N	\N	\N	\N	\N
db1	\N	\N	\N	\N	\N
db2	\N	\N	\N	\N	\N
db3	\N	\N	\N	\N	\N
DBD-Pg	\N	\N	\N	\N	\N
DBI	\N	\N	\N	\N	\N
dev	\N	\N	\N	\N	\N
dev86	\N	\N	\N	\N	\N
diffutils	\N	\N	\N	\N	\N
Digest-MD5	\N	\N	\N	\N	\N
ezmlm	\N	\N	\N	\N	\N
mrtg	\N	\N	\N	\N	\N
e2fsprogs	\N	\N	\N	\N	\N
e2fsprogs-devel	\N	\N	\N	\N	\N
ecs	\N	\N	\N	\N	\N
ed	\N	\N	\N	\N	\N
elm	\N	\N	\N	\N	\N
sysstat	\N	\N	\N	\N	\N
hwcrypto	\N	\N	\N	\N	\N
emacs	\N	\N	\N	\N	\N
emacs-el	\N	\N	\N	\N	\N
emacs-leim	\N	\N	\N	\N	\N
emacs-nox	\N	\N	\N	\N	\N
emacs-X11	\N	\N	\N	\N	\N
expect	\N	\N	\N	\N	\N
fastcgi	\N	\N	\N	\N	\N
FCGI	\N	\N	\N	\N	\N
fftw	\N	\N	\N	\N	\N
fftw-devel	\N	\N	\N	\N	\N
file	\N	\N	\N	\N	\N
filesystem	\N	\N	\N	\N	\N
fileutils	\N	\N	\N	\N	\N
findutils	\N	\N	\N	\N	\N
flex	\N	\N	\N	\N	\N
fop	\N	\N	\N	\N	\N
fortune-mod	\N	\N	\N	\N	\N
FreeMarker	\N	\N	\N	\N	\N
freetype	\N	\N	\N	\N	\N
ftp	\N	\N	\N	\N	\N
iptables-ipv6	\N	\N	\N	\N	\N
Garbage	\N	\N	\N	\N	\N
gawk	\N	\N	\N	\N	\N
gcc	\N	\N	\N	\N	\N
gcc-c++	\N	\N	\N	\N	\N
gcc-g77	\N	\N	\N	\N	\N
gcc-objc	\N	\N	\N	\N	\N
gd	\N	\N	\N	\N	\N
gdb	\N	\N	\N	\N	\N
gdbm	\N	\N	\N	\N	\N
gdbm-devel	\N	\N	\N	\N	\N
ghostscript	\N	\N	\N	\N	\N
ghostscript-fonts	\N	\N	\N	\N	\N
glib	\N	\N	\N	\N	\N
glibc	\N	\N	\N	\N	\N
glibc-common	\N	\N	\N	\N	\N
glibc-devel	\N	\N	\N	\N	\N
glib-devel	\N	\N	\N	\N	\N
gmp	\N	\N	\N	\N	\N
gnupg	\N	\N	\N	\N	\N
gnu.regexp	\N	\N	\N	\N	\N
gpm	\N	\N	\N	\N	\N
grep	\N	\N	\N	\N	\N
groff	\N	\N	\N	\N	\N
gtk+	\N	\N	\N	\N	\N
gtk+-devel	\N	\N	\N	\N	\N
gzip	\N	\N	\N	\N	\N
hdparm	\N	\N	\N	\N	\N
HTML-Parser	\N	\N	\N	\N	\N
imap	\N	\N	\N	\N	\N
indexhtml	\N	\N	\N	\N	\N
info	\N	\N	\N	\N	\N
initscripts	\N	\N	\N	\N	\N
InterBaseSS_LI	\N	\N	\N	\N	\N
InterClient	\N	\N	\N	\N	\N
iputils	\N	\N	\N	\N	\N
jaf	\N	\N	\N	\N	\N
castor	\N	\N	\N	\N	\N
jakarta-cocoon	\N	\N	\N	\N	\N
jakarta-oro	\N	\N	\N	\N	\N
jakarta-regexp	\N	\N	\N	\N	\N
jakarta-servletapi	\N	\N	\N	\N	\N
jakarta-slide	\N	\N	\N	\N	\N
eject	\N	\N	\N	\N	\N
jakarta-taglibs	\N	\N	\N	\N	\N
jakarta-tomcat	\N	\N	\N	\N	\N
jakarta-watchdog	\N	\N	\N	\N	\N
javamail	\N	\N	\N	\N	\N
JBoss	\N	\N	\N	\N	\N
jdbc	\N	\N	\N	\N	\N
tkinter	\N	\N	\N	\N	\N
ant	\N	\N	\N	\N	\N
JSDK	\N	\N	\N	\N	\N
JSP	\N	\N	\N	\N	\N
jsse	\N	\N	\N	\N	\N
kavachart	\N	\N	\N	\N	\N
kernel-headers	\N	\N	\N	\N	\N
kernel-smp	\N	\N	\N	\N	\N
krb5-libs	\N	\N	\N	\N	\N
less	\N	\N	\N	\N	\N
libgr	\N	\N	\N	\N	\N
libjpeg	\N	\N	\N	\N	\N
libjpeg-devel	\N	\N	\N	\N	\N
libmcrypt	\N	\N	\N	\N	\N
libmng	\N	\N	\N	\N	\N
libnet	\N	\N	\N	\N	\N
libpng	\N	\N	\N	\N	\N
libpng-devel	\N	\N	\N	\N	\N
libstdc++	\N	\N	\N	\N	\N
libstdc++-devel	\N	\N	\N	\N	\N
tmpwatch	\N	\N	\N	\N	\N
libtermcap	\N	\N	\N	\N	\N
libtiff	\N	\N	\N	\N	\N
libtool	\N	\N	\N	\N	\N
libtool-libs	\N	\N	\N	\N	\N
libungif	\N	\N	\N	\N	\N
libungif-progs	\N	\N	\N	\N	\N
libwww-perl	\N	\N	\N	\N	\N
lilo	\N	\N	\N	\N	\N
linuxconf	\N	\N	\N	\N	\N
logrotate	\N	\N	\N	\N	\N
traceroute	\N	\N	\N	\N	\N
losetup	\N	\N	\N	\N	\N
lslk	\N	\N	\N	\N	\N
lsof	\N	\N	\N	\N	\N
ltrace	\N	\N	\N	\N	\N
lynx	\N	\N	\N	\N	\N
m4	\N	\N	\N	\N	\N
mailcap	\N	\N	\N	\N	\N
mailx	\N	\N	\N	\N	\N
majordomo	\N	\N	\N	\N	\N
make	\N	\N	\N	\N	\N
MAKEDEV	\N	\N	\N	\N	\N
man	\N	\N	\N	\N	\N
man-pages	\N	\N	\N	\N	\N
mc	\N	\N	\N	\N	\N
mcrypt	\N	\N	\N	\N	\N
Mesa	\N	\N	\N	\N	\N
metamail	\N	\N	\N	\N	\N
MIME-Base64	\N	\N	\N	\N	\N
mingetty	\N	\N	\N	\N	\N
mkbootdisk	\N	\N	\N	\N	\N
mkinitrd	\N	\N	\N	\N	\N
mktemp	\N	\N	\N	\N	\N
mm-mysql	\N	\N	\N	\N	\N
mod_ssl	\N	\N	\N	\N	\N
modutils	\N	\N	\N	\N	\N
mount	\N	\N	\N	\N	\N
Msql-Mysql-modules	\N	\N	\N	\N	\N
mutt	\N	\N	\N	\N	\N
mx	\N	\N	\N	\N	\N
ncompress	\N	\N	\N	\N	\N
ncurses	\N	\N	\N	\N	\N
ncurses4	\N	\N	\N	\N	\N
ncurses-devel	\N	\N	\N	\N	\N
unzip	\N	\N	\N	\N	\N
Net-Daemon	\N	\N	\N	\N	\N
net-tools	\N	\N	\N	\N	\N
nscd	\N	\N	\N	\N	\N
openldap	\N	\N	\N	\N	\N
openssh	\N	\N	\N	\N	\N
openssh-clients	\N	\N	\N	\N	\N
openssh-server	\N	\N	\N	\N	\N
openssl	\N	\N	\N	\N	\N
openssl-devel	\N	\N	\N	\N	\N
openxml	\N	\N	\N	\N	\N
ozone	\N	\N	\N	\N	\N
pam	\N	\N	\N	\N	\N
passwd	\N	\N	\N	\N	\N
patch	\N	\N	\N	\N	\N
perl	\N	\N	\N	\N	\N
php	\N	\N	\N	\N	\N
URI	\N	\N	\N	\N	\N
urw-fonts	\N	\N	\N	\N	\N
utempter	\N	\N	\N	\N	\N
phpMyAdmin	\N	\N	\N	\N	\N
util-linux	\N	\N	\N	\N	\N
village	\N	\N	\N	\N	\N
pidentd	\N	\N	\N	\N	\N
pine	\N	\N	\N	\N	\N
PlRPC	\N	\N	\N	\N	\N
pmake	\N	\N	\N	\N	\N
vim-common	\N	\N	\N	\N	\N
PoolMan	\N	\N	\N	\N	\N
pop3	\N	\N	\N	\N	\N
popt	\N	\N	\N	\N	\N
postgresql	\N	\N	\N	\N	\N
procinfo	\N	\N	\N	\N	\N
procmail	\N	\N	\N	\N	\N
procps	\N	\N	\N	\N	\N
vim-minimal	\N	\N	\N	\N	\N
psmisc	\N	\N	\N	\N	\N
pspell	\N	\N	\N	\N	\N
pvm	\N	\N	\N	\N	\N
pvm-gui	\N	\N	\N	\N	\N
pwdb	\N	\N	\N	\N	\N
python	\N	\N	\N	\N	\N
vixie-cron	\N	\N	\N	\N	\N
qt	\N	\N	\N	\N	\N
perl-suidperl	\N	\N	\N	\N	\N
webmacro	\N	\N	\N	\N	\N
raidtools	\N	\N	\N	\N	\N
wget	\N	\N	\N	\N	\N
readline	\N	\N	\N	\N	\N
readline-devel	\N	\N	\N	\N	\N
redhat-logos	\N	\N	\N	\N	\N
redhat-release	\N	\N	\N	\N	\N
rgrep	\N	\N	\N	\N	\N
rmt	\N	\N	\N	\N	\N
rootfiles	\N	\N	\N	\N	\N
rpm	\N	\N	\N	\N	\N
rpm-build	\N	\N	\N	\N	\N
which	\N	\N	\N	\N	\N
sash	\N	\N	\N	\N	\N
screen	\N	\N	\N	\N	\N
sed	\N	\N	\N	\N	\N
sendmail	\N	\N	\N	\N	\N
sendmail-cf	\N	\N	\N	\N	\N
setserial	\N	\N	\N	\N	\N
setup	\N	\N	\N	\N	\N
shadow-utils	\N	\N	\N	\N	\N
sharutils	\N	\N	\N	\N	\N
sh-utils	\N	\N	\N	\N	\N
slang	\N	\N	\N	\N	\N
slocate	\N	\N	\N	\N	\N
words	\N	\N	\N	\N	\N
spfc	\N	\N	\N	\N	\N
wu-ftpd	\N	\N	\N	\N	\N
wv	\N	\N	\N	\N	\N
xang	\N	\N	\N	\N	\N
stat	\N	\N	\N	\N	\N
Storable	\N	\N	\N	\N	\N
stunnel	\N	\N	\N	\N	\N
Xaw3d	\N	\N	\N	\N	\N
symlinks	\N	\N	\N	\N	\N
sysklogd	\N	\N	\N	\N	\N
SysVinit	\N	\N	\N	\N	\N
talk	\N	\N	\N	\N	\N
talk-server	\N	\N	\N	\N	\N
tar	\N	\N	\N	\N	\N
tcl	\N	\N	\N	\N	\N
tcpdump	\N	\N	\N	\N	\N
tcp_wrappers	\N	\N	\N	\N	\N
tcsh	\N	\N	\N	\N	\N
telnet	\N	\N	\N	\N	\N
telnet-server	\N	\N	\N	\N	\N
termcap	\N	\N	\N	\N	\N
texinfo	\N	\N	\N	\N	\N
textutils	\N	\N	\N	\N	\N
time	\N	\N	\N	\N	\N
tix	\N	\N	\N	\N	\N
tk	\N	\N	\N	\N	\N
kernel-doc	\N	\N	\N	\N	\N
ezmlm-idx	\N	\N	\N	\N	\N
qmail-smtpd-auth	\N	\N	\N	\N	\N
dhcpcd	\N	\N	\N	\N	\N
mod_jk	\N	\N	\N	\N	\N
rdist	\N	\N	\N	\N	\N
rsync	\N	\N	\N	\N	\N
XFree86	\N	\N	\N	\N	\N
XFree86-100dpi-fonts	\N	\N	\N	\N	\N
XFree86-75dpi-fonts	\N	\N	\N	\N	\N
XFree86-devel	\N	\N	\N	\N	\N
XFree86-ISO8859-2-75dpi-fonts	\N	\N	\N	\N	\N
XFree86-libs	\N	\N	\N	\N	\N
XFree86-xfs	\N	\N	\N	\N	\N
XFree86-Xvfb	\N	\N	\N	\N	\N
xinetd	\N	\N	\N	\N	\N
xmlrpc-java	\N	\N	\N	\N	\N
zip	\N	\N	\N	\N	\N
zlib	\N	\N	\N	\N	\N
zlib-devel	\N	\N	\N	\N	\N
ApacheDBI	\N	\N	\N	\N	\N
aspell-devel	\N	\N	\N	\N	\N
bind-devel	\N	\N	\N	\N	\N
bzip2-devel	\N	\N	\N	\N	\N
bzip2-libs	\N	\N	\N	\N	\N
curl	\N	\N	\N	\N	\N
curl-devel	\N	\N	\N	\N	\N
cyrus-sasl-md5	\N	\N	\N	\N	\N
cyrus-sasl-plain	\N	\N	\N	\N	\N
db2-devel	\N	\N	\N	\N	\N
db3-devel	\N	\N	\N	\N	\N
dialog	\N	\N	\N	\N	\N
dosfstools	\N	\N	\N	\N	\N
expat	\N	\N	\N	\N	\N
expat-devel	\N	\N	\N	\N	\N
finger	\N	\N	\N	\N	\N
freetype-devel	\N	\N	\N	\N	\N
gcc3	\N	\N	\N	\N	\N
gcc3-c++	\N	\N	\N	\N	\N
gcc3-g77	\N	\N	\N	\N	\N
gcc3-java	\N	\N	\N	\N	\N
gcc3-objc	\N	\N	\N	\N	\N
gcc-chill	\N	\N	\N	\N	\N
gcc-java	\N	\N	\N	\N	\N
gd-devel	\N	\N	\N	\N	\N
glibc-profile	\N	\N	\N	\N	\N
gmp-devel	\N	\N	\N	\N	\N
imap-devel	\N	\N	\N	\N	\N
iproute	\N	\N	\N	\N	\N
iptables	\N	\N	\N	\N	\N
jikes	\N	\N	\N	\N	\N
kernel	\N	\N	\N	\N	\N
krb5-devel	\N	\N	\N	\N	\N
libcap	\N	\N	\N	\N	\N
libgcc	\N	\N	\N	\N	\N
libgcj	\N	\N	\N	\N	\N
libgcj3	\N	\N	\N	\N	\N
libgcj3-devel	\N	\N	\N	\N	\N
libgcj-devel	\N	\N	\N	\N	\N
libmcrypt-devel	\N	\N	\N	\N	\N
libstdc++3	\N	\N	\N	\N	\N
libstdc++3-devel	\N	\N	\N	\N	\N
libtiff-devel	\N	\N	\N	\N	\N
libxml2	\N	\N	\N	\N	\N
libxml2-devel	\N	\N	\N	\N	\N
libxslt	\N	\N	\N	\N	\N
libxslt-devel	\N	\N	\N	\N	\N
mhash	\N	\N	\N	\N	\N
mhash-devel	\N	\N	\N	\N	\N
mm	\N	\N	\N	\N	\N
mm-devel	\N	\N	\N	\N	\N
mod_dav	\N	\N	\N	\N	\N
mod_perl	\N	\N	\N	\N	\N
nc	\N	\N	\N	\N	\N
ntp	\N	\N	\N	\N	\N
Omni	\N	\N	\N	\N	\N
openldap-clients	\N	\N	\N	\N	\N
openldap-devel	\N	\N	\N	\N	\N
openssl095a	\N	\N	\N	\N	\N
openssl096	\N	\N	\N	\N	\N
openssl-perl	\N	\N	\N	\N	\N
pam-devel	\N	\N	\N	\N	\N
pdflib	\N	\N	\N	\N	\N
pdflib-devel	\N	\N	\N	\N	\N
perl-CGI	\N	\N	\N	\N	\N
perl-CPAN	\N	\N	\N	\N	\N
perl-DB_File	\N	\N	\N	\N	\N
perl-NDBM_File	\N	\N	\N	\N	\N
pspell-devel	\N	\N	\N	\N	\N
srm	\N	\N	\N	\N	\N
syslinux	\N	\N	\N	\N	\N
tamago	\N	\N	\N	\N	\N
tetex	\N	\N	\N	\N	\N
tetex-fonts	\N	\N	\N	\N	\N
ttfonts	\N	\N	\N	\N	\N
ttfonts-ja	\N	\N	\N	\N	\N
ucd-snmp	\N	\N	\N	\N	\N
ucd-snmp-devel	\N	\N	\N	\N	\N
ucd-snmp-utils	\N	\N	\N	\N	\N
unixODBC	\N	\N	\N	\N	\N
unixODBC-devel	\N	\N	\N	\N	\N
VFlib2	\N	\N	\N	\N	\N
vim-enhanced	\N	\N	\N	\N	\N
whois	\N	\N	\N	\N	\N
XFree86-cyrillic-fonts	\N	\N	\N	\N	\N
XFree86-ISO8859-15-100dpi-fonts	\N	\N	\N	\N	\N
XFree86-ISO8859-15-75dpi-fonts	\N	\N	\N	\N	\N
XFree86-ISO8859-2-100dpi-fonts	\N	\N	\N	\N	\N
XFree86-ISO8859-9-100dpi-fonts	\N	\N	\N	\N	\N
XFree86-ISO8859-9-75dpi-fonts	\N	\N	\N	\N	\N
PGPcmdln	\N	\N	\N	\N	\N
soap	\N	\N	\N	\N	\N
jdk	\N	\N	\N	\N	\N
xerces	\N	\N	\N	\N	\N
xalan	\N	\N	\N	\N	\N
IBMJava	\N	\N	\N	\N	\N
j2sdk	\N	\N	\N	\N	\N
httperf	\N	\N	\N	\N	\N
struts	\N	\N	\N	\N	\N
Bundle-libnet	\N	\N	\N	\N	\N
CGI	\N	\N	\N	\N	\N
File-Temp	\N	\N	\N	\N	\N
HTML-Tagset	\N	\N	\N	\N	\N
Parse-RecDescent	\N	\N	\N	\N	\N
python-devel	\N	\N	\N	\N	\N
qt-devel	\N	\N	\N	\N	\N
python2	\N	\N	\N	\N	\N
python2-devel	\N	\N	\N	\N	\N
python-docs	\N	\N	\N	\N	\N
python-tools	\N	\N	\N	\N	\N
Devel-CoreStack	\N	\N	\N	\N	\N
HTML-Element-Extended	\N	\N	\N	\N	\N
HTML-Tree	\N	\N	\N	\N	\N
libxml-perl	\N	\N	\N	\N	\N
Scalar-List-Utils	\N	\N	\N	\N	\N
Test-Harness	\N	\N	\N	\N	\N
Test-Simple	\N	\N	\N	\N	\N
XML-DOM	\N	\N	\N	\N	\N
XML-GDOME	\N	\N	\N	\N	\N
XML-LibXML	\N	\N	\N	\N	\N
XML-LibXML-Common	\N	\N	\N	\N	\N
XML-NamespaceSupport	\N	\N	\N	\N	\N
XML-Parser	\N	\N	\N	\N	\N
XML-RegExp	\N	\N	\N	\N	\N
XML-SAX	\N	\N	\N	\N	\N
XML-Simple	\N	\N	\N	\N	\N
XML-SimpleObject	\N	\N	\N	\N	\N
XML-TreeBuilder	\N	\N	\N	\N	\N
XML-Twig	\N	\N	\N	\N	\N
XML-Writer	\N	\N	\N	\N	\N
XML-XSLT	\N	\N	\N	\N	\N
gdome2	\N	\N	\N	\N	\N
gdome2-devel	\N	\N	\N	\N	\N
samba	\N	\N	\N	\N	\N
samba-common	\N	\N	\N	\N	\N
AppConfig	\N	\N	\N	\N	\N
libnas2-static-devel	\N	\N	\N	\N	\N
libqt3	\N	\N	\N	\N	\N
libqt3-devel	\N	\N	\N	\N	\N
bootloader-utils	\N	\N	\N	\N	\N
Archive-Tar	\N	\N	\N	\N	\N
Compress-Zlib	\N	\N	\N	\N	\N
DateManip	\N	\N	\N	\N	\N
DBIx-Password	\N	\N	\N	\N	\N
Email-Valid	\N	\N	\N	\N	\N
Font-AFM	\N	\N	\N	\N	\N
HTML-Format	\N	\N	\N	\N	\N
Image-Size	\N	\N	\N	\N	\N
libapreq	\N	\N	\N	\N	\N
Mail-Sendmail	\N	\N	\N	\N	\N
MailTools	\N	\N	\N	\N	\N
MD5	\N	\N	\N	\N	\N
Schedule-Cron	\N	\N	\N	\N	\N
Template-Toolkit	\N	\N	\N	\N	\N
TimeDate	\N	\N	\N	\N	\N
Time-HiRes	\N	\N	\N	\N	\N
Time-modules	\N	\N	\N	\N	\N
XML-RSS	\N	\N	\N	\N	\N
IO-Zlib	\N	\N	\N	\N	\N
Apache-Test	\N	\N	\N	\N	\N
Test-Manifest	\N	\N	\N	\N	\N
ExtUtils-MakeMaker	\N	\N	\N	\N	\N
reiserfs-utils	\N	\N	\N	\N	\N
cyrus-sasl-devel	\N	\N	\N	\N	\N
ImageMagick	\N	\N	\N	\N	\N
ImageMagick-Magick++	\N	\N	\N	\N	\N
ImageMagick-devel	\N	\N	\N	\N	\N
libqt3-mysql	\N	\N	\N	\N	\N
libqt3-odbc	\N	\N	\N	\N	\N
libunixODBC2	\N	\N	\N	\N	\N
common-licenses	\N	\N	\N	\N	\N
libunixODBC2-qt	\N	\N	\N	\N	\N
coreutils	\N	\N	\N	\N	\N
coreutils-doc	\N	\N	\N	\N	\N
libunixODBC2-devel	\N	\N	\N	\N	\N
nas	\N	\N	\N	\N	\N
qt3-common	\N	\N	\N	\N	\N
qt3-example	\N	\N	\N	\N	\N
VFlib2-devel	\N	\N	\N	\N	\N
wv-devel	\N	\N	\N	\N	\N
libXaw3d7	\N	\N	\N	\N	\N
elfutils	\N	\N	\N	\N	\N
etcskel	\N	\N	\N	\N	\N
libXaw3d7-devel	\N	\N	\N	\N	\N
libgdome0	\N	\N	\N	\N	\N
libgdome0-devel	\N	\N	\N	\N	\N
fontconfig	\N	\N	\N	\N	\N
font-tools	\N	\N	\N	\N	\N
MySQL Connector/J	\N	\N	\N	\N	\N
freetype-tools	\N	\N	\N	\N	\N
libdb4.1-devel	\N	\N	\N	\N	\N
gcc-cpp	\N	\N	\N	\N	\N
gettext-base	\N	\N	\N	\N	\N
libdb4.1-static-devel	\N	\N	\N	\N	\N
libdbcxx4.1	\N	\N	\N	\N	\N
gpg-pubkey	\N	\N	\N	\N	\N
libldap2-devel	\N	\N	\N	\N	\N
groff-for-man	\N	\N	\N	\N	\N
gtk+2.0	\N	\N	\N	\N	\N
gtkdialogs	\N	\N	\N	\N	\N
libldap2-devel-static	\N	\N	\N	\N	\N
libsasl2-devel	\N	\N	\N	\N	\N
ifplugd	\N	\N	\N	\N	\N
tcp_wrappers-devel	\N	\N	\N	\N	\N
info-install	\N	\N	\N	\N	\N
apache-modules	\N	\N	\N	\N	\N
iproute2	\N	\N	\N	\N	\N
db1-devel	\N	\N	\N	\N	\N
db1-tools	\N	\N	\N	\N	\N
libmm1	\N	\N	\N	\N	\N
kernel-enterprise	\N	\N	\N	\N	\N
libmm1-devel	\N	\N	\N	\N	\N
ldconfig	\N	\N	\N	\N	\N
libmm1-static-devel	\N	\N	\N	\N	\N
libacl1	\N	\N	\N	\N	\N
libatk1.0_0	\N	\N	\N	\N	\N
libattr1	\N	\N	\N	\N	\N
libbzip2_1	\N	\N	\N	\N	\N
libconsole0	\N	\N	\N	\N	\N
libcrack2	\N	\N	\N	\N	\N
libcups2	\N	\N	\N	\N	\N
libcurl2	\N	\N	\N	\N	\N
libdb4.1	\N	\N	\N	\N	\N
libelfutils1	\N	\N	\N	\N	\N
libexpat0	\N	\N	\N	\N	\N
libext2fs2	\N	\N	\N	\N	\N
libfontconfig1	\N	\N	\N	\N	\N
libfreetype6	\N	\N	\N	\N	\N
libgcc1	\N	\N	\N	\N	\N
libgd2	\N	\N	\N	\N	\N
libgdbm2	\N	\N	\N	\N	\N
libgdk_pixbuf2.0_0	\N	\N	\N	\N	\N
libglade2.0_0	\N	\N	\N	\N	\N
libglib1.2	\N	\N	\N	\N	\N
libglib2.0_0	\N	\N	\N	\N	\N
libgpm1	\N	\N	\N	\N	\N
libgtk+2.0_0	\N	\N	\N	\N	\N
libgtk+-x11-2.0_0	\N	\N	\N	\N	\N
libintl2	\N	\N	\N	\N	\N
libjpeg62	\N	\N	\N	\N	\N
libkrb51	\N	\N	\N	\N	\N
libldap2	\N	\N	\N	\N	\N
libmagic1	\N	\N	\N	\N	\N
libMesaGLU1	\N	\N	\N	\N	\N
libncurses5	\N	\N	\N	\N	\N
libnet-snmp50	\N	\N	\N	\N	\N
libnewt0.51	\N	\N	\N	\N	\N
libopenssl0.9.7	\N	\N	\N	\N	\N
libpango1.0_0	\N	\N	\N	\N	\N
libpcre0	\N	\N	\N	\N	\N
libpng3	\N	\N	\N	\N	\N
libpwdb0	\N	\N	\N	\N	\N
libpython2.3	\N	\N	\N	\N	\N
libreadline4	\N	\N	\N	\N	\N
libsasl2	\N	\N	\N	\N	\N
libslang1	\N	\N	\N	\N	\N
libstdc++5	\N	\N	\N	\N	\N
libtermcap2	\N	\N	\N	\N	\N
libtiff3	\N	\N	\N	\N	\N
libuser	\N	\N	\N	\N	\N
libuser1	\N	\N	\N	\N	\N
libutempter0	\N	\N	\N	\N	\N
libxclass0	\N	\N	\N	\N	\N
libxfree86	\N	\N	\N	\N	\N
apache-source	\N	\N	\N	\N	\N
libxpm4	\N	\N	\N	\N	\N
db3-utils	\N	\N	\N	\N	\N
locales	\N	\N	\N	\N	\N
locales-en	\N	\N	\N	\N	\N
libsasl2-plug-crammd5	\N	\N	\N	\N	\N
libsasl2-plug-digestmd5	\N	\N	\N	\N	\N
libsasl2-plug-gssapi	\N	\N	\N	\N	\N
libsasl2-plug-login	\N	\N	\N	\N	\N
libsasl2-plug-plain	\N	\N	\N	\N	\N
makedev	\N	\N	\N	\N	\N
Mail-SpamAssassin	\N	\N	\N	\N	\N
mandrake-release	\N	\N	\N	\N	\N
mdk-menu-messages	\N	\N	\N	\N	\N
menu	\N	\N	\N	\N	\N
gcc-colorgcc	\N	\N	\N	\N	\N
mpage	\N	\N	\N	\N	\N
gcc-gnat	\N	\N	\N	\N	\N
perl-ExtUtils_PerlPP	\N	\N	\N	\N	\N
gcc-gpc	\N	\N	\N	\N	\N
net-snmp	\N	\N	\N	\N	\N
net-snmp-mibs	\N	\N	\N	\N	\N
net-snmp-utils	\N	\N	\N	\N	\N
gcj-tools	\N	\N	\N	\N	\N
libbinutils2	\N	\N	\N	\N	\N
libf2c0	\N	\N	\N	\N	\N
libgcj4	\N	\N	\N	\N	\N
libgcj4-devel	\N	\N	\N	\N	\N
libgcj4-static-devel	\N	\N	\N	\N	\N
pango	\N	\N	\N	\N	\N
libgnat1	\N	\N	\N	\N	\N
tetex-latex	\N	\N	\N	\N	\N
perl-Authen-SASL	\N	\N	\N	\N	\N
perl-base	\N	\N	\N	\N	\N
perl-Convert-ASN1	\N	\N	\N	\N	\N
perl-Digest-HMAC	\N	\N	\N	\N	\N
perl-Digest-SHA1	\N	\N	\N	\N	\N
perl-Expect	\N	\N	\N	\N	\N
perl-Glib	\N	\N	\N	\N	\N
perl-Gtk2	\N	\N	\N	\N	\N
perl-HTML-Parser	\N	\N	\N	\N	\N
perl-HTML-Tagset	\N	\N	\N	\N	\N
perl-IO-Tty	\N	\N	\N	\N	\N
perl-ldap	\N	\N	\N	\N	\N
perl-libwww-perl	\N	\N	\N	\N	\N
perl-Locale-gettext	\N	\N	\N	\N	\N
perl-MDK-Common	\N	\N	\N	\N	\N
perl-URI	\N	\N	\N	\N	\N
perl-URPM	\N	\N	\N	\N	\N
perl-XML-NamespaceSupport	\N	\N	\N	\N	\N
perl-XML-Parser	\N	\N	\N	\N	\N
perl-XML-SAX	\N	\N	\N	\N	\N
libstdc++5-devel	\N	\N	\N	\N	\N
zlib1-devel	\N	\N	\N	\N	\N
proftpd	\N	\N	\N	\N	\N
proftpd-anonymous	\N	\N	\N	\N	\N
pwdb-conf	\N	\N	\N	\N	\N
python-base	\N	\N	\N	\N	\N
apache2	\N	\N	\N	\N	\N
reiserfsprogs	\N	\N	\N	\N	\N
apache2-common	\N	\N	\N	\N	\N
apache2-mod_cache	\N	\N	\N	\N	\N
apache2-mod_dav	\N	\N	\N	\N	\N
rpm-helper	\N	\N	\N	\N	\N
rpmtools	\N	\N	\N	\N	\N
apache2-mod_deflate	\N	\N	\N	\N	\N
samba-server	\N	\N	\N	\N	\N
apache2-mod_disk_cache	\N	\N	\N	\N	\N
apache2-mod_perl	\N	\N	\N	\N	\N
apache2-mod_proxy	\N	\N	\N	\N	\N
apache2-mod_ssl	\N	\N	\N	\N	\N
strace	\N	\N	\N	\N	\N
apache2-mod_suexec	\N	\N	\N	\N	\N
apache2-modules	\N	\N	\N	\N	\N
apache-conf	\N	\N	\N	\N	\N
libapr0	\N	\N	\N	\N	\N
t1utils	\N	\N	\N	\N	\N
mod_perl-common	\N	\N	\N	\N	\N
perl-BSD-Resource	\N	\N	\N	\N	\N
perl-Devel-Symdump	\N	\N	\N	\N	\N
perl-DBI	\N	\N	\N	\N	\N
timezone	\N	\N	\N	\N	\N
ADVX-build	\N	\N	\N	\N	\N
apache2-devel	\N	\N	\N	\N	\N
apache2-mod_perl-devel	\N	\N	\N	\N	\N
usermode	\N	\N	\N	\N	\N
usermode-consoleonly	\N	\N	\N	\N	\N
libexpat0-devel	\N	\N	\N	\N	\N
libgdbm2-devel	\N	\N	\N	\N	\N
libopenssl0.9.7-devel	\N	\N	\N	\N	\N
gcc2.96	\N	\N	\N	\N	\N
gcc2.96-c++	\N	\N	\N	\N	\N
gcc2.96-cpp	\N	\N	\N	\N	\N
xclass-icons	\N	\N	\N	\N	\N
libstdc++2.10	\N	\N	\N	\N	\N
libstdc++2.10-devel	\N	\N	\N	\N	\N
perl-devel	\N	\N	\N	\N	\N
xinitrc	\N	\N	\N	\N	\N
zcip	\N	\N	\N	\N	\N
zlib1	\N	\N	\N	\N	\N
locales-am	\N	\N	\N	\N	\N
locales-ar	\N	\N	\N	\N	\N
locales-as	\N	\N	\N	\N	\N
locales-az	\N	\N	\N	\N	\N
locales-be	\N	\N	\N	\N	\N
locales-bg	\N	\N	\N	\N	\N
locales-bn	\N	\N	\N	\N	\N
locales-br	\N	\N	\N	\N	\N
locales-bs	\N	\N	\N	\N	\N
locales-ca	\N	\N	\N	\N	\N
locales-cs	\N	\N	\N	\N	\N
locales-cy	\N	\N	\N	\N	\N
locales-da	\N	\N	\N	\N	\N
locales-de	\N	\N	\N	\N	\N
locales-el	\N	\N	\N	\N	\N
perl-FCGI	\N	\N	\N	\N	\N
locales-eo	\N	\N	\N	\N	\N
locales-es	\N	\N	\N	\N	\N
locales-et	\N	\N	\N	\N	\N
locales-eu	\N	\N	\N	\N	\N
locales-fa	\N	\N	\N	\N	\N
locales-fi	\N	\N	\N	\N	\N
locales-fo	\N	\N	\N	\N	\N
locales-fr	\N	\N	\N	\N	\N
locales-ga	\N	\N	\N	\N	\N
locales-gd	\N	\N	\N	\N	\N
locales-gl	\N	\N	\N	\N	\N
locales-gv	\N	\N	\N	\N	\N
locales-he	\N	\N	\N	\N	\N
locales-hi	\N	\N	\N	\N	\N
locales-hr	\N	\N	\N	\N	\N
locales-hu	\N	\N	\N	\N	\N
locales-hy	\N	\N	\N	\N	\N
locales-id	\N	\N	\N	\N	\N
locales-is	\N	\N	\N	\N	\N
locales-it	\N	\N	\N	\N	\N
locales-iu	\N	\N	\N	\N	\N
locales-ja	\N	\N	\N	\N	\N
locales-ka	\N	\N	\N	\N	\N
locales-kl	\N	\N	\N	\N	\N
locales-kn	\N	\N	\N	\N	\N
locales-ko	\N	\N	\N	\N	\N
locales-kw	\N	\N	\N	\N	\N
locales-lo	\N	\N	\N	\N	\N
locales-lt	\N	\N	\N	\N	\N
locales-lv	\N	\N	\N	\N	\N
locales-mi	\N	\N	\N	\N	\N
locales-mk	\N	\N	\N	\N	\N
locales-ml	\N	\N	\N	\N	\N
locales-mn	\N	\N	\N	\N	\N
locales-mr	\N	\N	\N	\N	\N
locales-ms	\N	\N	\N	\N	\N
locales-mt	\N	\N	\N	\N	\N
locales-nl	\N	\N	\N	\N	\N
locales-no	\N	\N	\N	\N	\N
locales-oc	\N	\N	\N	\N	\N
locales-ph	\N	\N	\N	\N	\N
locales-pl	\N	\N	\N	\N	\N
locales-pp	\N	\N	\N	\N	\N
locales-pt	\N	\N	\N	\N	\N
locales-ro	\N	\N	\N	\N	\N
locales-ru	\N	\N	\N	\N	\N
locales-se	\N	\N	\N	\N	\N
locales-sk	\N	\N	\N	\N	\N
locales-sl	\N	\N	\N	\N	\N
locales-sq	\N	\N	\N	\N	\N
locales-sr	\N	\N	\N	\N	\N
locales-st	\N	\N	\N	\N	\N
locales-sv	\N	\N	\N	\N	\N
locales-ta	\N	\N	\N	\N	\N
locales-te	\N	\N	\N	\N	\N
locales-tg	\N	\N	\N	\N	\N
locales-th	\N	\N	\N	\N	\N
locales-tr	\N	\N	\N	\N	\N
locales-tt	\N	\N	\N	\N	\N
locales-uk	\N	\N	\N	\N	\N
locales-ur	\N	\N	\N	\N	\N
locales-uz	\N	\N	\N	\N	\N
locales-vi	\N	\N	\N	\N	\N
locales-wa	\N	\N	\N	\N	\N
locales-xh	\N	\N	\N	\N	\N
locales-yi	\N	\N	\N	\N	\N
locales-zh	\N	\N	\N	\N	\N
locales-zu	\N	\N	\N	\N	\N
aspell-br	\N	\N	\N	\N	\N
aspell-ca	\N	\N	\N	\N	\N
aspell-cy	\N	\N	\N	\N	\N
aspell-da	\N	\N	\N	\N	\N
aspell-de	\N	\N	\N	\N	\N
aspell-el	\N	\N	\N	\N	\N
aspell-en	\N	\N	\N	\N	\N
aspell-eo	\N	\N	\N	\N	\N
aspell-es	\N	\N	\N	\N	\N
aspell-fo	\N	\N	\N	\N	\N
aspell-fr	\N	\N	\N	\N	\N
aspell-ga	\N	\N	\N	\N	\N
aspell-hr	\N	\N	\N	\N	\N
aspell-hu	\N	\N	\N	\N	\N
aspell-it	\N	\N	\N	\N	\N
aspell-nl	\N	\N	\N	\N	\N
aspell-no	\N	\N	\N	\N	\N
aspell-pl	\N	\N	\N	\N	\N
aspell-pt	\N	\N	\N	\N	\N
aspell-ro	\N	\N	\N	\N	\N
aspell-ru	\N	\N	\N	\N	\N
aspell-sk	\N	\N	\N	\N	\N
aspell-sv	\N	\N	\N	\N	\N
aspell-uk	\N	\N	\N	\N	\N
libaspell15	\N	\N	\N	\N	\N
libaspell15-devel	\N	\N	\N	\N	\N
libbzip2_1-devel	\N	\N	\N	\N	\N
ftp-client-krb5	\N	\N	\N	\N	\N
perl-Compress-Zlib	\N	\N	\N	\N	\N
libcurl2-devel	\N	\N	\N	\N	\N
perl-Data-ShowTable	\N	\N	\N	\N	\N
perl-DateManip	\N	\N	\N	\N	\N
libdb3.3	\N	\N	\N	\N	\N
libdbtcl3.3	\N	\N	\N	\N	\N
libdbtcl4.1	\N	\N	\N	\N	\N
tcllib	\N	\N	\N	\N	\N
perl-DBD-Pg	\N	\N	\N	\N	\N
dev86-devel	\N	\N	\N	\N	\N
Digest	\N	\N	\N	\N	\N
gettext	\N	\N	\N	\N	\N
gettext-devel	\N	\N	\N	\N	\N
HDF	\N	\N	\N	\N	\N
hdf5	\N	\N	\N	\N	\N
HDF-util	\N	\N	\N	\N	\N
intltool	\N	\N	\N	\N	\N
libexif9	\N	\N	\N	\N	\N
libexif9-devel	\N	\N	\N	\N	\N
libfontconfig1-devel	\N	\N	\N	\N	\N
libfreetype6-devel	\N	\N	\N	\N	\N
libfreetype6-static-devel	\N	\N	\N	\N	\N
libgimpprint1	\N	\N	\N	\N	\N
libgimpprint1-devel	\N	\N	\N	\N	\N
libgmp3	\N	\N	\N	\N	\N
libgmp3-devel	\N	\N	\N	\N	\N
libhdf5_0	\N	\N	\N	\N	\N
libhdf5_0-devel	\N	\N	\N	\N	\N
libjpeg62-devel	\N	\N	\N	\N	\N
libjpeg62-static-devel	\N	\N	\N	\N	\N
libjpeg-progs	\N	\N	\N	\N	\N
liblcms1	\N	\N	\N	\N	\N
liblcms1-devel	\N	\N	\N	\N	\N
libMagick5.5.7	\N	\N	\N	\N	\N
libMagick5.5.7-devel	\N	\N	\N	\N	\N
libnetpbm9	\N	\N	\N	\N	\N
libnetpbm9-devel	\N	\N	\N	\N	\N
libnetpbm9-static-devel	\N	\N	\N	\N	\N
libpng3-devel	\N	\N	\N	\N	\N
libpng3-static-devel	\N	\N	\N	\N	\N
libpython2.3-devel	\N	\N	\N	\N	\N
libtiff3-devel	\N	\N	\N	\N	\N
libtiff3-static-devel	\N	\N	\N	\N	\N
libtiff-progs	\N	\N	\N	\N	\N
libwmf0.2_7	\N	\N	\N	\N	\N
libwmf0.2_7-devel	\N	\N	\N	\N	\N
libwmf	\N	\N	\N	\N	\N
libxfree86-devel	\N	\N	\N	\N	\N
libxfree86-static-devel	\N	\N	\N	\N	\N
perl-File-NCopy	\N	\N	\N	\N	\N
libxml2-python	\N	\N	\N	\N	\N
libxml2-utils	\N	\N	\N	\N	\N
libxpm4-devel	\N	\N	\N	\N	\N
libxslt1	\N	\N	\N	\N	\N
libxslt1-devel	\N	\N	\N	\N	\N
netpbm	\N	\N	\N	\N	\N
perl-Apache-Filter	\N	\N	\N	\N	\N
perl-Apache-Session	\N	\N	\N	\N	\N
perl-Apache-SSI	\N	\N	\N	\N	\N
perl-Array-RefElem	\N	\N	\N	\N	\N
perl-Authen-PAM	\N	\N	\N	\N	\N
perl-Authen-Smb	\N	\N	\N	\N	\N
perl-CGI-Fast	\N	\N	\N	\N	\N
perl-Convert-BER	\N	\N	\N	\N	\N
perl-Crypt-OpenSSL-DSA	\N	\N	\N	\N	\N
perl-Crypt-OpenSSL-RSA	\N	\N	\N	\N	\N
perl-Crypt-SSLeay	\N	\N	\N	\N	\N
perl-Curses	\N	\N	\N	\N	\N
perl-Data-Dump	\N	\N	\N	\N	\N
perl-Data-DumpXML	\N	\N	\N	\N	\N
bison	\N	\N	\N	\N	\N
perl-DBI-ProfileDumper-Apache	\N	\N	\N	\N	\N
perl-DBI-proxy	\N	\N	\N	\N	\N
perl-DBIx-Recordset	\N	\N	\N	\N	\N
perl-Digest-BubbleBabble	\N	\N	\N	\N	\N
perl-Digest-MD2	\N	\N	\N	\N	\N
perl-Digest-Nilsimsa	\N	\N	\N	\N	\N
perl-doc	\N	\N	\N	\N	\N
perl-ExtUtils-Depends	\N	\N	\N	\N	\N
perl-ExtUtils_F77	\N	\N	\N	\N	\N
libwv-1.0_0	\N	\N	\N	\N	\N
libwv-1.0_0-devel	\N	\N	\N	\N	\N
spamassassin	\N	\N	\N	\N	\N
perl-File-Slurp	\N	\N	\N	\N	\N
perl-File-Tail	\N	\N	\N	\N	\N
perl-Filter	\N	\N	\N	\N	\N
perlftlib	\N	\N	\N	\N	\N
perl-GD	\N	\N	\N	\N	\N
perl-HTML-Clean	\N	\N	\N	\N	\N
perl-HTML-FillInForm	\N	\N	\N	\N	\N
perl-HTML-SimpleParse	\N	\N	\N	\N	\N
perl-Image-Size	\N	\N	\N	\N	\N
perl-Inline	\N	\N	\N	\N	\N
perl-IO-stringy	\N	\N	\N	\N	\N
perl-libxml-enno	\N	\N	\N	\N	\N
perl-libxml-perl	\N	\N	\N	\N	\N
perl-Magick	\N	\N	\N	\N	\N
perl-Mail-Sender	\N	\N	\N	\N	\N
perl-Mail-Sendmail	\N	\N	\N	\N	\N
perl-Mail-SpamAssassin	\N	\N	\N	\N	\N
perl-MailTools	\N	\N	\N	\N	\N
perl-MDK-Common-devel	\N	\N	\N	\N	\N
perl-MIME-tools	\N	\N	\N	\N	\N
perl-MLDBM	\N	\N	\N	\N	\N
perl-MLDBM-Sync	\N	\N	\N	\N	\N
perl-Mon	\N	\N	\N	\N	\N
perl-MP3-Info	\N	\N	\N	\N	\N
perl-Msgcat	\N	\N	\N	\N	\N
perl-Mysql	\N	\N	\N	\N	\N
perl-Net-Daemon	\N	\N	\N	\N	\N
perl-Net-DNS	\N	\N	\N	\N	\N
perl-Net-DNS-SEC	\N	\N	\N	\N	\N
perl-Net-IPv4Addr	\N	\N	\N	\N	\N
perl-Net_SSLeay	\N	\N	\N	\N	\N
perl-Net-Telnet	\N	\N	\N	\N	\N
perl-Net-XWhois	\N	\N	\N	\N	\N
perl-Parse-RecDescent	\N	\N	\N	\N	\N
perl-Parse-Yapp	\N	\N	\N	\N	\N
perl-Period	\N	\N	\N	\N	\N
perl-PerlIO-gzip	\N	\N	\N	\N	\N
perl-PlRPC	\N	\N	\N	\N	\N
perl-Razor-Agent	\N	\N	\N	\N	\N
perl-String-ShellQuote	\N	\N	\N	\N	\N
perl-Term-Readline-Gnu	\N	\N	\N	\N	\N
perl-Text-Template	\N	\N	\N	\N	\N
perl-Tie-Cache	\N	\N	\N	\N	\N
perl-Tie-TextDir	\N	\N	\N	\N	\N
perl-TimeDate	\N	\N	\N	\N	\N
perl-Tk	\N	\N	\N	\N	\N
perl-Tk-devel	\N	\N	\N	\N	\N
perl-Tk-doc	\N	\N	\N	\N	\N
perl-XML-Encoding	\N	\N	\N	\N	\N
perl-XML-LibXML	\N	\N	\N	\N	\N
perl-XML-LibXML-Common	\N	\N	\N	\N	\N
perl-XML-LibXSLT	\N	\N	\N	\N	\N
perl-XML-RSS	\N	\N	\N	\N	\N
perl-XML-Simple	\N	\N	\N	\N	\N
perl-XML-Twig	\N	\N	\N	\N	\N
perl-XML-Writer	\N	\N	\N	\N	\N
perl-XML-XSLT	\N	\N	\N	\N	\N
libMesaGL1	\N	\N	\N	\N	\N
spamassassin-tools	\N	\N	\N	\N	\N
python-imaging	\N	\N	\N	\N	\N
pythonlib	\N	\N	\N	\N	\N
python-numeric	\N	\N	\N	\N	\N
python-numeric-devel	\N	\N	\N	\N	\N
python-utmp	\N	\N	\N	\N	\N
tetex-dvips	\N	\N	\N	\N	\N
tkcvs	\N	\N	\N	\N	\N
libelfutils1-devel	\N	\N	\N	\N	\N
libelfutils1-static-devel	\N	\N	\N	\N	\N
popt-devel	\N	\N	\N	\N	\N
rpm-devel	\N	\N	\N	\N	\N
libfftw2	\N	\N	\N	\N	\N
libfftw2-devel	\N	\N	\N	\N	\N
libgpm1-devel	\N	\N	\N	\N	\N
freetype2-tools	\N	\N	\N	\N	\N
gd-utils	\N	\N	\N	\N	\N
libgd2-devel	\N	\N	\N	\N	\N
libgd2-static-devel	\N	\N	\N	\N	\N
libncurses5-devel	\N	\N	\N	\N	\N
libglib1.2-devel	\N	\N	\N	\N	\N
pkgconfig	\N	\N	\N	\N	\N
glibc-i18ndata	\N	\N	\N	\N	\N
glibc-static-devel	\N	\N	\N	\N	\N
glibc-utils	\N	\N	\N	\N	\N
glib-gettextize	\N	\N	\N	\N	\N
libatk1.0_0-devel	\N	\N	\N	\N	\N
libgdk_pixbuf2.0_0-devel	\N	\N	\N	\N	\N
libglib2.0_0-devel	\N	\N	\N	\N	\N
libgtk+1.2	\N	\N	\N	\N	\N
libgtk+1.2-devel	\N	\N	\N	\N	\N
libgtk+2.0_0-devel	\N	\N	\N	\N	\N
libpango1.0_0-devel	\N	\N	\N	\N	\N
imap-utils	\N	\N	\N	\N	\N
libext2fs2-devel	\N	\N	\N	\N	\N
libkrb51-devel	\N	\N	\N	\N	\N
libltdl3	\N	\N	\N	\N	\N
libmcrypt4	\N	\N	\N	\N	\N
libmhash2	\N	\N	\N	\N	\N
libltdl3-devel	\N	\N	\N	\N	\N
libmcrypt4-devel	\N	\N	\N	\N	\N
libmhash2-devel	\N	\N	\N	\N	\N
libmng1	\N	\N	\N	\N	\N
libmng1-devel	\N	\N	\N	\N	\N
libmng1-static-devel	\N	\N	\N	\N	\N
libungif4	\N	\N	\N	\N	\N
libungif4-devel	\N	\N	\N	\N	\N
libungif4-static-devel	\N	\N	\N	\N	\N
ncurses-extraterms	\N	\N	\N	\N	\N
foomatic-db	\N	\N	\N	\N	\N
foomatic-db-engine	\N	\N	\N	\N	\N
foomatic-filters	\N	\N	\N	\N	\N
libgtkmm1.2	\N	\N	\N	\N	\N
libgtkmm1.2-devel	\N	\N	\N	\N	\N
libgtkmm1.2-static-devel	\N	\N	\N	\N	\N
libijs0	\N	\N	\N	\N	\N
libijs0-devel	\N	\N	\N	\N	\N
libsigc++1.0	\N	\N	\N	\N	\N
libsigc++1.0-devel	\N	\N	\N	\N	\N
libsigc++1.0-examples	\N	\N	\N	\N	\N
omni	\N	\N	\N	\N	\N
printer-filters	\N	\N	\N	\N	\N
psutils	\N	\N	\N	\N	\N
PDFlib	\N	\N	\N	\N	\N
libreadline4-devel	\N	\N	\N	\N	\N
libpcap0	\N	\N	\N	\N	\N
libpcap0-devel	\N	\N	\N	\N	\N
telnet-client-krb5	\N	\N	\N	\N	\N
telnet-server-krb5	\N	\N	\N	\N	\N
cdialog	\N	\N	\N	\N	\N
libnet-snmp50-devel	\N	\N	\N	\N	\N
libnet-snmp50-static-devel	\N	\N	\N	\N	\N
libMesaGLU1-devel	\N	\N	\N	\N	\N
libnas2	\N	\N	\N	\N	\N
libnas2-devel	\N	\N	\N	\N	\N
dhcp-client	\N	\N	\N	\N	\N
dhcp-common	\N	\N	\N	\N	\N
dhcp-server	\N	\N	\N	\N	\N
jetspeed	\N	\N	\N	\N	\N
ldetect-lst	\N	\N	\N	\N	\N
bcel	\N	\N	\N	\N	\N
bsf	\N	\N	\N	\N	\N
netprofile	\N	\N	\N	\N	\N
cactus	\N	\N	\N	\N	\N
hivemind	\N	\N	\N	\N	\N
jakarta-jcs	\N	\N	\N	\N	\N
jakarta-commons-attributes	\N	\N	\N	\N	\N
jakarta-commons-beanutils	\N	\N	\N	\N	\N
jakarta-commons-betwixt	\N	\N	\N	\N	\N
jakarta-commons-chain	\N	\N	\N	\N	\N
jakarta-commons-cli	\N	\N	\N	\N	\N
jakarta-commons-codec	\N	\N	\N	\N	\N
jakarta-commons-collections	\N	\N	\N	\N	\N
jakarta-commons-configuration	\N	\N	\N	\N	\N
jakarta-commons-daemon	\N	\N	\N	\N	\N
jakarta-commons-dbcp	\N	\N	\N	\N	\N
jakarta-commons-dbutils	\N	\N	\N	\N	\N
jakarta-commons-digester	\N	\N	\N	\N	\N
jakarta-commons-discovery	\N	\N	\N	\N	\N
jakarta-commons-el	\N	\N	\N	\N	\N
jakarta-commons-fileupload	\N	\N	\N	\N	\N
jakarta-commons-httpclient	\N	\N	\N	\N	\N
jakarta-commons-io	\N	\N	\N	\N	\N
jakarta-commons-jelly	\N	\N	\N	\N	\N
jakarta-commons-jexl	\N	\N	\N	\N	\N
jakarta-commons-lang	\N	\N	\N	\N	\N
jakarta-commons-jxpath	\N	\N	\N	\N	\N
jakarta-commons-launcher	\N	\N	\N	\N	\N
jakarta-commons-logging	\N	\N	\N	\N	\N
jakarta-commons-math	\N	\N	\N	\N	\N
jakarta-commons-modeler	\N	\N	\N	\N	\N
jakarta-commons-net	\N	\N	\N	\N	\N
jakarta-commons-pool	\N	\N	\N	\N	\N
jakarta-commons-primitives	\N	\N	\N	\N	\N
jakarta-commons-transaction	\N	\N	\N	\N	\N
jakarta-commons-validator	\N	\N	\N	\N	\N
jakarta-poi	\N	\N	\N	\N	\N
jakarta-tapestry	\N	\N	\N	\N	\N
jakarta-velocity	\N	\N	\N	\N	\N
jakarta-velocity-tools	\N	\N	\N	\N	\N
forrest	\N	\N	\N	\N	\N
lucene	\N	\N	\N	\N	\N
myfaces	\N	\N	\N	\N	\N
axis	\N	\N	\N	\N	\N
jaxme	\N	\N	\N	\N	\N
juddi	\N	\N	\N	\N	\N
wsif	\N	\N	\N	\N	\N
batik	\N	\N	\N	\N	\N
MySQL	\N	\N	\N	\N	\N
\.
