select "schema".add_column('master', 'master_processes', 'process_id',         'long',       false,  true, false, '', '1.0a100', '1.82.1');
select "schema".add_column('master', 'master_processes', 'id',                 'Identifier', false,  true, false, '', '1.83.0',  null);
select "schema".add_column('master', 'master_processes', 'connector_id',       'long',        true, false, false, '', '1.0a100', '1.82.1');
select "schema".add_column('master', 'master_processes', 'connectorId' ,       'Identifier',  true, false, false, '', '1.83.0',  null);
select "schema".add_column('master', 'master_processes', 'authenticated_user', 'username',    true, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'effective_user',     'username',    true, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'daemon_server',      'fkey',        true, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'host',               'ip_address', false, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'protocol',           'string',     false, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'aoserv_protocol',    'string',      true, false, false, '', '1.0a101', null);
select "schema".add_column('master', 'master_processes', 'is_secure',          'boolean',    false, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'connect_time',       'time',       false, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'use_count',          'long',       false, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'total_time',         'interval',   false, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'priority',           'int',        false, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'state',              'string',     false, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'command',            'string',      true, false, false, '', '1.0a100', null);
select "schema".add_column('master', 'master_processes', 'state_start_time',   'time',       false, false, false, '', '1.0a100', null);
