select "schema".add_column('credit_cards', 'pkey', 0, 'pkey', false, true, false, 'primary key value', '1.0a100', null);
select "schema".add_column('credit_cards', 'processor_id', 1, 'string', false, false, false, 'the unique ID of the merchant services provider that is storing the card number and expiration date', '1.29', null);
select "schema".add_column('credit_cards', 'accounting', 2, 'accounting', false, false, false, 'the accounting code for the card', '1.0a100', null);
select "schema".add_column('credit_cards', 'group_name', 3, 'string', true, false, false, 'any application-specific grouping', '1.29', null);
select "schema".add_column('credit_cards', 'card_number', 4, 'string', false, false, false, 'the encrypted card number', '1.0a100', '1.28');
select "schema".add_column('credit_cards', 'card_info', 5, 'string', false, false, false, 'the masked card number', '1.0a100', null);
select "schema".add_column('credit_cards', 'provider_unique_id', 6, 'string', false, false, false, 'the per-provider unique ID allowing use of this credit card for new transactions', '1.29', null);
select "schema".add_column('credit_cards', 'expiration_month', 7, 'string', false, false, false, 'the encrypted expiration month', '1.0a100', '1.28');
select "schema".add_column('credit_cards', 'expiration_year', 8, 'string', false, false, false, 'the encrypted expiration year', '1.0a100', '1.28');
select "schema".add_column('credit_cards', 'cardholder_name', 9, 'string', false, false, false, 'the encrypted card holders name', '1.0a100', '1.28');
select "schema".add_column('credit_cards', 'first_name', 10, 'string', false, false, false, 'the first name', '1.29', null);
select "schema".add_column('credit_cards', 'last_name', 11, 'string', false, false, false, 'the last name', '1.29', null);
select "schema".add_column('credit_cards', 'company_name', 12, 'string', true, false, false, 'the company name', '1.29', null);
select "schema".add_column('credit_cards', 'email', 13, 'email', true, false, false, 'the email address', '1.29', null);
select "schema".add_column('credit_cards', 'phone', 14, 'phone', true, false, false, 'the daytime phone number', '1.29', null);
select "schema".add_column('credit_cards', 'fax', 15, 'phone', true, false, false, 'the fax number', '1.29', null);
select "schema".add_column('credit_cards', 'customer_tax_id', 16, 'string', true, false, false, 'the social security number of employer identification number', '1.29', null);
select "schema".add_column('credit_cards', 'street_address', 17, 'string', false, false, false, 'the encrypted card holders street address', '1.0a100', '1.28');
select "schema".add_column('credit_cards', 'street_address1', 18, 'string', false, false, false, 'the first line of the street address', '1.29', null);
select "schema".add_column('credit_cards', 'street_address2', 19, 'string', true, false, false, 'the second line of the street address', '1.29', null);
select "schema".add_column('credit_cards', 'city',            20, 'city', false, false, false, 'the encrypted card holders city', '1.0a100', '1.28');
select "schema".add_column('credit_cards', 'city',            21, 'city', false, false, false, 'the card holders city', '1.29', '1.68');
select "schema".add_column('credit_cards', 'city',            22, 'string', false, false, false, 'the card holders city', '1.69', null);
select "schema".add_column('credit_cards', 'state',           23, 'state', true, false, false, 'the encrypted card holders state, null indicates out of country', '1.0a100', '1.28');
select "schema".add_column('credit_cards', 'state',           24, 'state', true, false, false, 'the card holders state', '1.29', '1.68');
select "schema".add_column('credit_cards', 'state',           25, 'string', true, false, false, 'the card holders state', '1.69', null);
select "schema".add_column('credit_cards', 'zip',             26, 'zip', true, false, false, 'the encrypted card holders zip code', '1.0a100', '1.28');
select "schema".add_column('credit_cards', 'postal_code',     27, 'zip', true, false, false, 'the card holders postal code', '1.29', '1.68');
select "schema".add_column('credit_cards', 'postal_code',     28, 'string', true, false, false, 'the card holders postal code', '1.69', null);
select "schema".add_column('credit_cards', 'country_code',    29, 'country', false, false, false, 'the two-character country code', '1.29', '1.68');
select "schema".add_column('credit_cards', 'country_code',    30, 'string', false, false, false, 'the two-character country code', '1.69', null);
select "schema".add_column('credit_cards', 'created',         31, 'time', false, false, false, 'the time the card was added to the database', '1.0a100', null);
select "schema".add_column('credit_cards', 'created_by',      32, 'username', false, false, false, 'the business_administrator who added the card to the database', '1.0a100', null);
select "schema".add_column('credit_cards', 'principal_name',  33, 'string', true, false, false, 'the application-provided principal name of the person added the card to the database', '1.29', null);
select "schema".add_column('credit_cards', 'use_monthly',     34, 'boolean', false, false, false, 'if <code>true</code> the card will be used monthly', '1.0a100', null);
select "schema".add_column('credit_cards', 'active',          35, 'boolean', false, false, false, 'if <code>true</code> the card is currently active', '1.0a100', null);
select "schema".add_column('credit_cards', 'deactivated_on',                   36, 'time', true, false, false, 'the time the card was deactivated', '1.0a100', null);
select "schema".add_column('credit_cards', 'deactivate_reason',                37, 'string', true, false, false, 'the reason the card was deactivated', '1.0a100', null);
select "schema".add_column('credit_cards', 'priority',                         38, 'int', false, false, false, 'the priority of the card, lower is used first', '1.0a100', '1.28');
select "schema".add_column('credit_cards', 'description',                      39, 'string', true, false, false, 'any comment or description', '1.0a100', null);
select "schema".add_column('credit_cards', 'encrypted_card_number',            40, 'string', true, false, false, 'the card number stored encrypted', '1.31', null);
select "schema".add_column('credit_cards', 'encryption_card_number_from',      41, 'fkey', true, false, false, 'the from that was used for card number encryption', '1.31', null);
select "schema".add_column('credit_cards', 'encryption_card_number_recipient', 42, 'fkey', true, false, false, 'the recipient that was used for card number encryption', '1.31', null);
select "schema".add_column('credit_cards', 'encrypted_expiration',             43, 'string', true, false, false, 'the expiration stored encrypted', '1.31', null);
select "schema".add_column('credit_cards', 'encryption_expiration_from',       44, 'fkey', true, false, false, 'the from that was used for expiration encryption', '1.31', null);
select "schema".add_column('credit_cards', 'encryption_expiration_recipient',  45, 'fkey', true, false, false, 'the recipient that was used for expiration encryption', '1.31', null);
