select "schema".add_column('failover_mysql_replications', 'pkey', 0, 'pkey', false, true, false, 'a generated, unique id', '1.28', null);
select "schema".add_column('failover_mysql_replications', 'ao_server', 1, 'fkey', true, false, false, 'the ao_server the receives the replication', '1.59', null);
select "schema".add_column('failover_mysql_replications', 'replication', 2, 'fkey', false, false, false, 'the failover server that receives the replication', '1.28', '1.58');
select "schema".add_column('failover_mysql_replications', 'replication', 3, 'fkey', true, false, false, 'the failover server that receives the replication', '1.59', null);
select "schema".add_column('failover_mysql_replications', 'mysql_server', 4, 'fkey', false, false, false, 'the MySQL Server that is being replicated', '1.28', null);
select "schema".add_column('failover_mysql_replications', 'monitoring_seconds_behind_low', 5, 'int', true, false, false, 'the seconds behind where will trigger low alert level', '1.56', null);
select "schema".add_column('failover_mysql_replications', 'monitoring_seconds_behind_medium', 6, 'int', true, false, false, 'the seconds behind where will trigger medium alert level', '1.56', null);
select "schema".add_column('failover_mysql_replications', 'monitoring_seconds_behind_high', 7, 'int', true, false, false, 'the seconds behind where will trigger high alert level', '1.56', null);
select "schema".add_column('failover_mysql_replications', 'monitoring_seconds_behind_critical', 8, 'int', true, false, false, 'the seconds behind where will trigger critical alert level', '1.56', null);
select "schema".add_column('failover_mysql_replications', 'max_alert_level', 9, 'string', false, false, false, 'the maximum alert level for all monitoring of this slave', '1.74', null);
