select "schema".add_column('failover_file_replications', 'pkey', 0, 'pkey', false, true, false, 'a generated, unique id', '1.0a100', null);
select "schema".add_column('failover_file_replications', 'from_server', 1, 'fkey', false, false, false, 'the pkey of the server that the files are coming from', '1.0a100', '1.30');
select "schema".add_column('failover_file_replications', 'server', 2, 'fkey', false, false, false, 'the pkey of the server that the files are coming from', '1.31', null);
select "schema".add_column('failover_file_replications', 'to_server', 3, 'fkey', false, false, false, 'the pkey of the server that files are being sent to', '1.0a100', '1.30');
select "schema".add_column('failover_file_replications', 'backup_partition', 4, 'fkey', false, false, false, 'the pkey of the backup partition that the files are going to', '1.31', null);
select "schema".add_column('failover_file_replications', 'max_bit_rate', 5, 'int', true, false, false, 'the maximum bit rate for files being replicated', '1.0a105', '1.61');
select "schema".add_column('failover_file_replications', 'max_bit_rate', 6, 'long', true, false, false, 'the maximum bit rate for files being replicated', '1.61', null);
select "schema".add_column('failover_file_replications', 'last_start_time', 7, 'time', true, false, false, 'the last time the replication was started or null if never ran', '1.0a100', '1.30');
select "schema".add_column('failover_file_replications', 'use_compression', 8, 'boolean', false, false, false, 'when compression is enabled, chunk mode is used on mirroring, resulting in more CPU and disk, but less bandwidth', '1.9', null);
select "schema".add_column('failover_file_replications', 'retention', 9, 'short', false, false, false, 'the number of days backups will be kept', '1.13', null);
select "schema".add_column('failover_file_replications', 'connect_address', 10, 'string', true, false, false, 'an address that overrides regular AOServ connections for failovers', '1.14', '1.68');
select "schema".add_column('failover_file_replications', 'connect_address', 11, 'string', true, false, false, 'an address or hostname that overrides regular AOServ connections for failovers', '1.69', null);
select "schema".add_column('failover_file_replications', 'connect_from', 12, 'string', true, false, false, 'an address that overrides regular AOServ connection source addresses for failovers', '1.22', '1.68');
select "schema".add_column('failover_file_replications', 'connect_from', 13, 'ip_address', true, false, false, 'an address that overrides regular AOServ connection source addresses for failovers', '1.69', null);
select "schema".add_column('failover_file_replications', 'enabled', 14, 'boolean', false, false, false, 'the enabled flag for failovers', '1.15', null);
select "schema".add_column('failover_file_replications', 'to_path', 15, 'string', false, false, false, 'the destination path for the replication', '1.17','1.30');
select "schema".add_column('failover_file_replications', 'chunk_always', 16, 'boolean', false, false, false, 'when true chunking will always be performed (mtime+length will not be considered a sufficient match)', '1.17', '1.30');
select "schema".add_column('failover_file_replications', 'quota_gid', 17, 'int', true, false, false, 'the gid used on the backup_partition for quota reports, required if backup_partitions quotas are enabled, not allowed otherwise', '1.31', '1.68');
select "schema".add_column('failover_file_replications', 'quota_gid', 18, 'fkey', true, false, false, 'the gid used on the backup_partition for quota reports, required if backup_partitions quotas are enabled, not allowed otherwise', '1.69', '1.80');
select "schema".add_column('failover_file_replications', 'quota_gid', 19, 'linux_id', true, false, false, 'the gid used on the backup_partition for quota reports, required if backup_partitions quotas are enabled, not allowed otherwise', '1.80.0', null);
