select "schema".add_column('httpd_site_bind_headers', 'pkey',             0, 'pkey',    false,  true, false, 'a generated primary key',                     '1.81.15', null);
select "schema".add_column('httpd_site_bind_headers', 'httpd_site_bind',  1, 'fkey',    false, false, false, 'the site bind that is being referenced',      '1.81.15', null);
select "schema".add_column('httpd_site_bind_headers', 'sort_order',       2, 'short',   false, false, false, 'the per-bind unique sort ordering',           '1.81.15', null);
select "schema".add_column('httpd_site_bind_headers', 'type',             3, 'string',  false, false, false, 'the type of header, either "Header" or "RequestHeader"', '1.81.15', null);
select "schema".add_column('httpd_site_bind_headers', 'always',           4, 'boolean', false, false, false, 'the condition is either "onsuccess" (default, can be omitted) or "always"', '1.81.15', null);
select "schema".add_column('httpd_site_bind_headers', 'action',           5, 'string',  false, false, false, 'the action to be performed',                  '1.81.15', null);
select "schema".add_column('httpd_site_bind_headers', 'header',           6, 'string',  false, false, false, 'the header name, without any final colon',    '1.81.15', null);
select "schema".add_column('httpd_site_bind_headers', 'value',            7, 'string',   true, false, false, 'the header value, not used for all actions',  '1.81.15', null);
select "schema".add_column('httpd_site_bind_headers', 'replacement',      8, 'string',   true, false, false, 'the replacement value, only used for "edit" and "edit*"', '1.81.15', null);
select "schema".add_column('httpd_site_bind_headers', 'when',             9, 'string',   true, false, false, 'optional control over when is this header directive is applied', '1.81.15', null);
select "schema".add_column('httpd_site_bind_headers', 'comment',         10, 'string',   true, false, false, 'an optional comment describing the redirect', '1.81.15', null);
