select "schema".add_column('package_definitions', 'pkey', 0, 'pkey', false, true, false, 'the unique ID of the package definition', '1.0a123', null);
select "schema".add_column('package_definitions', 'accounting', 1, 'accounting', false, false, false, 'the accounting code of the seller/reseller that supports this package', '1.0a123', '1.43');
select "schema".add_column('package_definitions', 'brand', 2, 'accounting', false, false, false, 'the brand of the seller/reseller that supports this package', '1.44', '1.44');
select "schema".add_column('package_definitions', 'accounting', 3, 'accounting', false, false, false, 'the accounting code of the seller/reseller that supports this package', '1.45', null);
select "schema".add_column('package_definitions', 'category', 4, 'string', false, false, false, 'the package category', '1.0a123', null);
select "schema".add_column('package_definitions', 'name', 5, 'string', false, false, false, 'the name of the package', '1.0a123', null);
select "schema".add_column('package_definitions', 'version', 6, 'string', false, false, false, 'the unique version of this package', '1.0a123', null);
select "schema".add_column('package_definitions', 'display', 7, 'string', false, false, false, 'a short description for display use', '1.0a123', null);
select "schema".add_column('package_definitions', 'description', 8, 'string', false, false, false, 'a description of the package definition', '1.0a123', null);
select "schema".add_column('package_definitions', 'setup_fee', 9, 'decimal_2', true, false, false, 'the setup fee for this package definition', '1.0a123', null);
select "schema".add_column('package_definitions', 'setup_fee_transaction_type', 10, 'string', true, false, false, '', '1.0a123', null);
select "schema".add_column('package_definitions', 'monthly_rate', 11, 'decimal_2', true, false, false, 'the default monthly charge for this package', '1.0a123', null);
select "schema".add_column('package_definitions', 'monthly_rate_transaction_type', 12, 'string', true, false, false, '', '1.0a123', null);
select "schema".add_column('package_definitions', 'active', 13, 'boolean', false, false, false, 'allows new accounts for this package', '1.0a123', null);
select "schema".add_column('package_definitions', 'approved', 14, 'boolean', false, false, false, 'once approved a definition may be used for packages, but may not be modified', '1.0a123', null);
