select "schema".add_column('signup_requests', 'pkey', 0, 'pkey', false, true, false, 'a generate unique id', '1.23', null);
select "schema".add_column('signup_requests', 'accounting', 1, 'accounting', false, false, false, 'the accounting code of the parent business for the new account', '1.23', '1.43');
select "schema".add_column('signup_requests', 'brand', 2, 'accounting', false, false, false, 'the brand of the parent business for the new account', '1.44', null);
select "schema".add_column('signup_requests', 'time', 3, 'time', false, false, false, 'the time the request was added', '1.23', null);
select "schema".add_column('signup_requests', 'ip_address', 4, 'ip_address', false, false, false, 'the IP address of the user who signed-up', '1.23', null);
select "schema".add_column('signup_requests', 'package_definition', 5, 'fkey', false, false, false, 'the pkey of the Package Definition requested', '1.23', null);
select "schema".add_column('signup_requests', 'business_name', 6, 'string', false, false, false, 'the name of the business', '1.23', null);
select "schema".add_column('signup_requests', 'business_phone', 7, 'string', false, false, false, 'the phone number of the business', '1.23', '1.68');
select "schema".add_column('signup_requests', 'business_phone', 8, 'phone', false, false, false, 'the phone number of the business', '1.69', null);
select "schema".add_column('signup_requests', 'business_fax', 9, 'string', true, false, false, 'the fax number of the business', '1.23', '1.68');
select "schema".add_column('signup_requests', 'business_fax', 10, 'phone', true, false, false, 'the fax number of the business', '1.69', null);
select "schema".add_column('signup_requests', 'business_address1', 11, 'string', false, false, false, 'the street address of the business', '1.23', null);
select "schema".add_column('signup_requests', 'business_address2', 12, 'string', true, false, false, 'the street address of the business', '1.23', null);
select "schema".add_column('signup_requests', 'business_city',     13, 'city', false, false, false, 'the city  of the business', '1.23', '1.68');
select "schema".add_column('signup_requests', 'business_city',     14, 'string', false, false, false, 'the city  of the business', '1.69', null);
select "schema".add_column('signup_requests', 'business_state',    15, 'state', true, false, false, 'the state or providence of the business', '1.23', '1.68');
select "schema".add_column('signup_requests', 'business_state',    16, 'string', true, false, false, 'the state or providence of the business', '1.69', null);
select "schema".add_column('signup_requests', 'business_country',  17, 'country', false, false, false, 'the two-character country code of the business', '1.23', '1.68');
select "schema".add_column('signup_requests', 'business_country',  18, 'string', false, false, false, 'the two-character country code of the business', '1.69', null);
select "schema".add_column('signup_requests', 'business_zip',      19, 'zip', true, false, false, 'the zip code of the business', '1.23', '1.68');
select "schema".add_column('signup_requests', 'business_zip',      20, 'string', true, false, false, 'the zip code of the business', '1.69', null);
select "schema".add_column('signup_requests', 'ba_name',           21, 'string', false, false, false, 'the administrator''s name', '1.23', null);
select "schema".add_column('signup_requests', 'ba_title',          22, 'string', true, false, false, 'the administrator''s title', '1.23', null);
select "schema".add_column('signup_requests', 'ba_work_phone',     23, 'string', false, false, false, 'the administrator''s work phone', '1.23', '1.68');
select "schema".add_column('signup_requests', 'ba_work_phone',     24, 'string', false, false, false, 'the administrator''s work phone', '1.69', null);
select "schema".add_column('signup_requests', 'ba_cell_phone',     25, 'string', true, false, false, 'the administrator''s cell phone', '1.23', '1.68');
select "schema".add_column('signup_requests', 'ba_cell_phone',     26, 'string', true, false, false, 'the administrator''s cell phone', '1.69', null);
select "schema".add_column('signup_requests', 'ba_home_phone',     27, 'string', true, false, false, 'the administrator''s home phone', '1.23', '1.68');
select "schema".add_column('signup_requests', 'ba_home_phone',     28, 'string', true, false, false, 'the administrator''s home phone', '1.69', null);
select "schema".add_column('signup_requests', 'ba_fax',            29, 'string', true, false, false, 'the administrator''s fax number', '1.23', '1.68');
select "schema".add_column('signup_requests', 'ba_fax',            30, 'string', true, false, false, 'the administrator''s fax number', '1.69', null);
select "schema".add_column('signup_requests', 'ba_email',          31, 'email', false, false, false, 'the administrator''s email address', '1.23', null);
select "schema".add_column('signup_requests', 'ba_address1',       32, 'string', true, false, false, 'the street address of the administrator', '1.23', null);
select "schema".add_column('signup_requests', 'ba_address2',       33, 'string', true, false, false, 'the street address of the administrator', '1.23', null);
select "schema".add_column('signup_requests', 'ba_city',           34, 'city', true, false, false, 'the city of the administrator', '1.23', '1.68');
select "schema".add_column('signup_requests', 'ba_city',           35, 'string', true, false, false, 'the city of the administrator', '1.69', null);
select "schema".add_column('signup_requests', 'ba_state',          36, 'state', true, false, false, 'the state or providence of the administrator', '1.23', '1.68');
select "schema".add_column('signup_requests', 'ba_state',          37, 'string', true, false, false, 'the state or providence of the administrator', '1.69', null);
select "schema".add_column('signup_requests', 'ba_country',        38, 'country', true, false, false, 'the two-character country code of the administrator', '1.23', '1.68');
select "schema".add_column('signup_requests', 'ba_country',        39, 'string', true, false, false, 'the two-character country code of the administrator', '1.69', null);
select "schema".add_column('signup_requests', 'ba_zip',            40, 'zip', true, false, false, 'the zip code of the administrator', '1.23', '1.68');
select "schema".add_column('signup_requests', 'ba_zip',            41, 'string', true, false, false, 'the zip code of the administrator', '1.69', null);
select "schema".add_column('signup_requests', 'ba_username',       42, 'username', false, false, false, 'the username of the administrator', '1.23', null);
select "schema".add_column('signup_requests', 'billing_contact',   43, 'string', false, false, false, 'the name of the billing contact', '1.23', null);
select "schema".add_column('signup_requests', 'billing_email',        44, 'email', false, false, false, 'the email address of the billing contact', '1.23', null);
select "schema".add_column('signup_requests', 'billing_use_monthly',  45, 'boolean', false, false, false, 'if true, the credit_card will be used every month automatically', '1.23', null);
select "schema".add_column('signup_requests', 'billing_pay_one_year', 46, 'boolean', false, false, false, 'if true, one-year in advance will be charged to the credit_card and they will receive a credit for a free month', '1.23', null);
select "schema".add_column('signup_requests', 'encrypted_data',       47, 'string', false, false, false, 'the credit card details and password are stored encrypted', '1.23', null);
select "schema".add_column('signup_requests', 'encryption_from',      48, 'fkey', false, false, false, 'the from that was used for encryption', '1.31', null);
select "schema".add_column('signup_requests', 'encryption_key',       49, 'fkey', false, false, false, 'the recipient that was used for encryption', '1.23', '1.30');
select "schema".add_column('signup_requests', 'encryption_recipient', 50, 'fkey', false, false, false, 'the recipient that was used for encryption', '1.31', null);
select "schema".add_column('signup_requests', 'completed_by',         51, 'username', true, false, false, 'the username of the person who completed this sign-up request', '1.23', null);
select "schema".add_column('signup_requests', 'completed_time',       52, 'time', true, false, false, 'the time this request was completed', '1.23', null);
