select "schema".add_foreign_key('public', 'transactions', 'accounting',              'public',     'businesses',               'accounting',  '1.0a100', null);
select "schema".add_foreign_key('public', 'transactions', 'source_accounting',       'public',     'businesses',               'accounting',  '1.0a100', null);
select "schema".add_foreign_key('public', 'transactions', 'username',                'public',     'business_administrators',  'username',    '1.0a100', null);
select "schema".add_foreign_key('public', 'transactions', 'type',                    'public',     'rates',                    'name',        '1.0a100', '1.0a122');
select "schema".add_foreign_key('public', 'transactions', 'type',                    'public',     'transaction_types',        'name',        '1.0a123', null);
select "schema".add_foreign_key('public', 'transactions', 'payment_type',            'public',     'payment_types',            'name',        '1.0a100', null);
select "schema".add_foreign_key('public', 'transactions', 'merchant_account',        'accounting', 'merchant_accounts',        'name',        '1.0a100', '1.28');
select "schema".add_foreign_key('public', 'transactions', 'processor',               'public',     'credit_card_processors',   'provider_id', '1.29',    null);
select "schema".add_foreign_key('public', 'transactions', 'credit_card_transaction', 'public',     'credit_card_transactions', 'pkey',        '1.29',    null);
