select "schema".add_column('distribution.management', 'distro_files', 'pkey',                     'pkey',       false,  true, false, 'the unique pkey', '1.0a108', null);
select "schema".add_column('distribution.management', 'distro_files', 'operating_system_version', 'fkey',       false, false, false, 'the OS version that contains the file', '1.0a108', null);
select "schema".add_column('distribution.management', 'distro_files', 'path',                     'path',       false,  true, false, 'the full path to the file', '1.0a100', '1.0a107');
select "schema".add_column('distribution.management', 'distro_files', 'path',                     'path',       false, false, false, 'the full path to the file', '1.0a108', null);
select "schema".add_column('distribution.management', 'distro_files', 'optional',                 'boolean',    false, false, false, 'if the file is optional', '1.0a100', null);
select "schema".add_column('distribution.management', 'distro_files', 'type',                     'string',     false, false, false, 'the type of file', '1.0a100', null);
select "schema".add_column('distribution.management', 'distro_files', 'mode',                     'octal_long', false, false, false, 'the mode (including file type bits)', '1.0a100', null);
select "schema".add_column('distribution.management', 'distro_files', 'linux_account',            'username',   false, false, false, 'the owner of the file', '1.0a100', null);
select "schema".add_column('distribution.management', 'distro_files', 'linux_group',              'string',     false, false, false, 'the group of the file', '1.0a100', '1.80');
select "schema".add_column('distribution.management', 'distro_files', 'linux_group',              'group_id',   false, false, false, 'the group of the file', '1.80.0', null);
select "schema".add_column('distribution.management', 'distro_files', 'size',                     'long',        true, false, false, 'the length of the file', '1.0a100', null);
select "schema".add_column('distribution.management', 'distro_files', 'file_md5',                 'string',      true, false, false, 'the md5 hash if is a regular file', '1.0a100', '1.0a104');
select "schema".add_column('distribution.management', 'distro_files', 'file_md5_hi',              'long',        true, false, false, 'the md5 hash if is a regular file', '1.0a105', '1.79');
select "schema".add_column('distribution.management', 'distro_files', 'file_md5_lo',              'long',        true, false, false, 'the md5 hash if is a regular file', '1.0a105', '1.79');
select "schema".add_column('distribution.management', 'distro_files', 'file_sha256_0',            'long',        true, false, false, 'the first 64 bits of SHA-256 hash if is a regular file', '1.80', null);
select "schema".add_column('distribution.management', 'distro_files', 'file_sha256_1',            'long',        true, false, false, 'the second 64 bits of SHA-256 hash if is a regular file', '1.80', null);
select "schema".add_column('distribution.management', 'distro_files', 'file_sha256_2',            'long',        true, false, false, 'the third 64 bits of SHA-256 hash if is a regular file', '1.80', null);
select "schema".add_column('distribution.management', 'distro_files', 'file_sha256_3',            'long',        true, false, false, 'the fourth 64 bits of SHA-256 hash if is a regular file', '1.80', null);
select "schema".add_column('distribution.management', 'distro_files', 'symlink_target',           'string',      true, false, false, 'the target if is a symbolic link', '1.0a100', null);
