select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'pkey', 0, 'pkey', false, true, false, 'a generated unique key', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'tomcat_site', 1, 'fkey', false, false, false, 'the site this context is part of', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'class_name', 2, 'string', true, false, false, 'the className attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'cookies', 3, 'boolean', false, false, false, 'the cookies attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'cross_context', 4, 'boolean', false, false, false, 'the crossContext attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'doc_base', 5, 'string', false, false, false, 'the docBase attribute', '1.0a100', '1.80');
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'doc_base', 6, 'path', false, false, false, 'the docBase attribute', '1.80.0', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'override', 7, 'boolean', false, false, false, 'the override attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'path', 8, 'string', false, false, false, 'the path attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'privileged', 9, 'boolean', false, false, false, 'the privileged attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'reloadable', 10, 'boolean', false, false, false, 'the reloadable attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'use_naming', 11, 'boolean', false, false, false, 'the useNaming attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'wrapper_class', 12, 'string', true, false, false, 'the wrapperClass attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'debug', 13, 'int', false, false, false, 'the debug attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'work_dir', 14, 'path', true, false, false, 'the workDir attribute', '1.0a100', null);
select "schema".add_column('httpd', 'httpd_tomcat_contexts', 'server_xml_configured', 15, 'boolean', false, false, false, 'flag setting if the context is written into conf/server.xml', '1.81.3', null);
