#!/bin/bash
#
# aoserv-schema - Database schema for the AOServ Platform.
# Copyright (C) 2000-2006, 2008, 2018, 2020  AO Industries, Inc.
#     support@aoindustries.com
#     7262 Bull Pen Cir
#     Mobile, AL 36695
#
# This file is part of aoserv-schema.
#
# aoserv-schema is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# aoserv-schema is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with aoserv-schema.  If not, see <http://www.gnu.org/licenses/>.
#

DIR="${BASH_SOURCE%/*}"
DB_NAME="$1"
if [ "$DB_NAME" = "" ]
then
	echo "usage: $0 {aoweb|aoserv-master/public}" 2>&1
	exit 1
fi
grep -h -i "create table" "${DIR}/${DB_NAME}"/*.sql | cut -c14- | cut -d\  -f1 | while read TABLE_NAME
do
	echo "drop table ${TABLE_NAME} cascade;"
done
grep -h -i "create sequence" "${DIR}/${DB_NAME}"/*.sql | cut -c17- | cut -d\  -f1 | while read SEQUENCE_NAME
do
	echo "drop sequence ${SEQUENCE_NAME};"
done
