#!/bin/bash
#
# aoserv-schema - Database schema for the AOServ Platform.
# Copyright (C) 2000-2006, 2018, 2020, 2022  AO Industries, Inc.
#     support@aoindustries.com
#     7262 Bull Pen Cir
#     Mobile, AL 36695
#
# This file is part of aoserv-schema.
#
# aoserv-schema is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# aoserv-schema is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with aoserv-schema.  If not, see <https://www.gnu.org/licenses/>.
#

shopt -s nullglob

DIR="${BASH_SOURCE%/*}"
echo "BEGIN;"
# 5
cat "${DIR}/aoserv-master/schema/ForeignKey-data5-pre.sql"
  # 4
  cat "${DIR}/aoserv-master/schema/Column-data4-pre.sql"
  cat "${DIR}/aoserv-master/aosh/Command-data4-pre.sql"
    # 3
    cat "${DIR}/aoserv-master/schema/Table-data3-pre.sql"
      # 2
      cat "${DIR}/aoserv-master/schema/Type-data2-pre.sql"
      cat "${DIR}/aoserv-master/schema/Schema-data2-pre.sql"
        # 1
        cat "${DIR}/aoserv-master/schema/AoservProtocol-data1-pre.sql"
        cat "${DIR}/aoserv-master/schema/AoservProtocol-data1.sql"
        cat "${DIR}/aoserv-master/schema/AoservProtocol-data1-post.sql"
      # 2
      cat "${DIR}/aoserv-master/schema/Schema-data2.sql"
      cat "${DIR}/aoserv-master/schema/Schema-data2-post.sql"
      cat "${DIR}/aoserv-master/schema/Type-data2.sql"
      cat "${DIR}/aoserv-master/schema/Type-data2-post.sql"
    # 3
    cat "${DIR}/aoserv-master/schema/Table-data3.sql"
    cat "${DIR}/aoserv-master/schema/Table-data3-post.sql"
  # 4
  cat "${DIR}/aoserv-master/aosh/Command-data4.sql"
  for SQL in \
      "${DIR}/aoserv-master"/*/*-aosh.Command.sql \
      "${DIR}/aoserv-master"/*/*/*-aosh.Command.sql \
      "${DIR}/aoserv-master"/*/*/*/*-aosh.Command.sql
  do
    echo "\echo $SQL"
    cat "$SQL"
  done
  cat "${DIR}/aoserv-master/aosh/Command-data4-post.sql"
  for SQL in \
      "${DIR}/aoserv-master"/*/*-schema.Column.sql \
      "${DIR}/aoserv-master"/*/*/*-schema.Column.sql \
      "${DIR}/aoserv-master"/*/*/*/*-schema.Column.sql
  do
    echo "\echo $SQL"
    cat "$SQL"
  done
  cat "${DIR}/aoserv-master/schema/Column-data4-post.sql"
# 5
for SQL in \
  "${DIR}/aoserv-master"/*/*-schema.ForeignKey.sql \
  "${DIR}/aoserv-master"/*/*/*-schema.ForeignKey.sql \
  "${DIR}/aoserv-master"/*/*/*/*-schema.ForeignKey.sql
do
  echo "\echo $SQL"
  cat "$SQL"
done
cat "${DIR}/aoserv-master/schema/ForeignKey-data5-post.sql"
# Verify
cat "${DIR}/aoserv-master/schema/Schema-verify.sql"
cat "${DIR}/aoserv-master/schema/Table-verify.sql"
echo "COMMIT;"
