#!/bin/bash
#
# aoserv-schema - Database schema for the AOServ Platform.
# Copyright (C) 2000-2006, 2018, 2020  AO Industries, Inc.
#     support@aoindustries.com
#     7262 Bull Pen Cir
#     Mobile, AL 36695
#
# This file is part of aoserv-schema.
#
# aoserv-schema is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# aoserv-schema is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with aoserv-schema.  If not, see <http://www.gnu.org/licenses/>.
#

shopt -s nullglob

DIR="${BASH_SOURCE%/*}"
echo "BEGIN;"
# 5
cat "${DIR}/aoindustries/schema/ForeignKey-data5-pre.sql"
	# 4
	cat "${DIR}/aoindustries/schema/Column-data4-pre.sql"
	cat "${DIR}/aoindustries/aosh/Command-data4-pre.sql"
		# 3
		cat "${DIR}/aoindustries/schema/Table-data3-pre.sql"
			# 2
			cat "${DIR}/aoindustries/schema/Type-data2-pre.sql"
			cat "${DIR}/aoindustries/schema/Schema-data2-pre.sql"
				# 1
				cat "${DIR}/aoindustries/schema/AoservProtocol-data1-pre.sql"
				cat "${DIR}/aoindustries/schema/AoservProtocol-data1.sql"
				cat "${DIR}/aoindustries/schema/AoservProtocol-data1-post.sql"
			# 2
			cat "${DIR}/aoindustries/schema/Schema-data2.sql"
			cat "${DIR}/aoindustries/schema/Schema-data2-post.sql"
			cat "${DIR}/aoindustries/schema/Type-data2.sql"
			cat "${DIR}/aoindustries/schema/Type-data2-post.sql"
		# 3
		cat "${DIR}/aoindustries/schema/Table-data3.sql"
		cat "${DIR}/aoindustries/schema/Table-data3-post.sql"
	# 4
	cat "${DIR}/aoindustries/aosh/Command-data4.sql"
	for SQL in \
      "${DIR}/aoindustries"/*/*-aosh.Command.sql \
      "${DIR}/aoindustries"/*/*/*-aosh.Command.sql \
      "${DIR}/aoindustries"/*/*/*/*-aosh.Command.sql
	do
		echo "\echo $SQL"
		cat "$SQL"
	done
	cat "${DIR}/aoindustries/aosh/Command-data4-post.sql"
	for SQL in \
      "${DIR}/aoindustries"/*/*-schema.Column.sql \
      "${DIR}/aoindustries"/*/*/*-schema.Column.sql \
      "${DIR}/aoindustries"/*/*/*/*-schema.Column.sql
	do
		echo "\echo $SQL"
		cat "$SQL"
	done
	cat "${DIR}/aoindustries/schema/Column-data4-post.sql"
# 5
for SQL in \
  "${DIR}/aoindustries"/*/*-schema.ForeignKey.sql \
  "${DIR}/aoindustries"/*/*/*-schema.ForeignKey.sql \
  "${DIR}/aoindustries"/*/*/*/*-schema.ForeignKey.sql
do
	echo "\echo $SQL"
	cat "$SQL"
done
cat "${DIR}/aoindustries/schema/ForeignKey-data5-post.sql"
# Verify
cat "${DIR}/aoindustries/schema/Schema-verify.sql"
cat "${DIR}/aoindustries/schema/Table-verify.sql"
echo "COMMIT;"
