select "schema".add_column('billing', 'packages', 'pkey', 0, 'pkey', false, true, false, 'a generated unique key', '1.0a100', null);
select "schema".add_column('billing', 'packages', 'name', 1, 'package', false, true, false, 'the unique name of this package entry', '1.0a100', '1.80');
select "schema".add_column('billing', 'packages', 'name', 2, 'accounting', false, true, false, 'the unique name of this package entry', '1.80.0', null);
select "schema".add_column('billing', 'packages', 'accounting', 3, 'accounting', false, false, false, 'the accounting code of the business that pays for this package', '1.0a100', null);
select "schema".add_column('billing', 'packages', 'level', 4, 'string', false, false, false, '', '1.0a100', '1.0a122');
select "schema".add_column('billing', 'packages', 'rate', 5, 'decimal_2', true, false, false, '', '1.0a100', '1.0a122');
select "schema".add_column('billing', 'packages', 'package_definition', 6, 'fkey', false, false, false, 'the definition of the package', '1.0a123', null);
select "schema".add_column('billing', 'packages', 'created', 7, 'time', false, false, false, '', '1.0a100', null);
select "schema".add_column('billing', 'packages', 'created_by', 8, 'username', false, false, false, '', '1.0a100', null);
select "schema".add_column('billing', 'packages', 'user_limit', 9, 'int', true, false, false, '', '1.0a100', '1.0a122');
select "schema".add_column('billing', 'packages', 'additional_user_rate', 10, 'decimal_2', true, false, false, '', '1.0a100', '1.0a122');
select "schema".add_column('billing', 'packages', 'pop_limit', 11, 'int', true, false, false, '', '1.0a100', '1.0a122');
select "schema".add_column('billing', 'packages', 'additional_pop_rate', 12, 'decimal_2', true, false, false, '', '1.0a100', '1.0a122');
select "schema".add_column('billing', 'packages', 'daily_smtp_in_limit', 13, 'int', false, false, false, 'the number of emails allowed through SMTP servers in one day', '1.0a100', '1.30');
select "schema".add_column('billing', 'packages', 'daily_smtp_in_bandwidth_limit', 14, 'long', false, false, false, 'the total size of emails allowed through SMTP servers in one day', '1.0a100', '1.30');
select "schema".add_column('billing', 'packages', 'daily_smtp_out_limit', 15, 'int', false, false, false, 'the number of emails allowed through SMTP servers in one day', '1.0a100', '1.30');
select "schema".add_column('billing', 'packages', 'daily_smtp_out_bandwidth_limit', 16, 'long', false, false, false, 'the total size of emails allowed through SMTP servers in one day', '1.0a100', '1.30');
select "schema".add_column('billing', 'packages', 'disable_log', 17, 'fkey', true, false, false, 'indicates that the package is disabled', '1.0a100', null);
select "schema".add_column('billing', 'packages', 'email_in_burst', 18, 'int', true, false, false, 'the maximum burst of inbound email before limiting begins', '1.24', null);
select "schema".add_column('billing', 'packages', 'email_in_rate', 19, 'float', true, false, false, 'the number of sustained inbound emails per second', '1.24', null);
select "schema".add_column('billing', 'packages', 'email_out_burst', 20, 'int', true, false, false, 'the maximum burst of outbound email before limiting begins', '1.24', null);
select "schema".add_column('billing', 'packages', 'email_out_rate', 21, 'float', true, false, false, 'the number of sustained outbound emails per second', '1.24', null);
select "schema".add_column('billing', 'packages', 'email_relay_burst', 22, 'int', true, false, false, 'the maximum burst of relay email before limiting begins', '1.24', null);
select "schema".add_column('billing', 'packages', 'email_relay_rate', 23, 'float', true, false, false, 'the number of sustained relay emails per second', '1.24', null);
