select "schema".add_column('account', 'business_servers', 'pkey',                       'pkey',       false,  true, false, 'a generated primary key', '1.0a100', null);
select "schema".add_column('account', 'business_servers', 'accounting',                 'accounting', false, false, false, 'the business', '1.0a100', null);
select "schema".add_column('account', 'business_servers', 'server',                     'fkey',       false, false, false, 'the server', '1.0a100', null);
select "schema".add_column('account', 'business_servers', 'is_default',                 'boolean',    false, false, false, 'if <code>true</code>, this is the default server.', '1.0a100', null);
select "schema".add_column('account', 'business_servers', 'can_configure_backup',       'boolean',    false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('account', 'business_servers', 'can_control_apache',         'boolean',    false, false, false, '', '1.0a100', null);
select "schema".add_column('account', 'business_servers', 'can_control_cron',           'boolean',    false, false, false, '', '1.0a100', null);
select "schema".add_column('account', 'business_servers', 'can_control_interbase',      'boolean',    false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('account', 'business_servers', 'can_control_mysql',          'boolean',    false, false, false, '', '1.0a100', null);
select "schema".add_column('account', 'business_servers', 'can_control_postgresql',     'boolean',    false, false, false, '', '1.0a100', null);
select "schema".add_column('account', 'business_servers', 'can_control_xfs',            'boolean',    false, false, false, '', '1.0a100', null);
select "schema".add_column('account', 'business_servers', 'can_control_xvfb',           'boolean',    false, false, false, '', '1.0a100', null);
select "schema".add_column('account', 'business_servers', 'can_vnc_console',            'boolean',    false, false, false, '', '1.51', null);
select "schema".add_column('account', 'business_servers', 'can_control_virtual_server', 'boolean',    false, false, false, '', '1.64', null);
