#!/bin/bash
#
# aoserv-schema - Database schema for the AOServ Platform.
# Copyright (C) 2000-2006, 2008, 2018, 2020  AO Industries, Inc.
#     support@aoindustries.com
#     7262 Bull Pen Cir
#     Mobile, AL 36695
#
# This file is part of aoserv-schema.
#
# aoserv-schema is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# aoserv-schema is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with aoserv-schema.  If not, see <https://www.gnu.org/licenses/>.
#

DIR="${BASH_SOURCE%/*}"
DB_NAME="$1"
if [ "$DB_NAME" = "" ]
then
	echo "usage: $0 {aoweb|aoserv-master/public}" 2>&1
	exit 1
fi
"${DIR}/generate_sql-drop" "$1"
"${DIR}/generate_sql-create" "$1"
"${DIR}/generate_sql-data" "$1"
"${DIR}/generate_sql-test" "$1"
"${DIR}/generate_sql-view" "$1"
"${DIR}/generate_sql-index" "$1"
"${DIR}/generate_sql-vacuum" "$1"
"${DIR}/generate_sql-reference" "$1"

