select "schema".add_foreign_key('monitoring', 'server_reports', 'ao_server',       'public', 'ao_servers', 'server', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'server_reports', 'failover_server', 'public', 'ao_servers', 'server', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_cpu', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_db_mysql', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_db_postgres', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_disk_access', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_disk_mdstat', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_disk_space', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_kernel', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_load', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_memory', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_net_devices', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_net_icmp', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_net_ip', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_net_tcp', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_net_udp', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_num_users', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_paging', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_processes', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_swap_rate', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
select "schema".add_foreign_key('monitoring', 'sr_swap_size', 'server_report', 'server_reports', 'pkey', '1.0a100', '1.30');
