\echo server_reports
select "schema".add_column('monitoring', 'server_reports', 'pkey', 0, 'pkey', false, true, false, 'a unique, generated key', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'server_reports', 'time', 1, 'time', false, false, false, 'time these stats were reported (the ending time of the interval)', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'server_reports', 'interval', 2, 'interval', false, false, false, 'time interval in milliseconds seconds that these stats apply to', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'server_reports', 'ao_server', 3, 'fkey', false, false, false, 'the pkey of the server that these stats are for', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'server_reports', 'failover_server', 4, 'fkey', true, false, false, 'the pkey of the outer server for this server at the time of this report', '1.0a100', '1.30');

\echo sr_cpu
select "schema".add_column('monitoring', 'sr_cpu', 'pkey', 0, 'pkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'server_report', 1, 'fkey', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'cpu_number', 2, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'user_min', 3, 'float', false, false, false, 'minimum user CPU %', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'user_avg', 4, 'float', false, false, false, 'average user CPU %', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'user_max', 5, 'float', false, false, false, 'maximum user CPU %', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'nice_min', 6, 'float', false, false, false, 'minimum nice CPU %', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'nice_avg', 7, 'float', false, false, false, 'average nice CPU %', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'nice_max', 8, 'float', false, false, false, 'maximum nice CPU %', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'sys_min', 9, 'float', false, false, false, 'minimum system CPU %', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'sys_avg', 10, 'float', false, false, false, 'average system CPU %', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_cpu', 'sys_max', 11, 'float', false, false, false, 'maximum system CPU %', '1.0a100', '1.30');

\echo sr_db_mysql
select "schema".add_column('monitoring', 'sr_db_mysql', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'conn_min', 1, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'conn_avg', 2, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'conn_max', 3, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'questions_min', 4, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'questions_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'questions_max', 6, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'slow_queries_min', 7, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'slow_queries_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'slow_queries_max', 9, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'opens_min', 10, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'opens_avg', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'opens_max', 12, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'flush_min', 13, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'flush_avg', 14, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'flush_max', 15, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'open_tables_min', 16, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'open_tables_avg', 17, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'open_tables_max', 18, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'query_rate_min', 19, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'query_rate_avg', 20, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_mysql', 'query_rate_max', 21, 'float', false, false, false, '', '1.0a100', '1.30');

\echo sr_db_postgres
select "schema".add_column('monitoring', 'sr_db_postgres', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_postgres', 'conn_min', 1, 'int', false, false, false, 'minimum concurrent users', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_postgres', 'conn_avg', 2, 'float', false, false, false, 'average concurrent users', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_db_postgres', 'conn_max', 3, 'int', false, false, false, 'maximum concurrent users', '1.0a100', '1.30');

\echo sr_disk_access
select "schema".add_column('monitoring', 'sr_disk_access', 'pkey', 0, 'pkey', false, true, false, 'a generated pkey', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'server_report', 1, 'fkey', false, false, false, 'the report this is part of', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'device_major', 2, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'device_minor', 3, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'blocks_min', 4, 'long', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'blocks_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'blocks_max', 6, 'long', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'rios_min', 7, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'rios_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'rios_max', 9, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'rmerges_min', 10, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'rmerges_avg', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'rmerges_max', 12, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'rsect_min', 13, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'rsect_avg', 14, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'rsect_max', 15, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'ruse_min', 16, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'ruse_avg', 17, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'ruse_max', 18, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wios_min', 19, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wios_avg', 20, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wios_max', 21, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wmerge_min', 22, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wmerge_avg', 23, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wmerge_max', 24, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wsect_min', 25, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wsect_avg', 26, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wsect_max', 27, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wuse_min', 28, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wuse_avg', 29, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'wuse_max', 30, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'running_min', 31, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'running_avg', 32, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'running_max', 33, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'use_min', 34, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'use_avg', 35, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'use_max', 36, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'aveq_min', 37, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'aveq_avg', 38, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_access', 'aveq_max', 39, 'float', false, false, false, '', '1.0a100', '1.30');

\echo sr_disk_mdstat
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'pkey', 0, 'pkey', false, true, false, 'a generated pkey', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'server_report', 1, 'fkey', false, false, false, 'the report this is part of', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'device_major', 2, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'device_minor', 3, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'total_partitions_min', 4, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'total_partitions_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'total_partitions_max', 6, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'active_partitions_min', 7, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'active_partitions_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'active_partitions_max', 9, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'rebuild_percent_min', 10, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'rebuild_percent_avg', 11, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'rebuild_percent_max', 12, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'rebuild_rate_min', 13, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'rebuild_rate_avg', 14, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_mdstat', 'rebuild_rate_max', 15, 'int', true, false, false, '', '1.0a100', '1.30');

\echo sr_disk_space
select "schema".add_column('monitoring', 'sr_disk_space', 'pkey', 0, 'pkey', false, true, false, 'a generated pkey', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'server_report', 1, 'fkey', false, false, false, 'the report this is part of', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'device_major', 2, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'device_minor', 3, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'total_min', 4, 'long', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'total_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'total_max', 6, 'long', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'used_min', 7, 'long', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'used_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'used_max', 9, 'long', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'free_min', 10, 'long', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'free_avg', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_disk_space', 'free_max', 12, 'long', false, false, false, '', '1.0a100', '1.30');

\echo sr_kernel
select "schema".add_column('monitoring', 'sr_kernel', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'files_allocated_min', 1, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'files_allocated_avg', 2, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'files_allocated_max', 3, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'files_used_min', 4, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'files_used_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'files_used_max', 6, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'files_max_min', 7, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'files_max_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'files_max_max', 9, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_inodes_min', 10, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_inodes_avg', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_inodes_max', 12, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_free_inodes_min', 13, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_free_inodes_avg', 14, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_free_inodes_max', 15, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'inode_preshrink_min', 16, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'inode_preshrink_avg', 17, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'inode_preshrink_max', 18, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'msgmax_min', 19, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'msgmax_avg', 20, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'msgmax_max', 21, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'msgmnb_min', 22, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'msgmnb_avg', 23, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'msgmnb_max', 24, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'msgmni_min', 25, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'msgmni_avg', 26, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'msgmni_max', 27, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_msg_min', 28, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_msg_avg', 29, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_msg_max', 30, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'entropy_avail_min', 31, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'entropy_avail_avg', 32, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'entropy_avail_max', 33, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'rtsig_max_min', 34, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'rtsig_max_avg', 35, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'rtsig_max_max', 36, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'rtsig_nr_min', 37, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'rtsig_nr_avg', 38, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'rtsig_nr_max', 39, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semmsl_min', 40, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semmsl_avg', 41, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semmsl_max', 42, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semmns_min', 43, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semmns_avg', 44, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semmns_max', 45, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semopm_min', 46, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semopm_avg', 47, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semopm_max', 48, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semmni_min', 49, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semmni_avg', 50, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'semmni_max', 51, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_sem_min', 52, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_sem_avg', 53, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_sem_max', 54, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shmall_min', 55, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shmall_avg', 56, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shmall_max', 57, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shmmax_min', 58, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shmmax_avg', 59, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shmmax_max', 60, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shmmni_min', 61, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shmmni_avg', 62, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shmmni_max', 63, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_shm_min', 64, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_shm_avg', 65, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'nr_shm_max', 66, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shm_used_min', 67, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shm_used_avg', 68, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'shm_used_max', 69, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'threads_max_min', 70, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'threads_max_avg', 71, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_kernel', 'threads_max_max', 72, 'int', false, false, false, '', '1.0a100', '1.30');

\echo sr_load
select "schema".add_column('monitoring', 'sr_load', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_load', 'min', 1, 'float', false, false, false, 'minimum load', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_load', 'avg', 2, 'float', false, false, false, 'average load', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_load', 'max', 3, 'float', false, false, false, 'maximum load', '1.0a100', '1.30');

\echo sr_memory
select "schema".add_column('monitoring', 'sr_memory', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'mem_total_min', 1, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'mem_total_avg', 2, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'mem_total_max', 3, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'mem_free_min', 4, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'mem_free_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'mem_free_max', 6, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'mem_shared_min', 7, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'mem_shared_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'mem_shared_max', 9, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'buffers_min', 10, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'buffers_avg', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'buffers_max', 12, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'cached_min', 13, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'cached_avg', 14, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'cached_max', 15, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'swap_cached_min', 16, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'swap_cached_avg', 17, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'swap_cached_max', 18, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'active_min', 19, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'active_avg', 20, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'active_max', 21, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'inact_dirty_min', 22, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'inact_dirty_avg', 23, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'inact_dirty_max', 24, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'inact_clean_min', 25, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'inact_clean_avg', 26, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'inact_clean_max', 27, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'inact_target_min', 28, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'inact_target_avg', 29, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'inact_target_max', 30, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'high_total_min', 31, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'high_total_avg', 32, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'high_total_max', 33, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'high_free_min', 34, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'high_free_avg', 35, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'high_free_max', 36, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'low_total_min', 37, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'low_total_avg', 38, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'low_total_max', 39, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'low_free_min', 40, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'low_free_avg', 41, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_memory', 'low_free_max', 42, 'int', false, false, false, '', '1.0a100', '1.30');

\echo sr_net_devices
select "schema".add_column('monitoring', 'sr_net_devices', 'pkey', 0, 'pkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'server_report', 1, 'fkey', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'device_id', 2, 'string', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_bytes_min', 3, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_bytes_avg', 4, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_bytes_max', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_packets_min', 6, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_packets_avg', 7, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_packets_max', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_errors_min', 9, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_errors_avg', 10, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_errors_max', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_drop_min', 12, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_drop_avg', 13, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_drop_max', 14, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_fifo_min', 15, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_fifo_avg', 16, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_fifo_max', 17, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_frame_min', 18, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_frame_avg', 19, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_frame_max', 20, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_compress_min', 21, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_compress_avg', 22, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_compress_max', 23, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_multicast_min', 24, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_multicast_avg', 25, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'rx_multicast_max', 26, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_bytes_min', 27, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_bytes_avg', 28, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_bytes_max', 29, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_packets_min', 30, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_packets_avg', 31, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_packets_max', 32, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_errors_min', 33, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_errors_avg', 34, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_errors_max', 35, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_drop_min', 36, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_drop_avg', 37, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_drop_max', 38, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_fifo_min', 39, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_fifo_avg', 40, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_fifo_max', 41, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_colls_min', 42, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_colls_avg', 43, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_colls_max', 44, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_carrier_min', 45, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_carrier_avg', 46, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_carrier_max', 47, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_compressed_min', 48, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_compressed_avg', 49, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'tx_compressed_max', 50, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'listen_min', 51, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'listen_avg', 52, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_devices', 'listen_max', 53, 'int', false, false, false, '', '1.0a100', '1.30');

\echo sr_net_icmp
select "schema".add_column('monitoring', 'sr_net_icmp', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_message_min', 1, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_message_avg', 2, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_message_max', 3, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_fail_min', 4, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_fail_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_fail_max', 6, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_unreachable_min', 7, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_unreachable_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_unreachable_max', 9, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_timeout_min', 10, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_timeout_avg', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_timeout_max', 12, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_quench_min', 13, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_quench_avg', 14, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_quench_max', 15, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_redirect_min', 16, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_redirect_avg', 17, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_redirect_max', 18, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_echo_request_min', 19, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_echo_request_avg', 20, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_echo_request_max', 21, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_echo_reply_min', 22, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_echo_reply_avg', 23, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'in_echo_reply_max', 24, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_message_min', 25, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_message_avg', 26, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_message_max', 27, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_fail_min', 28, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_fail_avg', 29, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_fail_max', 30, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_unreachable_min', 31, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_unreachable_avg', 32, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_unreachable_max', 33, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_timeout_min', 34, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_timeout_avg', 35, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_timeout_max', 36, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_redirect_min', 37, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_redirect_avg', 38, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_redirect_max', 39, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_echo_reply_min', 40, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_echo_reply_avg', 41, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_icmp', 'out_echo_reply_max', 42, 'float', false, false, false, '', '1.0a100', '1.30');

\echo sr_net_ip
select "schema".add_column('monitoring', 'sr_net_ip', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'packet_min', 1, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'packet_avg', 2, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'packet_max', 3, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'invalid_headers_min', 4, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'invalid_headers_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'invalid_headers_max', 6, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'forward_min', 7, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'forward_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'forward_max', 9, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'discard_min', 10, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'discard_avg', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'discard_max', 12, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'deliver_min', 13, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'deliver_avg', 14, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'deliver_max', 15, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'request_min', 16, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'request_avg', 17, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'request_max', 18, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'out_drop_min', 19, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'out_drop_avg', 20, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'out_drop_max', 21, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'out_drop_no_route_min', 22, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'out_drop_no_route_avg', 23, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'out_drop_no_route_max', 24, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'out_drop_timeout_min', 25, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'out_drop_timeout_avg', 26, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'out_drop_timeout_max', 27, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'ra_req_min', 28, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'ra_req_avg', 29, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'ra_req_max', 30, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'ra_ok_min', 31, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'ra_ok_avg', 32, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'ra_ok_max', 33, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'ra_fail_min', 34, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'ra_fail_avg', 35, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_ip', 'ra_fail_max', 36, 'float', false, false, false, '', '1.0a100', '1.30');

\echo sr_net_tcp
select "schema".add_column('monitoring', 'sr_net_tcp', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'active_connect_min', 1, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'active_connect_avg', 2, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'active_connect_max', 3, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'passive_connect_min', 4, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'passive_connect_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'passive_connect_max', 6, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'fail_connect_min', 7, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'fail_connect_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'fail_connect_max', 9, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'in_reset_min', 10, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'in_reset_avg', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'in_reset_max', 12, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'connect_min', 13, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'connect_avg', 14, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'connect_max', 15, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'segment_receive_min', 16, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'segment_receive_avg', 17, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'segment_receive_max', 18, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'segment_send_min', 19, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'segment_send_avg', 20, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'segment_send_max', 21, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'segment_resend_min', 22, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'segment_resend_avg', 23, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'segment_resend_max', 24, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'bad_segment_receive_min', 25, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'bad_segment_receive_avg', 26, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'bad_segment_receive_max', 27, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'out_reset_min', 28, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'out_reset_avg', 29, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_tcp', 'out_reset_max', 30, 'float', false, false, false, '', '1.0a100', '1.30');

\echo sr_net_udp
select "schema".add_column('monitoring', 'sr_net_udp', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'receive_min', 1, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'receive_avg', 2, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'receive_max', 3, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'unknown_min', 4, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'unknown_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'unknown_max', 6, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'error_min', 7, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'error_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'error_max', 9, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'send_min', 10, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'send_avg', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_net_udp', 'send_max', 12, 'float', false, false, false, '', '1.0a100', '1.30');

\echo sr_num_users
select "schema".add_column('monitoring', 'sr_num_users', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_num_users', 'min', 1, 'int', false, false, false, 'minimum concurrent users', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_num_users', 'avg', 2, 'float', false, false, false, 'average concurrent users', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_num_users', 'max', 3, 'int', false, false, false, 'maximum concurrent users', '1.0a100', '1.30');

\echo sr_paging
select "schema".add_column('monitoring', 'sr_paging', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_paging', 'in_min', 1, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_paging', 'in_avg', 2, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_paging', 'in_max', 3, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_paging', 'out_min', 4, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_paging', 'out_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_paging', 'out_max', 6, 'float', false, false, false, '', '1.0a100', '1.30');

\echo sr_processes
select "schema".add_column('monitoring', 'sr_processes', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_sleep_min', 1, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_sleep_avg', 2, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_sleep_max', 3, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_sleep_min', 4, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_sleep_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_sleep_max', 6, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_run_min', 7, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_run_avg', 8, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_run_max', 9, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_run_min', 10, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_run_avg', 11, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_run_max', 12, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_zombie_min', 13, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_zombie_avg', 14, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_zombie_max', 15, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_zombie_min', 16, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_zombie_avg', 17, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_zombie_max', 18, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_trace_min', 19, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_trace_avg', 20, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_trace_max', 21, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_trace_min', 22, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_trace_avg', 23, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_trace_max', 24, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_uninterruptible_min', 25, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_uninterruptible_avg', 26, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_uninterruptible_max', 27, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_uninterruptible_min', 28, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_uninterruptible_avg', 29, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_uninterruptible_max', 30, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_unknown_min', 31, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_unknown_avg', 32, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'total_unknown_max', 33, 'int', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_unknown_min', 34, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_unknown_avg', 35, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'user_unknown_max', 36, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'rate_min', 37, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'rate_avg', 38, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'rate_max', 39, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'context_min', 40, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'context_avg', 41, 'float', true, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_processes', 'context_max', 42, 'float', true, false, false, '', '1.0a100', '1.30');

\echo sr_swap_rate
select "schema".add_column('monitoring', 'sr_swap_rate', 'server_report', 0, 'fkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_rate', 'in_min', 1, 'float', false, false, false, 'minimum swap reads per second', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_rate', 'in_avg', 2, 'float', false, false, false, 'average swap reads per second', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_rate', 'in_max', 3, 'float', false, false, false, 'maximum swap reads per second', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_rate', 'out_min', 4, 'float', false, false, false, 'minimum swap writes per second', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_rate', 'out_avg', 5, 'float', false, false, false, 'average swap writes per second', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_rate', 'out_max', 6, 'float', false, false, false, 'maximum swap writes per second', '1.0a100', '1.30');

\echo sr_swap_size
select "schema".add_column('monitoring', 'sr_swap_size', 'pkey', 0, 'pkey', false, true, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_size', 'server_report', 1, 'fkey', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_size', 'device_major', 2, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_size', 'device_minor', 3, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_size', 'total_min', 4, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_size', 'total_avg', 5, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_size', 'total_max', 6, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_size', 'used_min', 7, 'int', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_size', 'used_avg', 8, 'float', false, false, false, '', '1.0a100', '1.30');
select "schema".add_column('monitoring', 'sr_swap_size', 'used_max', 9, 'int', false, false, false, '', '1.0a100', '1.30');
