begin;
-- centos
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(64, 'centos', '5.dom0', '5', 'i686', 'CentOS 5 (i686) (Xen Domain-0)', true, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(63, 'centos', '5.dom0', '5', 'x86_64', 'CentOS 5 (x86_64) (Xen Domain-0)', true, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(67, 'centos', '5', '5', 'i686,x86_64', 'CentOS 5 (i686 and x86_64) (Xen Guest and Standalone)', true, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(69, 'centos', '7.dom0', '7.dom0', 'x86_64', 'CentOS 7 (x86_64) (Xen Domain-0)', true, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(70, 'centos', '7', '7', 'x86_64', 'CentOS 7 (x86_64) (Xen Guest and Standalone)', true, (select count(*)+1 from distribution."OperatingSystemVersion"));
-- debian
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(1, 'debian', '3.0r1', 'Woody', 'i386', 'Debian 3.0r1 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(68, 'debian', '5', 'Lenny', 'x86_64', 'Debian 5 (x86_64)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
-- fedora
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(50, 'fedora', '1', 'Yarrow', 'i386', 'Fedora Core 1 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(51, 'fedora', '2', 'Tettnang', 'i386', 'Fedora Core 2 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(48, 'fedora', '3', 'Heidelberg', 'i386', 'Fedora Core 3 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(52, 'fedora', '4', 'Stentz', 'i386', 'Fedora Core 4 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(53, 'fedora', '5', 'Bordeaux', 'i386', 'Fedora Core 5 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(49, 'fedora', '6', 'Zod', 'i386', 'Fedora Core 6 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
-- gentoo
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(2, 'gentoo', '1.4', '1.4', 'alpha', 'Gentoo 1.4 (alpha)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(3, 'gentoo', '1.4', '1.4', 'amd64', 'Gentoo 1.4 (amd64)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(4, 'gentoo', '1.4', '1.4', 'hppa', 'Gentoo 1.4 (hppa)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(5, 'gentoo', '1.4', '1.4', 'i686', 'Gentoo 1.4 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(6, 'gentoo', '1.4', '1.4', 'ppc', 'Gentoo 1.4 (ppc)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(7, 'gentoo', '1.4', '1.4', 'sparc', 'Gentoo 1.4 (sparc)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(8, 'gentoo', '1.4', '1.4', 'sparc64', 'Gentoo 1.4 (sparc64)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(46, 'gentoo', '2006.0', '2006.0', 'i686', 'Gentoo 2006.0 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
-- mandrake/mandriva
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(9, 'mandrake', '8.0', '8.0', 'i586', 'Mandrake 8.0 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(10, 'mandrake', '9.0', '9.0', 'i586', 'Mandrake 9.0 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(11, 'mandrake', '9.1', '9.1', 'i586', 'Mandrake 9.1 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(12, 'mandrake', '9.2', '9.2', 'i586', 'Mandrake 9.2 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(13, 'mandrake', '10.0', '10.0', 'i586', 'Mandrake 10.0 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(14, 'mandrake', '10.1', '10.1', 'i586', 'Mandrake 10.1 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(43, 'mandrake', '10.2', '10.2', 'i586', 'Mandrake 10.2 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(44, 'mandriva', 'LE2005', 'LE2005', 'i586', 'Mandriva Limited Edition 2005 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(45, 'mandriva', '2006.0', '2006.0', 'i586', 'Mandriva 2006.0 (i586)', true, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(54, 'mandriva', '2007.0', '2007.0', 'i586', 'Mandriva 2007.0 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(62, 'mandriva', '2007.1', '2007.1', 'i586', 'Mandriva 2007 Spring (i586)', true, (select count(*)+1 from distribution."OperatingSystemVersion"));
-- redhat
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(61, 'redhat', '0.8', 'Preview', 'i386', 'RedHat 0.8 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(60, 'redhat', '0.9', 'Halloween', 'i386', 'RedHat 0.9 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(59, 'redhat', '1.0', 'Mother''s Day', 'i386', 'RedHat 1.0 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(58, 'redhat', '1.1', 'Mother''s Day+1', 'i386', 'RedHat 1.1 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(57, 'redhat', '2.0', '2.0', 'i386', 'RedHat 2.0 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(56, 'redhat', '2.1', '2.1', 'i386', 'RedHat 2.1 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(15, 'redhat', '3.0.3', 'Picasso', 'i386', 'RedHat 3.0.3 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(55, 'redhat', '3.0.4', 'Rembrandt', 'i386', 'RedHat 3.0.4 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(16, 'redhat', '4.0', 'Colgate', 'i386', 'RedHat 4.0 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(17, 'redhat', '4.1', 'Vanderbilt', 'i386', 'RedHat 4.1 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(18, 'redhat', '4.2', 'Biltmore', 'i386', 'RedHat 4.2 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(19, 'redhat', '5.0', 'Hurricane', 'i586', 'RedHat 5.0 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(20, 'redhat', '5.1', 'Manhattan', 'i586', 'RedHat 5.1 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(21, 'redhat', '5.2', 'Apollo', 'i586', 'RedHat 5.2 (i586)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(22, 'redhat', '6.0', 'Hedwig', 'i686', 'RedHat 6.0 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(23, 'redhat', '6.1', 'Cartman', 'i686', 'RedHat 6.1 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(24, 'redhat', '6.2', 'Zoot', 'i686', 'RedHat 6.2 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(25, 'redhat', '7.0', 'Guinness', 'i686', 'RedHat 7.0 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(26, 'redhat', '7.1', 'Seawolf', 'i686', 'RedHat 7.1 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(27, 'redhat', '7.2', 'Enigma', 'i686', 'RedHat 7.2 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(28, 'redhat', '7.3', 'Valhalla', 'i686', 'RedHat 7.3 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(29, 'redhat', '8.0', 'Psyche', 'i686', 'RedHat 8.0 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(30, 'redhat', '9', 'Shrike', 'i686', 'RedHat 9 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(31, 'redhat', 'ES 2.1', 'ES 2.1', 'i686', 'RedHat ES 2.1 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(32, 'redhat', 'ES 3.0', 'ES 3.0', 'i686', 'RedHat ES 3.0 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(47, 'redhat', 'ES 4', 'ES 4', 'x86_64', 'RedHat ES 4 (x86_64)', true, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(65, 'redhat', 'ES 5', 'ES 5', 'i686', 'RedHat ES 5 (i686)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(66, 'redhat', 'ES 5', 'ES 5', 'x86_64', 'RedHat ES 5 (x86_64)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
-- windows
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(33, 'windows', '3.0', '3.0', 'i286', 'Windows 3.0 (i286)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(34, 'windows', '3.1', '3.1', 'i286', 'Windows 3.1 (i286)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(35, 'windows', '3.11', '3.11', 'i386', 'Windows 3.11 for Workgroups (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(36, 'windows', '4.0', '95', 'i386', 'Windows 95 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(37, 'windows', '4.10', '98', 'i386', 'Windows 98 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(38, 'windows', '4.90', '98 SE', 'i386', 'Windows 98 SE (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(39, 'windows', 'NT 4.0', 'NT 4.0', 'i386', 'Windows NT 4.0 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(40, 'windows', 'NT 5.0', '2000', 'i386', 'Windows 2000 (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(41, 'windows', 'NT 5.1', 'XP', 'i386', 'Windows XP (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
insert into distribution."OperatingSystemVersion" (pkey, operating_system, version_number, version_name, architecture, display, is_aoserv_daemon_supported, sort_order) values(42, 'windows', '2003 Server', '2003 Server', 'i386', 'Windows 2003 Server (i386)', false, (select count(*)+1 from distribution."OperatingSystemVersion"));
commit;
