COPY distribution."SoftwareCategorization" ("name", "class") FROM stdin;
analog	Apache
which	Linux
words	Linux
fastcgi	Apache
jakarta-cocoon	Apache
jakarta-tomcat	Apache
php	Apache
pine	E-Mail
metamail	E-Mail
mutt	E-Mail
procmail	E-Mail
wu-ftpd	Linux
Crypt-CBC	Encryption
Crypt-DES	Encryption
Digest-MD5	Encryption
gnupg	Encryption
libmcrypt	Encryption
mcrypt	Encryption
openssl	Encryption
openssl-devel	Encryption
zip	Linux
sendmail	E-Mail
sendmail-cf	E-Mail
daemontools	Linux
Apache-Jyve	Java
Apache-Turbine	Java
hivemind	Java
cos	Java
ecs	Java
fop	Java
FreeMarker	Java
gnu.regexp	Java
jaf	Java
jakarta-jcs	Java
jakarta-cocoon	Java
jakarta-oro	Java
jakarta-regexp	Java
jakarta-servletapi	Java
jakarta-slide	Java
jakarta-commons-attributes	Java
jakarta-taglibs	Java
jakarta-tomcat	Java
jakarta-watchdog	Java
javamail	Java
jdbc	Java
dot-forward	E-Mail
jakarta-commons-betwixt	Java
JSDK	Java
JSP	Java
kavachart	Java
mm-mysql	Java
openxml	Java
ozone	Java
pop3	Java
fastforward	E-Mail
spfc	Java
village	Java
webmacro	Java
qmail	E-Mail
xang	Java
ucspi-tcp	E-Mail
ezmlm	E-Mail
xmlrpc-java	Java
anonftp	Linux
ash	Linux
aspell	Linux
autoconf	Linux
automake	Linux
basesystem	Linux
bash	Linux
bc	Linux
bdflush	Linux
bind	Linux
bind-utils	Linux
binutils	Linux
byacc	Linux
bzip2	Linux
caching-nameserver	Linux
chkconfig	Linux
chkfontpath	Linux
compat-libstdc++	Linux
console-tools	Linux
sysstat	Linux
cpio	Linux
cpp	Linux
cracklib	Linux
cracklib-dicts	Linux
crontabs	Linux
cvs	Linux
cyrus-sasl	Linux
db1	Linux
db2	Linux
db3	Linux
dev	Linux
dev86	Linux
diffutils	Linux
mrtg	Linux
hwcrypto	Encryption
e2fsprogs	Linux
e2fsprogs-devel	Linux
ed	Linux
hwcrypto	Linux
aspell-devel	Linux
bind-devel	Linux
emacs	Linux
emacs-el	Linux
emacs-leim	Linux
emacs-nox	Linux
emacs-X11	Linux
emacs-X11	X11
expect	Linux
file	Linux
filesystem	Linux
fileutils	Linux
findutils	Linux
flex	Linux
fortune-mod	Linux
freetype	Linux
ftp	Linux
Garbage	Linux
gawk	Linux
gcc	Linux
gcc-c++	Linux
gcc-g77	Linux
gcc-objc	Linux
gd	Linux
gdb	Linux
gdbm	Linux
gdbm-devel	Linux
ghostscript	Linux
ghostscript-fonts	Linux
glib	Linux
glibc	Linux
glibc-devel	Linux
gmp	Linux
grep	Linux
groff	Linux
gtk+	Linux
gzip	Linux
hdparm	Linux
bzip2-devel	Linux
indexhtml	Linux
info	Linux
initscripts	Linux
iputils	Linux
Apache-Test	PERL
kernel-smp	Linux
krb5-libs	Linux
less	Linux
libgr	Linux
libjpeg	Linux
libjpeg-devel	Linux
libstdc++	Linux
libstdc++-devel	Linux
libtermcap	Linux
libtiff	Linux
libtool	Linux
libtool-libs	Linux
libungif	Linux
libungif-progs	Linux
lilo	Linux
linuxconf	Linux
logrotate	Linux
bzip2-libs	Linux
losetup	Linux
lslk	Linux
lsof	Linux
ltrace	Linux
lynx	Linux
m4	Linux
curl	Linux
curl-devel	Linux
cyrus-sasl-md5	Linux
make	Linux
MAKEDEV	Linux
man	Linux
man-pages	Linux
cyrus-sasl-plain	Linux
mingetty	Linux
mkbootdisk	Linux
mkinitrd	Linux
mktemp	Linux
modutils	Linux
mount	Linux
ncompress	Linux
ncurses	Linux
ncurses-devel	Linux
ncurses4	Linux
net-tools	Linux
phpMyAdmin	PHP
openldap	Linux
pam	Linux
passwd	Linux
patch	Linux
pidentd	Linux
php	PHP
pmake	Linux
db2-devel	Linux
popt	Linux
procinfo	Linux
db3-devel	Linux
procps	Linux
dialog	Linux
psmisc	Linux
pspell	Linux
pvm	Linux
pvm-gui	Linux
pwdb	Linux
python	Python
dosfstools	Linux
qt	Linux
Apache-Test	Apache
expat	XML
raidtools	Linux
expat-devel	XML
readline	Linux
redhat-logos	Linux
redhat-release	Linux
rgrep	Linux
rmt	Linux
rootfiles	Linux
rpm	Linux
rpm-build	Linux
sash	Linux
sed	Linux
finger	Linux
setserial	Linux
setup	Linux
sh-utils	Linux
shadow-utils	Linux
sharutils	Linux
slang	Linux
slocate	Linux
stat	Linux
stunnel	Linux
symlinks	Linux
sysklogd	Linux
SysVinit	Linux
talk	Linux
talk-server	Linux
tar	Linux
tcl	Linux
tcpdump	Linux
tcp_wrappers	Linux
tcsh	Linux
telnet	Linux
telnet-server	Linux
termcap	Linux
texinfo	Linux
textutils	Linux
time	Linux
tix	Linux
tk	Linux
tkinter	Linux
tmpwatch	Linux
traceroute	Linux
unzip	Linux
urw-fonts	Linux
utempter	Linux
util-linux	Linux
vim-common	Linux
vim-minimal	Linux
vixie-cron	Linux
wget	Linux
zlib	Linux
zlib-devel	Linux
mm-mysql	MySQL
Msql-Mysql-modules	MySQL
MySQL	MySQL
freetype-devel	Linux
phpMyAdmin	MySQL
Crypt-CBC	PERL
Crypt-DES	PERL
Data-ShowTable	PERL
DBI	PERL
Digest-MD5	PERL
fastcgi	PERL
FCGI	PERL
HTML-Parser	PERL
libnet	PERL
libwww-perl	PERL
MIME-Base64	PERL
Msql-Mysql-modules	PERL
Net-Daemon	PERL
perl	PERL
gcc3	Linux
gcc3-c++	Linux
gcc3-g77	Linux
gcc3-java	Linux
gcc3-objc	Linux
gcc-chill	Linux
PlRPC	PERL
Storable	PERL
URI	PERL
gcc-java	Linux
postgresql	PostgreSQL
Mesa	X11
gd-devel	Linux
XFree86	X11
XFree86-100dpi-fonts	X11
XFree86-75dpi-fonts	X11
XFree86-ISO8859-2-75dpi-fonts	X11
XFree86-libs	X11
XFree86-xfs	X11
XFree86-Xvfb	X11
iptables-ipv6	Linux
glibc-profile	Linux
fop	XML
jakarta-cocoon	XML
openxml	XML
gmp-devel	Linux
iproute	Linux
xang	XML
Xaw3d	XML
iptables	Linux
jikes	Java
xmlrpc-java	XML
Apache-JSSI	Apache
Apache-JSSI	Java
InterBaseSS_LI	InterBase
InterClient	InterBase
mc	Linux
screen	Linux
kernel	Linux
PoolMan	Java
PoolMan	MySQL
PoolMan	PostgreSQL
PoolMan	InterBase
glibc-common	Linux
nscd	Linux
krb5-devel	Linux
libcap	Linux
jsse	Encryption
jsse	Java
XFree86-devel	X11
apache	Apache
readline-devel	Linux
gtk+-devel	Linux
glib-devel	Linux
libgcc	Linux
fftw	Linux
fftw-devel	Linux
libpng-devel	X11
mod_ssl	Apache
mod_ssl	Encryption
apache-devel	Apache
JBoss	Apache
JBoss	Java
JBoss	PostgreSQL
DBD-Pg	PERL
DBD-Pg	PostgreSQL
openssh	Encryption
openssh-clients	Encryption
openssh-server	Encryption
mx	PostgreSQL
wv	Linux
libgcj	Linux
libgcj3	Linux
libgcj3-devel	Linux
libgcj-devel	Linux
libmcrypt-devel	Encryption
libstdc++3	Linux
libstdc++3-devel	Linux
libtiff-devel	Linux
libxml2	XML
libxml2-devel	XML
libxslt	XML
libxslt-devel	XML
mhash	Encryption
mhash-devel	Encryption
mm	Linux
mm-devel	Linux
mod_dav	Apache
mod_perl	Apache
mod_perl	PERL
nc	Linux
ntp	Linux
php	MySQL
php	PostgreSQL
php	InterBase
php	Encryption
php	XML
Test-Manifest	PERL
openldap-clients	Linux
kernel-doc	Linux
xinetd	Linux
InterClient	Java
ezmlm-idx	E-Mail
qmail-smtpd-auth	E-Mail
dhcpcd	Linux
mod_jk	Apache
mod_jk	Java
rdist	Linux
rsync	Linux
openldap-devel	Linux
openssl095a	Encryption
openssl096	Encryption
openssl-perl	Encryption
openssl-perl	PERL
pam-devel	Linux
pdflib	Linux
pdflib-devel	Linux
perl-CGI	Apache
perl-CGI	PERL
perl-CPAN	PERL
perl-DB_File	PERL
perl-NDBM_File	PERL
pspell-devel	Linux
srm	Linux
syslinux	Linux
tamago	Linux
tetex	Linux
tetex-fonts	Linux
ttfonts	X11
ttfonts-ja	X11
ucd-snmp	Linux
ucd-snmp-devel	Linux
ucd-snmp-utils	Linux
unixODBC	Linux
unixODBC-devel	Linux
VFlib2	Linux
vim-enhanced	Linux
whois	Linux
XFree86-cyrillic-fonts	X11
XFree86-ISO8859-15-100dpi-fonts	X11
XFree86-ISO8859-15-75dpi-fonts	X11
XFree86-ISO8859-2-100dpi-fonts	X11
XFree86-ISO8859-9-100dpi-fonts	X11
XFree86-ISO8859-9-75dpi-fonts	X11
PGPcmdln	Encryption
soap	Java
soap	XML
jdk	Java
IBMJava	Java
j2sdk	Java
httperf	Linux
jakarta-commons-beanutils	Java
xalan	Java
xalan	XML
Bundle-libnet	PERL
CGI	PERL
File-Temp	PERL
HTML-Tagset	PERL
Parse-RecDescent	PERL
Socket	PERL
Spreadsheet-WriteExcel	PERL
xerces	Java
xerces	XML
elm	E-Mail
imap	E-Mail
imap-devel	E-Mail
javamail	E-Mail
pop3	E-Mail
JBoss	InterBase
mailcap	E-Mail
mailx	E-Mail
majordomo	E-Mail
majordomo	PERL
python-devel	Python
qt-devel	Linux
libpng	X11
python2	Python
python2-devel	Python
python-docs	Python
python-tools	Python
Devel-CoreStack	PERL
HTML-Element-Extended	PERL
HTML-Tree	PERL
libxml-perl	PERL
libxml-perl	XML
Scalar-List-Utils	PERL
Test-Harness	PERL
Test-Simple	PERL
XML-DOM	PERL
XML-DOM	XML
XML-GDOME	PERL
XML-GDOME	XML
XML-LibXML	PERL
XML-LibXML	XML
XML-LibXML-Common	PERL
XML-LibXML-Common	XML
XML-NamespaceSupport	PERL
XML-NamespaceSupport	XML
XML-Parser	PERL
XML-Parser	XML
XML-RegExp	PERL
XML-RegExp	XML
XML-SAX	PERL
XML-SAX	XML
XML-Simple	PERL
XML-Simple	XML
XML-SimpleObject	PERL
XML-SimpleObject	XML
XML-TreeBuilder	PERL
XML-TreeBuilder	XML
XML-Twig	PERL
XML-Twig	XML
XML-Writer	PERL
XML-Writer	XML
XML-XSLT	PERL
XML-XSLT	XML
gdome2	XML
gdome2-devel	XML
samba	Linux
samba-common	Linux
perl-suidperl	PERL
kernel-headers	Linux
ApacheDBI	Apache
ApacheDBI	PERL
AppConfig	PERL
Archive-Tar	PERL
Compress-Zlib	PERL
DateManip	PERL
DBIx-Password	PERL
Email-Valid	PERL
Font-AFM	PERL
HTML-Format	PERL
Image-Size	PERL
libapreq	PERL
Mail-Sendmail	PERL
MailTools	PERL
MD5	PERL
Schedule-Cron	PERL
Template-Toolkit	PERL
TimeDate	PERL
Time-HiRes	PERL
Time-modules	PERL
XML-RSS	PERL
IO-Zlib	PERL
bootloader-utils	Linux
common-licenses	Linux
coreutils	Linux
ExtUtils-MakeMaker	PERL
reiserfs-utils	Linux
cyrus-sasl-devel	Linux
ImageMagick	Linux
ImageMagick-Magick++	Linux
ImageMagick-devel	Linux
libpango1.0_0-devel	Linux
coreutils-doc	Linux
elfutils	Linux
etcskel	Linux
fontconfig	X11
font-tools	Linux
freetype-tools	Linux
gcc-cpp	Linux
gettext-base	Linux
gpg-pubkey	Encryption
groff-for-man	Linux
gtk+2.0	Linux
gtkdialogs	Linux
ifplugd	Linux
info-install	Linux
iproute2	Linux
kernel-enterprise	Linux
ldconfig	Linux
libacl1	Linux
imap-utils	E-Mail
perl-Authen-SASL	PERL
perl-base	PERL
perl-Convert-ASN1	PERL
perl-Authen-SASL	Encryption
perl-Digest-HMAC	Encryption
perl-Digest-HMAC	PERL
perl-Digest-SHA1	PERL
perl-Digest-SHA1	Encryption
perl-Expect	PERL
perl-Glib	PERL
perl-Gtk2	PERL
perl-HTML-Parser	PERL
perl-HTML-Tagset	PERL
perl-IO-Tty	PERL
perl-ldap	PERL
perl-libwww-perl	PERL
perl-Locale-gettext	PERL
perl-MDK-Common	PERL
perl-URI	PERL
perl-URPM	PERL
perl-XML-NamespaceSupport	PERL
perl-XML-NamespaceSupport	XML
perl-XML-Parser	XML
perl-XML-Parser	PERL
perl-XML-SAX	PERL
perl-XML-SAX	XML
libatk1.0_0	Linux
libattr1	Linux
libbzip2_1	Linux
libconsole0	Linux
libcrack2	Linux
libcups2	Linux
libcurl2	Linux
libdb4.1	Linux
libelfutils1	Linux
libexpat0	Linux
libext2fs2	Linux
libfontconfig1	Linux
libfreetype6	Linux
libgcc1	Linux
libgd2	Linux
libgdbm2	Linux
libgdk_pixbuf2.0_0	Linux
libglade2.0_0	Linux
libglib1.2	Linux
libglib2.0_0	Linux
libgpm1	Linux
libgtk+-x11-2.0_0	X11
libjpeg62	Linux
libldap2	Linux
libMesaGLU1	X11
libnet-snmp50	Linux
libopenssl0.9.7	Encryption
libpcre0	Linux
libpwdb0	Linux
libreadline4	Linux
libslang1	Linux
libtermcap2	Linux
libuser	Linux
libuser1	Linux
libxfree86	X11
locales	Linux
locales-en	Linux
mdk-menu-messages	Linux
mpage	Linux
net-snmp	Linux
net-snmp-utils	Linux
net-snmp-mibs	Linux
python-base	Python
libgtk+2.0_0	Linux
libintl2	Linux
libkrb51	Linux
libmagic1	Linux
libncurses5	Linux
libnewt0.51	Linux
libpango1.0_0	Linux
libpng3	Linux
libpython2.3	Python
libsasl2	Linux
libext2fs2-devel	Linux
libstdc++5	Linux
libtiff3	Linux
libutempter0	Linux
libxclass0	Linux
makedev	Linux
libkrb51-devel	Linux
menu	Linux
pwdb-conf	Linux
rpm-helper	Linux
samba-server	Linux
t1utils	Linux
timezone	Linux
xclass-icons	Linux
zcip	Linux
zlib1	Linux
libxpm4	Linux
mandrake-release	Linux
libltdl3	Linux
pango	Linux
gcc-colorgcc	Linux
reiserfsprogs	Linux
rpmtools	Linux
strace	Linux
usermode	Linux
usermode-consoleonly	Linux
xinitrc	X11
gcc-gnat	Linux
gcc-gpc	Linux
gcj-tools	Linux
libbinutils2	Linux
libf2c0	Linux
libgcj4	Linux
libgcj4-devel	Linux
libgcj4-static-devel	Linux
libgnat1	Linux
libstdc++5-devel	Linux
zlib1-devel	Linux
proftpd	Linux
proftpd-anonymous	Linux
apache2	Apache
apache2-common	Apache
apache2-mod_cache	Apache
apache2-mod_dav	Apache
apache2-mod_deflate	Apache
apache2-mod_disk_cache	Apache
apache2-mod_perl	Apache
apache2-mod_perl	PERL
apache2-mod_proxy	Apache
apache2-mod_ssl	Apache
apache2-mod_ssl	Encryption
apache2-mod_suexec	Apache
apache2-modules	Apache
apache-conf	Apache
libapr0	Apache
mod_perl-common	Apache
mod_perl-common	PERL
perl-BSD-Resource	PERL
perl-Devel-Symdump	PERL
perl-DBI	PERL
ADVX-build	Linux
apache2-devel	Apache
apache2-mod_perl-devel	Apache
apache2-mod_perl-devel	PERL
libexpat0-devel	Linux
libgdbm2-devel	Linux
libopenssl0.9.7-devel	Encryption
gcc2.96	Linux
gcc2.96-c++	Linux
gcc2.96-cpp	Linux
libstdc++2.10	Linux
libstdc++2.10-devel	Linux
perl-devel	PERL
locales-am	Linux
locales-ar	Linux
locales-as	Linux
locales-az	Linux
locales-be	Linux
locales-bg	Linux
locales-bn	Linux
locales-br	Linux
locales-bs	Linux
locales-ca	Linux
locales-cs	Linux
locales-cy	Linux
locales-da	Linux
locales-de	Linux
locales-el	Linux
bison	Linux
locales-eo	Linux
locales-es	Linux
locales-et	Linux
locales-eu	Linux
locales-fa	Linux
locales-fi	Linux
locales-fo	Linux
locales-fr	Linux
locales-ga	Linux
locales-gd	Linux
locales-gl	Linux
locales-gv	Linux
locales-he	Linux
locales-hi	Linux
locales-hr	Linux
locales-hu	Linux
locales-hy	Linux
locales-id	Linux
locales-is	Linux
locales-it	Linux
locales-iu	Linux
locales-ja	Linux
locales-ka	Linux
locales-kl	Linux
locales-kn	Linux
locales-ko	Linux
locales-kw	Linux
locales-lo	Linux
locales-lt	Linux
locales-lv	Linux
locales-mi	Linux
locales-mk	Linux
locales-ml	Linux
locales-mn	Linux
locales-mr	Linux
locales-ms	Linux
locales-mt	Linux
locales-nl	Linux
locales-no	Linux
locales-oc	Linux
locales-ph	Linux
locales-pl	Linux
locales-pp	Linux
locales-pt	Linux
locales-ro	Linux
locales-ru	Linux
locales-se	Linux
locales-sk	Linux
locales-sl	Linux
locales-sq	Linux
locales-sr	Linux
locales-st	Linux
locales-sv	Linux
locales-ta	Linux
locales-te	Linux
locales-tg	Linux
locales-th	Linux
locales-tr	Linux
locales-tt	Linux
locales-uk	Linux
locales-ur	Linux
locales-uz	Linux
locales-vi	Linux
locales-wa	Linux
locales-xh	Linux
locales-yi	Linux
locales-zh	Linux
locales-zu	Linux
aspell-br	Linux
aspell-ca	Linux
aspell-cy	Linux
aspell-da	Linux
aspell-de	Linux
aspell-el	Linux
aspell-en	Linux
aspell-eo	Linux
aspell-es	Linux
aspell-fo	Linux
aspell-fr	Linux
aspell-ga	Linux
aspell-hr	Linux
aspell-hu	Linux
aspell-it	Linux
aspell-nl	Linux
aspell-no	Linux
aspell-pl	Linux
aspell-pt	Linux
aspell-ro	Linux
aspell-ru	Linux
aspell-sk	Linux
aspell-sv	Linux
aspell-uk	Linux
libaspell15	Linux
libaspell15-devel	Linux
libbzip2_1-devel	Linux
ftp-client-krb5	Linux
perl-Compress-Zlib	PERL
libcurl2-devel	Linux
perl-Data-ShowTable	PERL
perl-DateManip	PERL
libdb3.3	Linux
libdbtcl3.3	Linux
libdbtcl4.1	Linux
tcllib	Linux
perl-DBD-Pg	PERL
perl-DBD-Pg	PostgreSQL
dev86-devel	Linux
Digest	PERL
gettext	Linux
gettext-devel	Linux
HDF	Linux
hdf5	Linux
HDF-util	Linux
intltool	Linux
libexif9	Linux
libexif9-devel	Linux
libfontconfig1-devel	Linux
libfreetype6-devel	Linux
libfreetype6-static-devel	Linux
libgimpprint1	Linux
libgimpprint1-devel	Linux
libgmp3	Linux
libgmp3-devel	Linux
libhdf5_0	Linux
libhdf5_0-devel	Linux
libjpeg62-devel	Linux
libjpeg62-static-devel	Linux
libjpeg-progs	Linux
liblcms1	Linux
liblcms1-devel	Linux
libMagick5.5.7	Linux
libMagick5.5.7-devel	Linux
libnetpbm9	Linux
libnetpbm9-devel	Linux
libnetpbm9-static-devel	Linux
libpng3-devel	Linux
libpng3-static-devel	Linux
libpython2.3-devel	Python
libtiff3-devel	Linux
libtiff3-static-devel	Linux
libtiff-progs	Linux
libwmf0.2_7	Linux
libwmf0.2_7-devel	Linux
libwmf	Linux
libxfree86-devel	Linux
libxfree86-static-devel	Linux
libxml2-python	Python
libxml2-python	XML
libxml2-utils	XML
libxpm4-devel	Linux
libxslt1	XML
libxslt1-devel	XML
libmcrypt4	Encryption
libmhash2	Linux
netpbm	Linux
perl-Apache-Filter	PERL
perl-Apache-Filter	Apache
perl-Apache-Session	PERL
perl-Apache-Session	Apache
perl-Apache-SSI	PERL
perl-Apache-SSI	Apache
perl-Array-RefElem	PERL
perl-Authen-PAM	PERL
perl-Authen-Smb	PERL
perl-CGI-Fast	PERL
perl-CGI-Fast	Apache
perl-Convert-BER	PERL
perl-Crypt-OpenSSL-DSA	PERL
perl-Crypt-OpenSSL-DSA	Encryption
perl-Crypt-OpenSSL-RSA	PERL
libltdl3-devel	Linux
perl-Crypt-OpenSSL-RSA	Encryption
perl-Crypt-SSLeay	PERL
libwv-1.0_0	Linux
perl-Crypt-SSLeay	Encryption
perl-Curses	PERL
perl-Data-Dump	PERL
perl-Data-DumpXML	PERL
perl-Data-DumpXML	XML
libmcrypt4-devel	Encryption
perl-DBI-ProfileDumper-Apache	PERL
perl-DBI-ProfileDumper-Apache	Apache
perl-DBI-proxy	PERL
perl-DBIx-Recordset	PERL
perl-Digest-BubbleBabble	PERL
perl-Digest-MD2	PERL
perl-Digest-MD2	Encryption
perl-Digest-Nilsimsa	PERL
perl-doc	PERL
perl-ExtUtils-Depends	PERL
perl-ExtUtils_F77	PERL
perl-ExtUtils_PerlPP	PERL
perl-FCGI	PERL
perl-FCGI	Apache
perl-File-NCopy	PERL
perl-File-Slurp	PERL
perl-File-Tail	PERL
perl-Filter	PERL
perlftlib	PERL
perl-GD	PERL
perl-HTML-Clean	PERL
perl-HTML-FillInForm	PERL
perl-HTML-SimpleParse	PERL
perl-Image-Size	PERL
perl-Inline	PERL
perl-IO-stringy	PERL
perl-libxml-enno	PERL
perl-libxml-enno	XML
perl-libxml-perl	PERL
perl-libxml-perl	XML
perl-Magick	PERL
perl-Mail-Sender	PERL
perl-Mail-Sendmail	PERL
perl-Mail-SpamAssassin	PERL
perl-Mail-SpamAssassin	E-Mail
perl-Mail-Sendmail	E-Mail
perl-Mail-Sender	E-Mail
perl-MailTools	E-Mail
perl-MailTools	PERL
perl-MDK-Common-devel	PERL
perl-MIME-tools	PERL
perl-MLDBM	PERL
perl-MLDBM-Sync	PERL
perl-Mon	PERL
perl-MP3-Info	PERL
perl-Msgcat	PERL
perl-Mysql	PERL
perl-Mysql	MySQL
perl-Net-Daemon	PERL
perl-Net-DNS	PERL
perl-Net-DNS-SEC	PERL
perl-Net-IPv4Addr	PERL
perl-Net_SSLeay	PERL
perl-Net-Telnet	PERL
perl-Net_SSLeay	Encryption
perl-Net-XWhois	PERL
perl-Parse-RecDescent	PERL
perl-Parse-Yapp	PERL
perl-Period	PERL
perl-PerlIO-gzip	PERL
perl-PlRPC	PERL
perl-Razor-Agent	PERL
perl-String-ShellQuote	PERL
perl-Term-Readline-Gnu	PERL
perl-Text-Template	PERL
perl-Tie-Cache	PERL
perl-Tie-TextDir	PERL
perl-TimeDate	PERL
perl-Tk	PERL
perl-Tk-devel	PERL
perl-Tk-doc	PERL
perl-XML-Encoding	PERL
perl-XML-Encoding	XML
perl-XML-LibXML	PERL
perl-XML-LibXML	XML
perl-XML-LibXML-Common	PERL
perl-XML-LibXML-Common	XML
perl-XML-LibXSLT	PERL
perl-XML-LibXSLT	XML
perl-XML-RSS	PERL
perl-XML-RSS	XML
perl-XML-Simple	PERL
perl-XML-Simple	XML
perl-XML-Twig	PERL
perl-XML-Twig	XML
perl-XML-Writer	PERL
perl-XML-Writer	XML
perl-XML-XSLT	PERL
perl-XML-XSLT	XML
python-imaging	Python
pythonlib	Python
python-numeric	Python
python-numeric-devel	Python
python-utmp	Python
tkcvs	Linux
libelfutils1-devel	Linux
libelfutils1-static-devel	Linux
popt-devel	Linux
rpm-devel	Linux
libfftw2	Linux
libfftw2-devel	Linux
freetype2-tools	Linux
gd-utils	Linux
libgd2-devel	Linux
libgd2-static-devel	Linux
libglib1.2-devel	Linux
pkgconfig	Linux
glibc-i18ndata	Linux
glibc-static-devel	Linux
glibc-utils	Linux
glib-gettextize	Linux
libatk1.0_0-devel	Linux
libgdk_pixbuf2.0_0-devel	Linux
libglib2.0_0-devel	Linux
libgtk+1.2	Linux
libgtk+1.2-devel	Linux
libgtk+2.0_0-devel	Linux
castor	Java
libwv-1.0_0-devel	Linux
spamassassin	E-Mail
spamassassin-tools	E-Mail
spamassassin	PERL
spamassassin-tools	PERL
tetex-dvips	Linux
tetex-latex	Linux
ant	Java
libmhash2-devel	Linux
libmng1	Linux
libmng1-devel	Linux
libmng1-static-devel	Linux
libungif4	Linux
libungif4-devel	Linux
libungif4-static-devel	Linux
libMesaGL1	X11
libgpm1-devel	Linux
libncurses5-devel	Linux
ncurses-extraterms	Linux
foomatic-db	Linux
foomatic-db-engine	Linux
foomatic-filters	Linux
libgtkmm1.2	Linux
libgtkmm1.2-devel	Linux
libgtkmm1.2-static-devel	Linux
libijs0	Linux
libijs0-devel	Linux
libsigc++1.0	Linux
libsigc++1.0-devel	Linux
libsigc++1.0-examples	Linux
omni	Linux
printer-filters	Linux
psutils	Linux
PDFlib	Linux
libreadline4-devel	Linux
libpcap0	Linux
libpcap0-devel	Linux
VFlib2-devel	Linux
telnet-client-krb5	Linux
telnet-server-krb5	Linux
cdialog	Linux
libnet-snmp50-devel	Linux
libnet-snmp50-static-devel	Linux
libMesaGLU1-devel	X11
libnas2	Linux
libnas2-devel	Linux
libnas2-static-devel	Linux
libqt3	Linux
libqt3-devel	Linux
libqt3-mysql	Linux
libqt3-mysql	MySQL
libqt3-odbc	Linux
libunixODBC2	Linux
libunixODBC2-qt	Linux
libunixODBC2-devel	Linux
nas	Linux
qt3-common	Linux
qt3-example	Linux
wv-devel	Linux
libXaw3d7	X11
libXaw3d7-devel	X11
libgdome0	XML
libgdome0-devel	XML
mysql-connector-java	Java
libdb4.1-devel	Linux
mysql-connector-java	MySQL
libdb4.1-static-devel	Linux
libdbcxx4.1	Linux
libldap2-devel	Linux
libldap2-devel-static	Linux
libsasl2-devel	Linux
tcp_wrappers-devel	Linux
apache-modules	Apache
libsasl2-plug-crammd5	Linux
db1-devel	Linux
db1-tools	Linux
libmm1	Linux
libmm1-devel	Linux
libmm1-static-devel	Linux
apache-source	Apache
db3-utils	Linux
libsasl2-plug-crammd5	Encryption
libsasl2-plug-digestmd5	Linux
libsasl2-plug-digestmd5	Encryption
Mail-SpamAssassin	PERL
libsasl2-plug-gssapi	Linux
libsasl2-plug-gssapi	Encryption
libsasl2-plug-login	Linux
libsasl2-plug-plain	Linux
eject	Linux
struts	Java
Mail-SpamAssassin	E-Mail
jetspeed	Java
bcel	Java
ldetect-lst	Linux
bsf	Java
cactus	Java
netprofile	Linux
jakarta-commons-chain	Java
jakarta-commons-cli	Java
jakarta-commons-codec	Java
jakarta-commons-collections	Java
jakarta-commons-configuration	Java
jakarta-commons-daemon	Java
jakarta-commons-dbcp	Java
jakarta-commons-dbutils	Java
jakarta-commons-digester	Java
jakarta-commons-discovery	Java
jakarta-commons-el	Java
jakarta-commons-fileupload	Java
jakarta-commons-httpclient	Java
jakarta-commons-io	Java
jakarta-commons-jelly	Java
jakarta-commons-jexl	Java
jakarta-commons-lang	Java
jakarta-commons-jxpath	Java
jakarta-commons-launcher	Java
jakarta-commons-logging	Java
jakarta-commons-math	Java
jakarta-commons-modeler	Java
dhcp-client	Linux
dhcp-common	Linux
dhcp-server	Linux
jakarta-commons-net	Java
jakarta-commons-pool	Java
jakarta-commons-primitives	Java
jakarta-commons-transaction	Java
jakarta-commons-validator	Java
jakarta-poi	Java
jakarta-tapestry	Java
jakarta-velocity	Apache
jakarta-velocity	Java
jakarta-velocity-tools	Java
forrest	Java
forrest	XML
lucene	Java
myfaces	Java
axis	Java
jaxme	Java
juddi	Java
wsif	Java
batik	Java
batik	XML
acl	Linux
acpid	Linux
anacron	Linux
apr	Apache
apr-util	Apache
at	Linux
attr	Linux
audit	Linux
audit-libs	Linux
authconfig	Linux
autofs	Linux
automake14	Linux
automake15	Linux
automake16	Linux
automake17	Linux
beecrypt	Encryption
bind-libs	Linux
bluez-bluefw	Linux
bluez-hcidump	Linux
bluez-libs	Linux
bluez-utils	Linux
cdecl	Linux
cdparanoia-libs	Linux
checkpolicy	Linux
compat-db	Linux
compat-libcom_err	Linux
compat-libgcc-296	Linux
compat-libstdc++-296	Linux
compat-libstdc++-33	Linux
compat-openldap	Linux
comps	Linux
crash	Linux
crypto-utils	Linux
crypto-utils	Encryption
cryptsetup	Linux
cryptsetup	Encryption
cscope	Linux
ctags	Linux
cups	Linux
cups-libs	Linux
cyrus-sasl-gssapi	Linux
cyrus-sasl-ntlm	Linux
db4	Linux
db4-devel	Linux
db4-utils	Linux
dbus	Linux
dbus-devel	Linux
dbus-glib	Linux
dbus-python	Python
desktop-file-utils	Linux
device-mapper	Linux
dhclient	Linux
dhcpv6_client	Linux
diffstat	Linux
diskdumputils	Linux
distcache	Linux
dmraid	Linux
dos2unix	Linux
dump	Linux
elfutils-libelf	Linux
emacs-common	Linux
ethtool	Linux
fbset	Linux
gamin	Linux
glib2	Linux
glib2-devel	Linux
glibc-headers	Linux
glibc-kernheaders	Linux
grub	Linux
hal	Linux
hesiod	Linux
hotplug	Linux
htmlview	Linux
httpd	Apache
httpd-suexec	Apache
hwdata	Linux
indent	Linux
ipsec-tools	Linux
ipsec-tools	Encryption
iptstate	Linux
irda-utils	Linux
isdn4k-utils	Linux
jpackage-utils	Java
jwhois	Linux
kbd	Linux
kernel-devel	Linux
kernel-smp-devel	Linux
kernel-utils	Linux
krb5-workstation	Linux
kudzu	Linux
lftp	Linux
lha	Linux
libacl	Linux
libattr	Linux
libc-client	Linux
libdbi	Linux
libexif	Linux
libf2c	Linux
libgcrypt	Encryption
libgpg-error	Encryption
libidn	Linux
libidn-devel	Linux
libobjc	Linux
libpcap	Linux
libselinux	Linux
libselinux-devel	Linux
libsepol	Linux
libtermcap-devel	Linux
libusb	Linux
libuser-devel	Linux
libwvstreams	Linux
lm_sensors	Linux
lockdev	Linux
lockdev-devel	Linux
logwatch	Linux
lrzsz	Linux
lvm2	Linux
mcelog	Linux
mdadm	Linux
memtest86+	Linux
mgetty	Linux
minicom	Linux
module-init-tools	Linux
mozilla-nspr	Linux
mozilla-nss	Linux
mtools	Linux
mtr	Linux
mt-st	Linux
nano	Linux
netconfig	Linux
netdump	Linux
newt	Linux
newt-devel	Linux
newt-perl	PERL
nss_db	Linux
nss_ldap	Linux
ntsysv	Linux
numactl	Linux
openssl096b	Encryption
pam_ccreds	Linux
pam_krb5	Linux
pam_passwdqc	Linux
pam_smb	Linux
parted	Linux
patchutils	Linux
pax	Linux
pciutils	Linux
pciutils-devel	Linux
pcmcia	Linux
pcre	Linux
pdksh	Linux
perl-LDAP	PERL
perl-XML-Dumper	PERL
perl-XML-Dumper	XML
perl-XML-Grove	PERL
perl-XML-Grove	XML
pinfo	Linux
policycoreutils	Linux
ppp	Linux
prelink	Linux
psacct	Linux
psgml	Linux
pstack	Linux
pyOpenSSL	Python
pyOpenSSL	Encryption
python-ldap	Python
pyxf86config	X11
pyxf86config	Python
PyXML	Python
PyXML	XML
quota	Linux
rcs	Linux
redhat-lsb	Linux
redhat-menus	Linux
redhat-rpm-config	Linux
rhnlib	Linux
rhnlib	Python
rhpl	Linux
rhpl	Python
rpmdb-redhat-4	Linux
rpm-libs	Linux
rpm-python	Linux
rpm-python	Python
rp-pppoe	Linux
rsh	Linux
ruby-libs	Linux
schedutils	Linux
selinux-policy-targeted	Linux
setarch	Linux
setools	Linux
setuptool	Linux
sgml-common	Linux
shared-mime-info	Linux
slang-devel	Linux
specspo	Linux
splint	Linux
statserial	Linux
sudo	Linux
sysfsutils	Linux
sysfsutils-devel	Linux
sysreport	Linux
system-config-mouse	Linux
system-config-network-tui	Linux
system-config-securitylevel-tui	Linux
ttmkfdir	Linux
tzdata	Linux
udev	Linux
unix2dos	Linux
up2date	Linux
usbutils	Linux
valgrind	Linux
valgrind-callgrind	Linux
vconfig	Linux
w3c-libwww	Linux
wireless-tools	Linux
wvdial	Linux
xml-common	XML
xmlsec1	XML
xmlsec1	Encryption
xmlsec1-openssl	XML
xmlsec1-openssl	Encryption
xorg-x11-libs	X11
xorg-x11-Mesa-libGL	X11
iptraf	Linux
\.
