select "schema".add_column('net', 'ip_reputation_limiter_limits', 'pkey',                 0, 'pkey',   false, true,  false, 'a generated, unique key',       '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'limiter',              1, 'fkey',   false, false, false, 'the identifier of the limiter', '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'class',                2, 'string', false, false, false, 'the reputation class',          '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'syn_per_ip_burst',     3, 'short',  false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'syn_per_ip_rate',      4, 'short',  false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'syn_per_ip_unit',      5, 'string', false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'syn_per_ip_size',      6, 'short',  false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'syn_burst',            7, 'short',  false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'syn_rate',             8, 'short',  false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'syn_unit',             9, 'string', false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'packet_per_ip_burst', 10, 'short',  false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'packet_per_ip_rate',  11, 'short',  false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'packet_per_ip_unit',  12, 'string', false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'packet_per_ip_size',  13, 'short',  false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'packet_burst',        14, 'short',  false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'packet_rate',         15, 'short',  false, false, false, '',                              '1.66', null);
select "schema".add_column('net', 'ip_reputation_limiter_limits', 'packet_unit',         16, 'string', false, false, false, '',                              '1.66', null);
