select "schema".add_column('net', 'net_binds', 'pkey',                  'pkey',       false,  true, false, 'a generated pkey', '1.0a100', null);
select "schema".add_column('net', 'net_binds', 'package',               'package',    false, false, false, 'the package that owns the opened port', '1.0a100', '1.80');
select "schema".add_column('net', 'net_binds', 'package',               'accounting', false, false, false, 'the package that owns the opened port', '1.80.0', null);
select "schema".add_column('net', 'net_binds', 'ao_server',             'fkey',       false, false, false, 'the pkey of the server that this port is bound on', '1.0a100', '1.32');
select "schema".add_column('net', 'net_binds', 'server',                'fkey',       false, false, false, 'the pkey of the server that this port is bound on', '1.33', null);
select "schema".add_column('net', 'net_binds', 'ip_address',            'fkey',       false, false, false, 'the pkey of the IP address that is bound to', '1.0a100', null);
select "schema".add_column('net', 'net_binds', 'port',                  'int',        false, false, false, 'the port number that is bound', '1.0a100', '1.68');
select "schema".add_column('net', 'net_binds', 'port',                  'fkey',       false, false, false, 'the port number that is bound', '1.69', '1.80');
select "schema".add_column('net', 'net_binds', 'port',                  'net_port',   false, false, false, 'the port that is bound', '1.80.0', null);
select "schema".add_column('net', 'net_binds', 'net_protocol',          'string',     false, false, false, 'the network protocol (<code>net_protocols</code>)', '1.0a100', '1.80');
select "schema".add_column('net', 'net_binds', 'app_protocol',          'string',     false, false, false, 'the application protocol (<code>protocols</code>)', '1.0a100', null);
select "schema".add_column('net', 'net_binds', 'open_firewall',         'boolean',    false, false, false, 'flags if the firewall should be opened for this port', '1.0a100', '1.80.2');
select "schema".add_column('net', 'net_binds', 'monitor_delay',         'int',         true, false, false, '', '1.0a100', '1.0a103');
select "schema".add_column('net', 'net_binds', 'monitor_parameter',     'string',      true, false, false, '', '1.0a100', '1.0a103');
select "schema".add_column('net', 'net_binds', 'monitor_contact',       'string',      true, false, false, '', '1.0a100', '1.0a103');
select "schema".add_column('net', 'net_binds', 'monitor_info',          'string',      true, false, false, '', '1.0a100', '1.0a103');
select "schema".add_column('net', 'net_binds', 'monitoring_enabled',    'boolean',    false, false, false, 'turns on monitoring of the port', '1.0a104', null);
select "schema".add_column('net', 'net_binds', 'monitoring_parameters', 'string',      true, false, false, 'the URL-encoded name=value pairs of monitoring parameters', '1.58', null);
