select "schema".add_column('mysql', 'mysql_databases', 'pkey',                        'pkey',                false,  true, false, 'a unique, generated primary key', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_databases', 'name',                        'string',              false, false, false, 'the name of the database', '1.0a100', '1.80');
select "schema".add_column('mysql', 'mysql_databases', 'name',                        'mysql_database_name', false, false, false, 'the name of the database', '1.80.0', null);
select "schema".add_column('mysql', 'mysql_databases', 'ao_server',                   'fkey',                false, false, false, 'the pkey of the server that this database is hosted on', '1.0a100', '1.3');
select "schema".add_column('mysql', 'mysql_databases', 'mysql_server',                'fkey',                false, false, false, 'the pkey of the server that this database is hosted on', '1.4', null);
select "schema".add_column('mysql', 'mysql_databases', 'package',                     'package',             false, false, false, 'the package that this database is part of', '1.0a100', '1.80');
select "schema".add_column('mysql', 'mysql_databases', 'package',                     'accounting',          false, false, false, 'the package that this database is part of', '1.80.0', null);
select "schema".add_column('mysql', 'mysql_databases', 'backup_level',                'short',               false, false, false, 'the number of backup copies to keep', '1.0a100', '1.30');
select "schema".add_column('mysql', 'mysql_databases', 'backup_retention',            'short',               false, false, false, 'the number of days backups will be kept', '1.0a100', '1.30');
select "schema".add_column('mysql', 'mysql_databases', 'max_check_table_alert_level', 'string',              false, false, false, 'the maximum alert level created for the check table monitoring of this database', '1.74', null);
