CREATE TYPE payment."AuthorizationResult.DeclineReason" AS ENUM (
  'NO_SPECIFIC',
  'EXPIRED_CARD',
  'PICK_UP_CARD',
  'AVS_MISMATCH',
  'CVV2_MISMATCH',
  'FRAUD_DETECTED',
  'BLOCKED_IP',
  'MANUAL_REVIEW',
  'INSUFFICIENT_FUNDS',
  'MAX_SALE_EXCEEDED',
  'MIN_SALE_NOT_MET',
  'VOLUME_EXCEEDED_1_DAY',
  'USAGE_EXCEEDED_1_DAY',
  'VOLUME_EXCEEDED_3_DAYS',
  'USAGE_EXCEEDED_3_DAYS',
  'VOLUME_EXCEEDED_15_DAYS',
  'USAGE_EXCEEDED_15_DAYS',
  'VOLUME_EXCEEDED_30_DAYS',
  'USAGE_EXCEEDED_30_DAYS',
  'STOLEN_OR_LOST_CARD',
  'AVS_FAILURE',
  'NOT_PROVIDED',
  'UNKNOWN'
);
COMMENT ON TYPE payment."AuthorizationResult.DeclineReason" IS
'Matches enum com.aoindustries.creditcards.AuthorizationResult.DeclineReason';
