select "schema".add_column('payment', 'credit_card_processors', 'provider_id', 0, 'string', false, true, false, 'the unique ID of this processor', '1.29', null);
select "schema".add_column('payment', 'credit_card_processors', 'accounting', 1, 'accounting', false, false, false, 'the accounting code of the business owning the merchant account', '1.29', null);
select "schema".add_column('payment', 'credit_card_processors', 'class_name', 2, 'string', false, false, false, 'the classname of the Java code that connects to the merchant services provider', '1.29', null);
select "schema".add_column('payment', 'credit_card_processors', 'param1', 3, 'string', true, false, false, 'the optional parameters for the Java code that connects to the merchant services provider', '1.29', null);
select "schema".add_column('payment', 'credit_card_processors', 'param2', 4, 'string', true, false, false, 'the optional parameters for the Java code that connects to the merchant services provider', '1.29', null);
select "schema".add_column('payment', 'credit_card_processors', 'param3', 5, 'string', true, false, false, 'the optional parameters for the Java code that connects to the merchant services provider', '1.29', null);
select "schema".add_column('payment', 'credit_card_processors', 'param4', 6, 'string', true, false, false, 'the optional parameters for the Java code that connects to the merchant services provider', '1.29', null);
select "schema".add_column('payment', 'credit_card_processors', 'enabled', 7, 'boolean', false, false, false, 'the enabled flag', '1.29', null);
select "schema".add_column('payment', 'credit_card_processors', 'weight', 8, 'int', false, false, false, 'the weight used for multi-processor weighted transaction distribution', '1.29', null);
select "schema".add_column('payment', 'credit_card_processors', 'description', 9, 'string', true, false, false, 'an optional description of the processor', '1.29', null);
select "schema".add_column('payment', 'credit_card_processors', 'encryption_from', 10, 'fkey', false, false, false, 'the from that will be used for encryption', '1.31', null);
select "schema".add_column('payment', 'credit_card_processors', 'encryption_recipient', 11, 'fkey', false, false, false, 'the recipient that will be used for encryption', '1.31', null);
