select "schema".add_foreign_key('ticket', 'ticket_actions', 'ticket',                    'tickets',                 'pkey',       '1.44',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'administrator',  'public',  'business_administrators', 'username',   '1.44',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'action_type',               'ticket_action_types',     'type',       '1.44',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'old_accounting', 'public',  'businesses',              'accounting', '1.44',   '1.68');
select "schema".add_foreign_key('ticket', 'ticket_actions', 'old_accounting', 'public',  'businesses',              'accounting', '1.69',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'new_accounting', 'public',  'businesses',              'accounting', '1.44',   '1.68');
select "schema".add_foreign_key('ticket', 'ticket_actions', 'new_accounting', 'public',  'businesses',              'accounting', '1.69',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'old_priority',              'ticket_priorities',       'priority',   '1.44',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'new_priority',              'ticket_priorities',       'priority',   '1.44',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'old_type',                  'ticket_types',            'type',       '1.49',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'new_type',                  'ticket_types',            'type',       '1.49',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'old_status',                'ticket_stati',            'status',     '1.44',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'new_status',                'ticket_stati',            'status',     '1.44',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'old_assigned_to', 'public', 'business_administrators', 'username',   '1.44',   '1.80');
select "schema".add_foreign_key('ticket', 'ticket_actions', 'old_assigned_to', 'public', 'business_administrators', 'username',   '1.80.0', null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'new_assigned_to', 'public', 'business_administrators', 'username',   '1.44',   '1.80');
select "schema".add_foreign_key('ticket', 'ticket_actions', 'new_assigned_to', 'public', 'business_administrators', 'username',   '1.80.0', null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'old_category',              'ticket_categories',       'pkey',       '1.44',   null);
select "schema".add_foreign_key('ticket', 'ticket_actions', 'new_category',              'ticket_categories',       'pkey',       '1.44',   null);
