select "schema".add_column('mysql', 'mysql_users', 'username', 0, 'username', false, true, false, 'the username of the MySQL user', '1.0a100', '1.80');
select "schema".add_column('mysql', 'mysql_users', 'username', 1, 'mysql_username', false, true, false, 'the username of the MySQL user', '1.80.0', null);
select "schema".add_column('mysql', 'mysql_users', 'select_priv', 2, 'boolean', false, false, false, 'the SELECT privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'insert_priv', 3, 'boolean', false, false, false, 'the INSERT privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'update_priv', 4, 'boolean', false, false, false, 'the UPDATE privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'delete_priv', 5, 'boolean', false, false, false, 'the DELETE privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'create_priv', 6, 'boolean', false, false, false, 'the CREATE privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'drop_priv', 7, 'boolean', false, false, false, 'the DROP privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'reload_priv', 8, 'boolean', false, false, false, 'the RELOAD privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'shutdown_priv', 9, 'boolean', false, false, false, 'the SHUTDOWN privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'process_priv', 10, 'boolean', false, false, false, 'the PROCESS privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'file_priv', 11, 'boolean', false, false, false, 'the FILE privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'grant_priv', 12, 'boolean', false, false, false, 'the GRANT privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'references_priv', 13, 'boolean', false, false, false, 'the REFERENCES privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'index_priv', 14, 'boolean', false, false, false, 'the INDEX privilege to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'alter_priv', 15, 'boolean', false, false, false, 'the ALTER privilete to all databases', '1.0a100', null);
select "schema".add_column('mysql', 'mysql_users', 'show_db_priv', 16, 'boolean', false, false, false, '', '1.0a111', null);
select "schema".add_column('mysql', 'mysql_users', 'super_priv', 17, 'boolean', false, false, false, '', '1.0a111', null);
select "schema".add_column('mysql', 'mysql_users', 'create_tmp_table_priv', 18, 'boolean', false, false, false, '', '1.0a111', null);
select "schema".add_column('mysql', 'mysql_users', 'lock_tables_priv', 19, 'boolean', false, false, false, '', '1.0a111', null);
select "schema".add_column('mysql', 'mysql_users', 'execute_priv', 20, 'boolean', false, false, false, '', '1.0a111', null);
select "schema".add_column('mysql', 'mysql_users', 'repl_slave_priv', 21, 'boolean', false, false, false, '', '1.0a111', null);
select "schema".add_column('mysql', 'mysql_users', 'repl_client_priv', 22, 'boolean', false, false, false, '', '1.0a111', null);
select "schema".add_column('mysql', 'mysql_users', 'create_view_priv', 23, 'boolean', false, false, false, '', '1.4', null);
select "schema".add_column('mysql', 'mysql_users', 'show_view_priv', 24, 'boolean', false, false, false, '', '1.4', null);
select "schema".add_column('mysql', 'mysql_users', 'create_routine_priv', 25, 'boolean', false, false, false, '', '1.4', null);
select "schema".add_column('mysql', 'mysql_users', 'alter_routine_priv', 26, 'boolean', false, false, false, '', '1.4', null);
select "schema".add_column('mysql', 'mysql_users', 'create_user_priv', 27, 'boolean', false, false, false, '', '1.4', null);
select "schema".add_column('mysql', 'mysql_users', 'event_priv', 28, 'boolean', false, false, false, 'the Event_priv', '1.54', null);
select "schema".add_column('mysql', 'mysql_users', 'trigger_priv', 29, 'boolean', false, false, false, 'the Trigger_priv', '1.54', null);
select "schema".add_column('mysql', 'mysql_users', 'disable_log', 30, 'fkey', true, false, false, 'indicates that this account is disabled', '1.0a100', null);
