create table mysql_users (
  username text
    primary key,
  select_priv boolean
    not null
    default false,
  insert_priv boolean
    not null
    default false,
  update_priv boolean
    not null
    default false,
  delete_priv boolean
    not null
    default false,
  create_priv boolean
    not null
    default false,
  drop_priv boolean
    not null
    default false,
  reload_priv boolean
    not null
    default false,
  shutdown_priv boolean
    not null
    default false,
  process_priv boolean
    not null
    default false,
  file_priv boolean
    not null
    default false,
  grant_priv boolean
    not null
    default false,
  references_priv boolean
    not null
    default false,
  index_priv boolean
    not null
    default false,
  alter_priv boolean
    not null
    default false,
  show_db_priv boolean
    not null
    default false,
  super_priv boolean
    not null
    default false,
  create_tmp_table_priv boolean
    not null
    default false,
  lock_tables_priv boolean
    not null
    default false,
  execute_priv boolean
    not null
    default false,
  repl_slave_priv boolean
    not null
    default false,
  repl_client_priv boolean
    not null
    default false,
  create_view_priv boolean
    not null
    default false,
  show_view_priv boolean
    not null
    default false,
  create_routine_priv boolean
    not null
    default false,
  alter_routine_priv boolean
    not null
    default false,
  create_user_priv boolean
    not null
    default false,
  event_priv boolean
    not null
    default false,
  trigger_priv boolean
    not null
    default false,
  disable_log integer
);
grant all                            on mysql_users to aoadmin;
grant select, insert, update, delete on mysql_users to aoserv_app;
