select "schema".add_column('accounting', 'bank_transactions', 'time',             'time',      false, false, false, 'the time the transaction occured', '1.0a100', null);
select "schema".add_column('accounting', 'bank_transactions', 'transid',          'int',       false,  true, false, 'a unique identifier for the transaction', '1.0a100', '1.68');
select "schema".add_column('accounting', 'bank_transactions', 'transid',          'pkey',      false,  true, false, 'a unique identifier for the transaction', '1.69', null);
select "schema".add_column('accounting', 'bank_transactions', 'bank_account',     'string',    false, false, false, 'the account the transaction is for', '1.0a100', null);
select "schema".add_column('accounting', 'bank_transactions', 'merchant_account', 'string',     true, false, false, 'the merchant account the transaction is for', '1.0a100', '1.28');
select "schema".add_column('accounting', 'bank_transactions', 'processor',        'string',     true, false, false, 'the credit card processor used by this transaction', '1.29', null);
select "schema".add_column('accounting', 'bank_transactions', 'administrator',    'username',  false, false, false, 'the business_administrator who made this transaction', '1.0a100', null);
select "schema".add_column('accounting', 'bank_transactions', 'type',             'string',    false, false, false, 'the type of transaction', '1.0a100', null);
select "schema".add_column('accounting', 'bank_transactions', 'expense_code',     'string',     true, false, false, 'the category in which this expense belongs', '1.0a100', null);
select "schema".add_column('accounting', 'bank_transactions', 'description',      'string',    false, false, false, 'a description of the transaction', '1.0a100', null);
select "schema".add_column('accounting', 'bank_transactions', 'check_no',         'string',     true, false, false, 'the check number (if available)', '1.0a100', null);
select "schema".add_column('accounting', 'bank_transactions', 'amount',           'decimal_2', false, false, false, 'the amount (negative for withdrawal)', '1.0a100', null);
select "schema".add_column('accounting', 'bank_transactions', 'confirmed',        'boolean',   false, false, false, 'the confirmation status with bank', '1.0a100', null);
