select "schema".add_column('email', 'email_smtp_relays', 'pkey',           'pkey',       false,  true, false, 'a generated unique key', '1.0a100', null);
select "schema".add_column('email', 'email_smtp_relays', 'package',        'package',    false, false, false, 'the package that owns this entry', '1.0a100', '1.80');
select "schema".add_column('email', 'email_smtp_relays', 'package',        'accounting', false, false, false, 'the package that owns this entry', '1.80.0', null);
select "schema".add_column('email', 'email_smtp_relays', 'ao_server',      'fkey',        true, false, false, 'the pkey of the server that the rule applies to', '1.0a100', null);
select "schema".add_column('email', 'email_smtp_relays', 'host',           'string',     false, false, false, 'the hostname or IP the rule applies to', '1.0a100', '1.68');
select "schema".add_column('email', 'email_smtp_relays', 'host',           'hostname',   false, false, false, 'the hostname or IP the rule applies to', '1.69', null);
select "schema".add_column('email', 'email_smtp_relays', 'type',           'string',     false, false, false, 'the type of entry', '1.0a100', null);
select "schema".add_column('email', 'email_smtp_relays', 'created',        'time',       false, false, false, 'the time the entry was created', '1.0a100', null);
select "schema".add_column('email', 'email_smtp_relays', 'last_refreshed', 'time',       false, false, false, 'the time the entry was last updated', '1.0a100', null);
select "schema".add_column('email', 'email_smtp_relays', 'refresh_count',  'int',        false, false, false, 'the number of times the entry has been updated', '1.0a100', null);
select "schema".add_column('email', 'email_smtp_relays', 'expiration',     'time',        true, false, false, 'the expiration time of the entry, or null if non-expiring', '1.0a100', null);
select "schema".add_column('email', 'email_smtp_relays', 'disable_log',    'fkey',        true, false, false, 'indicates that the rule is disabled', '1.0a100', null);
