select "schema".add_column('account', 'business_administrators', 'username', 0, 'username', false, true, false, 'the unique identifier for this admin', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'password', 1, 'string', false, false, false, 'the encrypted password for this admin', '1.0a100', '1.68');
select "schema".add_column('account', 'business_administrators', 'password', 2, 'hashed_password', true, false, false, 'the encrypted password for this admin', '1.69', null);
select "schema".add_column('account', 'business_administrators', 'name', 3, 'string', false, false, false, 'the name of this admin', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'title', 4, 'string', true, false, false, 'the admins title within their organization', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'birthday', 5, 'time', true, false, false, 'the admins birthday', '1.0a100', '1.68');
select "schema".add_column('account', 'business_administrators', 'birthday', 6, 'date', true, false, false, 'the admins birthday', '1.69', null);
select "schema".add_column('account', 'business_administrators', 'is_preferred', 7, 'boolean', false, false, false, 'if true, customers is preferred', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'private', 8, 'boolean', false, false, false, 'indicates if the admin should not be listed in publicly available lists', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'created', 9, 'time', false, false, false, 'the time the admin entry was created', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'work_phone', 10, 'phone', false, false, false, 'the work phone number (if different than business)', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'home_phone', 11, 'phone', true, false, false, 'the home phone number', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'cell_phone', 12, 'phone', true, false, false, 'the cellular phone number', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'fax', 13, 'phone', true, false, false, 'the fax number (if different than business)', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'email', 14, 'email', false, false, false, 'the email address', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'address1', 15, 'string', true, false, false, 'the street address (if different than business)', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'address2', 16, 'string', true, false, false, 'the street address (if different than business)', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'city', 17, 'city', true, false, false, 'the city (if different than business)', '1.0a100', '1.68');
select "schema".add_column('account', 'business_administrators', 'city', 18, 'string', true, false, false, 'the city (if different than business)', '1.69', null);
select "schema".add_column('account', 'business_administrators', 'state',            19, 'state', true, false, false, 'the state (if different than business)', '1.0a100', '1.68');
select "schema".add_column('account', 'business_administrators', 'state',            20, 'string', true, false, false, 'the state (if different than business)', '1.69', null);
select "schema".add_column('account', 'business_administrators', 'country',          21, 'country', true, false, false, 'the country (if different than business)', '1.0a100', '1.68');
select "schema".add_column('account', 'business_administrators', 'country',          22, 'string', true, false, false, 'the country (if different than business)', '1.69', null);
select "schema".add_column('account', 'business_administrators', 'zip',              23, 'zip', true, false, false, 'the zip code (if different than business)', '1.0a100', '1.68');
select "schema".add_column('account', 'business_administrators', 'zip',              24, 'string', true, false, false, 'the zip code (if different than business)', '1.69', null);
select "schema".add_column('account', 'business_administrators', 'disable_log',      25, 'fkey', true, false, false, 'indicates that this account is disabled', '1.0a100', null);
select "schema".add_column('account', 'business_administrators', 'can_switch_users', 26, 'boolean', false, false, false, 'allows this person to switch users to any subaccounts', '1.0a118', null);
select "schema".add_column('account', 'business_administrators', 'support_code',     27, 'string', true, true, false, 'used to authenticate for email-based supprt', '1.44', null);
