select "schema".add_column('backup', 'file_backups', 'pkey', 0, 'pkey', false, true, false, 'a generated primary key', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'server', 1, 'fkey', false, false, false, 'the server that the file resides on', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'path', 2, 'string', false, false, false, 'the pkey in file_paths for the path of this file', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'device', 3, 'short', false, false, false, 'the device that was storing this file', '1.0a100', '1.0a106');
select "schema".add_column('backup', 'file_backups', 'device', 4, 'short', true, false, false, 'the device that was storing this file', '1.0a107', '1.30');
select "schema".add_column('backup', 'file_backups', 'inode', 5, 'long', false, false, false, 'the unique identifier for this object within the device', '1.0a100', '1.0a106');
select "schema".add_column('backup', 'file_backups', 'inode', 6, 'long', true, false, false, 'the unique identifier for this object within the device', '1.0a107', '1.30');
select "schema".add_column('backup', 'file_backups', 'package', 7, 'fkey', false, false, false, 'the number of the package that owns the file', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'mode', 8, 'octal_long', false, false, false, 'the permissions and type of the file', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'uid', 9, 'int', false, false, false, 'the file owner', '1.0a100', '1.0a106');
select "schema".add_column('backup', 'file_backups', 'uid', 10, 'int', true, false, false, 'the file owner', '1.0a107', '1.30');
select "schema".add_column('backup', 'file_backups', 'gid', 11, 'int', false, false, false, 'the file group', '1.0a100', '1.0a106');
select "schema".add_column('backup', 'file_backups', 'gid', 12, 'int', true, false, false, 'the file group', '1.0a107', '1.30');
select "schema".add_column('backup', 'file_backups', 'backup_data', 13, 'fkey', true, false, false, 'the data content for the file', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'create_time', 14, 'time', false, false, false, 'the time the file backup entry was created', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'modify_time', 15, 'time', true, false, false, 'the modification time of the file the last time it was verified', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'remove_time', 16, 'time', true, false, false, 'the time the file backup entry was no longer valid', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'backup_level', 17, 'short', false, false, false, 'the number of times to store this backup', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'backup_retention', 18, 'short', false, false, false, 'the number of days the backups will be kept', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'symlink_target', 19, 'string', true, false, false, 'the target of a symbolic link', '1.0a100', '1.30');
select "schema".add_column('backup', 'file_backups', 'device_id', 20, 'long', true, false, false, 'the ID for device files', '1.0a100', '1.30');
