select "schema".add_column('ftp', 'private_ftp_servers', 'ip_address',           'fkey',        false,  true, false, 'the pkey of the net_bind that the FTP server is on', '1.0a100', '1.0a112');
select "schema".add_column('ftp', 'private_ftp_servers', 'net_bind',             'fkey',        false,  true, false, 'the root directory', '1.0a113', null);
select "schema".add_column('ftp', 'private_ftp_servers', 'root',                 'path',        false, false, false, 'the file transfers are logged to', '1.0a100', '1.38');
select "schema".add_column('ftp', 'private_ftp_servers', 'logfile',              'path',        false, false, false, 'the file transfers are logged to', '1.0a100', null);
select "schema".add_column('ftp', 'private_ftp_servers', 'hostname',             'hostname',    false, false, false, 'the hostname the server reports', '1.0a100', '1.68');
select "schema".add_column('ftp', 'private_ftp_servers', 'hostname',             'domain_name', false, false, false, 'the hostname the server reports', '1.69', null);
select "schema".add_column('ftp', 'private_ftp_servers', 'email',                'email',       false, false, false, 'the email address the server reports', '1.0a100', null);
select "schema".add_column('ftp', 'private_ftp_servers', 'price',                'decimal_2',    true, false, false, '', '1.0a100', '1.0a122');
select "schema".add_column('ftp', 'private_ftp_servers', 'created',              'time',        false, false, false, 'the time the server was added', '1.0a100', null);
select "schema".add_column('ftp', 'private_ftp_servers', 'linux_server_account', 'int',         false, false, false, '', '1.0a100', '1.68');
select "schema".add_column('ftp', 'private_ftp_servers', 'linux_server_account', 'fkey',        false, false, false, '', '1.69', null);
select "schema".add_column('ftp', 'private_ftp_servers', 'linux_server_group',   'int',         false, false, false, '', '1.0a100', '1.38');
select "schema".add_column('ftp', 'private_ftp_servers', 'allow_anonymous',      'boolean',     false, false, false, 'enabled or disabled anonymous access to the server', '1.0a113', null);
